Repository kubernetes/ingress-nginx, pull requests merged in 2018-08, with the labels that each got.

#2808 fix the bug #2799, add prefix (?i) in rewrite statement.
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  test/e2e/annotations/affinity.go
  test/e2e/annotations/rewrite.go
  test/e2e/annotations/rewrite_log.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2895 support custom configuration to main context of nginx config
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/main_snippet.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2890 Usability improvements to build steps
  Makefile
  build/build.sh
  build/go-in-docker.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2888 Fix grafana datasources
  deploy/grafana/dashboards/README.md
  deploy/grafana/dashboards/nginx.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2893 Update nginx image
  images/e2e/Dockerfile
  images/nginx/Makefile
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
  images/nginx/rootfs/entrypoint.sh
  images/nginx/rootfs/etc/authbind/byport/443
  images/nginx/rootfs/etc/authbind/byport/80
  images/nginx/rootfs/etc/authbind/byuid/33
  images/nginx/rootfs/install_lua_resty_waf.sh
Labels: approved, cncf-cla: yes, size/M

#2896 support configuring multi_accept directive via configmap
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/multi_accept.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2898 Fix default sync-period doc
  docs/user-guide/cli-arguments.md
Labels: approved, cncf-cla: yes, size/XS

#2682 Use localhost to expose status server
  internal/ingress/controller/checker.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2897 Enable reuse-port by default
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2902 Fix documentation
  docs/user-guide/exposing-tcp-udp-services.md
  docs/user-guide/nginx-configuration/configmap.md
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, size/S

#2903 Very minor grammar fix
  docs/how-it-works.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2905 Fix IPV6 detection
  .travis.yml
  internal/net/net.go
  internal/net/net_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2871 Add support for AJP protocol
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/backendprotocol/main.go
  internal/ingress/annotations/backendprotocol/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/template.go
  internal/ingress/types.go
  test/e2e/annotations/grpc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2915 dont restrict status page to localhost only
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2921 Remove echoheaders image from the repository
  docs/examples/http-svc.yaml
  docs/examples/multi-tls/multi-tls.yaml
  images/echoheaders/Dockerfile
  images/echoheaders/Makefile
  images/echoheaders/README.md
  images/echoheaders/echo-app.yaml
  images/echoheaders/nginx.conf
  images/echoheaders/run.sh
  images/echoheaders/template.lua
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2885 fix: Sort TCP/UDP upstream order
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2926 Add misspell target
  Makefile
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/third-party-addons/modsecurity.md
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2927 Release 0.18.0
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
  docs/deploy/upgrade.md
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2928 docs: Precisations on the usage of the InfluxDB module
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2932 Fixed typo in flags.go
  cmd/nginx/flags.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2912 Add documentation to install prometheus and grafana
  deploy/monitoring/configuration.yaml
  deploy/monitoring/grafana.yaml
  deploy/monitoring/prometheus.yaml
  docs/images/grafana.png
  docs/images/prometheus-dashboard.png
  docs/user-guide/monitoring.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2889 Add Lua endpoint to support dynamic certificate serving functionality
  build/test-lua.sh
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/lua/configuration.lua
  rootfs/etc/nginx/lua/test/configuration_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/L

#2925 Update nginx dependencies
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2942 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/custom-error-pages/Makefile
  images/nginx/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#2946 Add unit tests to configuration_test.lua that cover Backends configuration
  rootfs/etc/nginx/lua/test/configuration_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/L

#2857 remove unnecessary encoding/decoding also fix ipv6 issue
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/balancer/chash.lua
  rootfs/etc/nginx/lua/balancer/ewma.lua
  rootfs/etc/nginx/lua/balancer/round_robin.lua
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/test/balancer/chash_test.lua
  rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/run.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#2616 Add use-forwarded-headers configmap option.
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/forwarded_headers.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/L

#2923 Add dynamic certificate serving feature to controller
  cmd/nginx/flags.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/sslcert.go
  internal/ingress/types_equals.go
  internal/net/ssl/ssl.go
  internal/net/ssl/ssl_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2941 now actually using the $controller and $namespace variables
  deploy/grafana/dashboards/nginx.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2955 Update nginx opentracing zipkin module
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2956 Update nginx and e2e images
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2957 Batch metrics and flush periodically
  internal/ingress/metric/collectors/socket.go
  internal/ingress/metric/collectors/socket_test.go
  rootfs/etc/nginx/lua/monitor.lua
  rootfs/etc/nginx/lua/test/defer_test.lua
  rootfs/etc/nginx/lua/test/monitor_test.lua
  rootfs/etc/nginx/lua/util/defer.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2899 fixed rewrites for paths not ending in /
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  test/e2e/annotations/rewrite.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2964 fix variable parsing when key is number
  rootfs/etc/nginx/lua/test/util_test.lua
  rootfs/etc/nginx/lua/util.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#2970 Update labels
  deploy/configmap.yaml
  deploy/default-backend.yaml
  deploy/mandatory.yaml
  deploy/monitoring/configuration.yaml
  deploy/monitoring/grafana.yaml
  deploy/monitoring/prometheus.yaml
  deploy/provider/aws/patch-configmap-l4.yaml
  deploy/provider/aws/patch-configmap-l7.yaml
  deploy/provider/aws/service-l4.yaml
  deploy/provider/aws/service-l7.yaml
  deploy/provider/aws/service-nlb.yaml
  deploy/provider/baremetal/service-nodeport.yaml
  deploy/provider/cloud-generic.yaml
  deploy/tcp-services-configmap.yaml
  deploy/udp-services-configmap.yaml
  deploy/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#2962 Fix broken anchor link to GCE/GKE
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2972 consistently fallback to default certificate when TLS is configured
  internal/ingress/controller/controller.go
  test/e2e/annotations/luarestywaf.go
  test/e2e/framework/framework.go
  test/e2e/settings/tls.go
  test/e2e/ssl/secret_update.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2884 [grafana] Rate over 2 minutes since default Prometheus interval is 1m
  deploy/grafana/dashboards/nginx.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2806 add help for tls prerequisite for ingress.yaml
  docs/examples/grpc/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2977 Pass real source IP address to auth request
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2979 clear dynamic configuration e2e tests
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2966 Add unit tests for sticky lua module
  rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/L

#2983 Add documentation for enable-dynamic-certificates feature
  docs/user-guide/cli-arguments.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2987 cleanup dynamic cert e2e tests
  test/e2e/lua/dynamic_certificates.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2988 Update go to 1.11
  build/go-in-docker.sh
  images/e2e/Dockerfile
  internal/ingress/controller/nginx.go
  internal/ingress/errors/errors.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2998 fixed jsonpath command in examples
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3002 Enhance Troubleshooting Documentation
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3003 Update nginx to 1.15.3
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#3004 Update nginx image
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3005 Fix gdb issue and update e2e image
  build/go-in-docker.sh
  docs/troubleshooting.md
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#3006 apply nginx patch to make ssl_certificate_by_lua_block work properly
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
  images/nginx/rootfs/patches/openresty-ssl_cert_cb_yield.patch
Labels: approved, cncf-cla: yes, lgtm, size/M

#3011 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3021 Fix documentation search
  .travis/ingress-controller.sh
  .travis/publish-docs.sh
  .travis/publish.sh
  build/mkdocs/Dockerfile
  build/mkdocs/entrypoint.sh
  docs/deploy/upgrade.md
  docs/examples/auth/external-auth/README.md
  docs/examples/auth/oauth-external-auth/README.md
  docs/examples/docker-registry/README.md
  docs/examples/grpc/ingress.yaml
  docs/troubleshooting.md
  docs/user-guide/custom-errors.md
  docs/user-guide/default-backend.md
  docs/user-guide/miscellaneous.md
  docs/user-guide/monitoring.md
  docs/user-guide/multiple-ingress.md
  docs/user-guide/nginx-configuration/configmap.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3014 Release 0.19.0
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL
