Repository kubernetes/ingress-nginx, pull requests merged in 2018-02, with the labels that each got.

#2063 Run one test at a time
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#2065 Always return an IP address
  internal/k8s/main.go
Labels: approved, cncf-cla: yes, size/S

#2071 Update Go to 1.9.4
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#2069 Do not cancel the synchronization of secrets
  internal/ingress/controller/store/backend_ssl.go
Labels: approved, cncf-cla: yes, size/XS

#2076 Fix spelling errors
  internal/ingress/controller/store/store_test.go
Labels: approved, cncf-cla: yes, size/S

#2077 Remove initContainer from default deployment
  deploy/with-rbac.yaml
  deploy/without-rbac.yaml
  docs/examples/customization/sysctl/README.md
  docs/examples/customization/sysctl/patch.json
Labels: approved, cncf-cla: yes, size/M

#2075 Fix opentracing configuration when multiple options are configured
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/M

#2082 Use a ring channel to avoid blocking write of events
  Gopkg.lock
  Gopkg.toml
  internal/ingress/controller/nginx.go
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  vendor/github.com/eapache/channels/.gitignore
  vendor/github.com/eapache/channels/.travis.yml
  vendor/github.com/eapache/channels/CHANGELOG.md
  vendor/github.com/eapache/channels/LICENSE
  vendor/github.com/eapache/channels/README.md
  vendor/github.com/eapache/channels/batching_channel.go
  vendor/github.com/eapache/channels/batching_channel_test.go
  vendor/github.com/eapache/channels/black_hole.go
  vendor/github.com/eapache/channels/black_hole_test.go
  vendor/github.com/eapache/channels/channels.go
  vendor/github.com/eapache/channels/channels_test.go
  vendor/github.com/eapache/channels/infinite_channel.go
  vendor/github.com/eapache/channels/infinite_channel_test.go
  vendor/github.com/eapache/channels/native_channel.go
  vendor/github.com/eapache/channels/native_channel_test.go
  vendor/github.com/eapache/channels/overflowing_channel.go
  vendor/github.com/eapache/channels/overflowing_channel_test.go
  vendor/github.com/eapache/channels/resizable_channel.go
  vendor/github.com/eapache/channels/resizable_channel_test.go
  vendor/github.com/eapache/channels/ring_channel.go
  vendor/github.com/eapache/channels/ring_channel_test.go
  vendor/github.com/eapache/channels/shared_buffer.go
  vendor/github.com/eapache/channels/shared_buffer_test.go
  vendor/github.com/eapache/queue/.gitignore
  vendor/github.com/eapache/queue/.travis.yml
  vendor/github.com/eapache/queue/LICENSE
  vendor/github.com/eapache/queue/README.md
  vendor/github.com/eapache/queue/queue.go
  vendor/github.com/eapache/queue/queue_test.go
Labels: approved, cncf-cla: yes, size/XXL

#2084 Add LemonLDAP::NG kubernetes controller to catalog
  docs/catalog.md
Labels: approved, cncf-cla: yes, size/XS

#2086 Ingress custom backend
  images/custom-error-pages/main.go
  images/custom-error-pages/metrics.go
Labels: approved, cncf-cla: yes, size/M

#2092 Update Makefile to allow specifying tag from command line
  images/404-server/Makefile
Labels: approved, cncf-cla: yes, size/XS

#2091 Add HTTPS port to echoheaders
  images/echoheaders/Dockerfile
  images/echoheaders/Makefile
  images/echoheaders/README.md
  images/echoheaders/echo-app.yaml
  images/echoheaders/nginx.conf
  images/echoheaders/run.sh
Labels: approved, cncf-cla: yes, size/M

#2093 Only pods in running phase are vallid for status
  images/echoheaders/run.sh
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
Labels: approved, cncf-cla: yes, size/M

#2099 Added GeoIP Organisational data
  images/nginx/build.sh
  rootfs/etc/nginx/template/nginx.tmpl
Labels: cncf-cla: yes, size/XS

#2105 Updates and extends client cert documentation
  docs/examples/README.md
  docs/examples/auth/client-certs/README.md
  docs/examples/auth/client-certs/ingress.yaml
  docs/examples/auth/client-certs/nginx-tls-auth.yaml
  docs/user-guide/annotations.md
Labels: approved, cncf-cla: yes, size/M

#2102 Fix proxy_redirect description
  docs/user-guide/annotations.md
Labels: approved, cncf-cla: yes, size/XS

#2111 replace &#8209; with actual dashes '-'
  docs/user-guide/configmap.md
Labels: approved, cncf-cla: yes, size/L

#2112 Fix e2e tests updating nginx image
  Makefile
  images/nginx/Makefile
Labels: approved, cncf-cla: yes

#2107 Enabled the dynamic reload of GeoIP data
  images/nginx/build.sh
  internal/ingress/controller/nginx.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/M

#2089 Retry initial connection to the Kubernetes cluster
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, size/M

#2118 Fix coveralls report
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#2120 Migrate to codecov.io
  .codecov.yml
  .gitignore
  .travis.yml
  Makefile
  README.md
  images/nginx/build.sh
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, size/M

#2119 Remove deprecated flag disable-node-list
  cmd/nginx/flags.go
Labels: approved, cncf-cla: yes, size/XS

#2127 Revert deletion of dependency version override
  Gopkg.toml
Labels: approved, cncf-cla: yes, size/XS

#2122 Release nginx ingress controller 0.11.0
  Changelog.md
  Makefile
  deploy/provider/patch-service-with-rbac.yaml
  deploy/provider/patch-service-without-rbac.yaml
  deploy/with-rbac.yaml
  deploy/without-rbac.yaml
  docs/examples/customization/custom-errors/rc-custom-errors.yaml
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, size/M

#2124 Document how to provide list types in configmap
  docs/user-guide/configmap.md
Labels: approved, cncf-cla: yes, size/XS

#2133 fix limit-req-status-code doc
  docs/user-guide/configmap.md
Labels: cncf-cla: yes, size/XS

#2137 Updated log level to v2 for sysctlFSFileMax.
  internal/ingress/controller/nginx.go
  internal/ingress/controller/util.go
Labels: approved, cncf-cla: yes, size/XS

#2139 Update documentation for nginx-ingress-role RBAC.
  deploy/rbac.md
Labels: approved, cncf-cla: yes, size/XS

#2140 Cors header should always be returned
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S

#2141 Fix error loading modules
  internal/ingress/controller/template/template.go
Labels: approved, cncf-cla: yes, size/S

#2143 Only add HSTS headers in HTTPS
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S

#2144 Add annotation to disable logs in a location
  docs/user-guide/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/log/main.go
  internal/ingress/annotations/log/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/L

#2145 Add option in the configuration configmap to enable remote logging
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S

#2146 In case of TLS errors do not allow traffic
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/authtls/main.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S

#2148 Add publish-status-address flag
  cmd/nginx/flags.go
  docs/user-guide/cli-arguments.md
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
Labels: approved, cncf-cla: yes, size/M
