Repository kubernetes/ingress-nginx, pull requests merged in 2018-12, with the labels that each got.

#3470 Use opentracing_grpc_propagate_context when necessary
  Makefile
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#3492 Fix data size validations
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3501 be consistent with what Nginx supports
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#3504 fix an ewma unit test
  rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
  rootfs/etc/nginx/lua/test/run.lua
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3482 Annotations doc links: minor fixes and unification
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3510 Update mkdocs [skip ci]
  build/mkdocs/Dockerfile
  requirements-docs.txt
Labels: cncf-cla: yes, size/XS

#3513 Revert removal of TCP and UDP support configmaps in mandatroy manifest
  deploy/mandatory.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#3516 Fix error in configmap yaml definition
  deploy/configmap.yaml
  deploy/mandatory.yaml
Labels: approved, cncf-cla: yes, size/XS

#3474 Improve parsing of annotations and use of Ingress wrapper
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/authreq/main_test.go
  internal/ingress/annotations/authtls/main.go
  internal/ingress/annotations/connection/main_test.go
  internal/ingress/annotations/cors/main.go
  internal/ingress/annotations/influxdb/main.go
  internal/ingress/annotations/log/main.go
  internal/ingress/annotations/luarestywaf/main.go
  internal/ingress/annotations/modsecurity/main.go
  internal/ingress/annotations/modsecurity/main_test.go
  internal/ingress/annotations/parser/main.go
  internal/ingress/annotations/parser/main_test.go
  internal/ingress/annotations/proxy/main.go
  internal/ingress/annotations/rewrite/main.go
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/controller/store/ingress_annotation.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3512 Allow to disable NGINX metrics
  cmd/nginx/flags.go
  cmd/nginx/main.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/metric/dummy.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#3509 [1759] Ingress affinity session cookie with Secure flag for HTTPS
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#3518 Fix log output format
  internal/ingress/controller/tcp.go
  internal/net/ssl/ssl.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3508 Update nginx to 1.15.7
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm

#3521 Fix a bug with Canary becoming main server
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  test/e2e/annotations/canary.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3530 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#3536 Replace dockerfile entrypoint
  rootfs/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3525 make canary ingresses independent of the order they were applied
  internal/ingress/controller/controller.go
  test/e2e/annotations/canary.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3503 compare error with error types from k8s.io/apimachinery/pkg/api/errors
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3553 handle_error_when_executing_diff
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3551 Fix --enable-dynamic-certificates for nested subdomain
  rootfs/etc/nginx/lua/certificate.lua
  rootfs/etc/nginx/lua/test/certificate_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/S

#3562 Rename nginx.yaml to nginx.json
  deploy/grafana/dashboards/nginx.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3505 Update lua configuration_data when number of controller pod change
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/lua/configuration.lua
  test/e2e/framework/exec.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3566 Add Unit Tests for getIngressInformation
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3573 Update Certificate Generation Docs to not use MD5
  docs/examples/PREREQUISITES.md
  docs/examples/auth/client-certs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3577 Add standard labels to namespace specs
  deploy/mandatory.yaml
  deploy/namespace.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3587 adjust dind istallation
  test/e2e/up.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3575 Add documentation for spec.rules.host format
  docs/user-guide/ingress-path-matching.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3581 lua randomseed per worker
  .luacheckrc
  build/static-check.sh
  rootfs/etc/nginx/lua/lua_ingress.lua
  rootfs/etc/nginx/lua/test/lua_ingress_test.lua
  rootfs/etc/nginx/lua/test/run.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#3548 e2e test to ensure graceful shutdown does not lose requests
  test/e2e/e2e.go
  test/e2e/framework/deployment.go
  test/e2e/framework/framework.go
  test/e2e/gracefulshutdown/slow_requests.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3594 Add a flag to make per-host metrics optional
  cmd/nginx/flags.go
  cmd/nginx/main.go
  internal/ingress/controller/controller.go
  internal/ingress/metric/collectors/socket.go
  internal/ingress/metric/collectors/socket_test.go
  internal/ingress/metric/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3240 Adds support for HTTP2 Push Preload annotation
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/http2pushpreload/main.go
  internal/ingress/annotations/http2pushpreload/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/http2pushpreload.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3601 Update nginx to 1.15.8
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/S

#3605 Fix CLA URLs
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
