Repository kubernetes/ingress-nginx, pull requests merged in 2018-03, with the labels that each got.

#2162 Remove duplicated BuildConfigFromFlags func
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, size/S

#2155 Update nginx with new modules
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/M

#2165 Typo fix "api server " -> "API server"
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, size/XS

#2164 use the correct error channel
  internal/ingress/controller/nginx.go
Labels: cncf-cla: yes, size/XS

#2163 include lua-upstream-nginx-module in Nginx build
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/S

#2169 Add documentation about secure-verify-ca-secret
  docs/user-guide/annotations.md
Labels: approved, cncf-cla: yes, size/XS

#2180 Include tests in golint checks, fix warnings
  Makefile
  hack/verify-golint.sh
  test/e2e/framework/cleanup.go
  test/e2e/framework/framework.go
  test/e2e/framework/k8s.go
  test/e2e/framework/logs.go
  test/e2e/framework/ssl.go
  test/e2e/framework/test_context.go
  test/e2e/framework/util.go
Labels: approved, cncf-cla: yes, size/M

#2185 Remove ProxyPassParams setting
  internal/ingress/annotations/proxy/main.go
  internal/ingress/annotations/proxy/main_test.go
  internal/ingress/defaults/main.go
Labels: approved, cncf-cla: yes, size/S

#2181 change nginx process pgid
  internal/ingress/controller/nginx.go
Labels: cncf-cla: yes, size/XS

#2172 include lua-resty-lock in nginx image
  images/nginx/Makefile
  images/nginx/build.sh
Labels: cncf-cla: yes, size/S

#2191 Add checker test for bad pid
  internal/ingress/controller/checker_test.go
Labels: approved, cncf-cla: yes, size/S

#2167 configuring load balancing per ingress
  docs/user-guide/annotations.md
  internal/file/bindata.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/loadbalancing/main.go
  internal/ingress/annotations/loadbalancing/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/template.go
  internal/ingress/defaults/main.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/L

#2193 fix wrong json tag
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/ipwhitelist/main.go
  internal/ingress/types.go
Labels: approved, cncf-cla: yes, size/S

#2200 fix grammer mistake
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, size/XS

#2201 Add worker-cpu-affinity nginx option
  Makefile
  docs/user-guide/configmap.md
  internal/file/bindata.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/configmap.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/M

#2174 Live Nginx configuration update without reloading
  Makefile
  cmd/nginx/flags.go
  internal/file/bindata.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/configuration.lua
  rootfs/etc/nginx/lua/util.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/XL

#2202 Allow config to disable geoip
  docs/user-guide/configmap.md
  internal/file/bindata.go
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S

#2205 add luacheck to lint lua files
  .luacheckrc
  .travis.yml
  Makefile
  rootfs/etc/nginx/lua/balancer.lua
Labels: approved, cncf-cla: yes, size/S

#2203 Add configoption to exclude routes from tls upgrading
  docs/user-guide/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/M

#2209 fix go test TestSkipEnqueue error, move queue.Run
  internal/task/queue_test.go
Labels: approved, cncf-cla: yes, size/XS

#2206 Release nginx ingress controller 0.12.0
  Changelog.md
  Makefile
  deploy/provider/patch-service-with-rbac.yaml
  deploy/provider/patch-service-without-rbac.yaml
  deploy/with-rbac.yaml
  deploy/without-rbac.yaml
  docs/examples/customization/custom-errors/rc-custom-errors.yaml
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, size/M

#2208 Add missing lua bindata change
  .travis.yml
  Makefile
  hack/verify-bindata.sh
  internal/file/bindata.go
Labels: approved, cncf-cla: yes, size/M

#2078 Expose SSL client cert data to external auth provider.
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S

#2213 Update cli-arguments.md
  docs/user-guide/cli-arguments.md
Labels: approved, cncf-cla: yes, size/XS

#2210 allow ipv6 localhost when enabled
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/XS

#2215 fix wrong config generation when upstream-hash-by is set
  internal/ingress/controller/template/template.go
Labels: approved, cncf-cla: yes, size/XS

#2219 Fix log format documentation
  docs/user-guide/log-format.md
Labels: cncf-cla: yes, size/XS

#2221 Update nginx to 1.13.10 and enable gRPC
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/S

#2227 do not hardcode keepalive for upstream_balancer
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/XS

#2228 Fix broken links in multi-tls
  docs/examples/multi-tls/multi-tls.yaml
Labels: cncf-cla: yes, size/XS

#2233 clean backends data before sending to Lua endpoint
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, size/S

#2235 add proxy header ssl-client-issuer-dn, fix #2178
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/XS

#2232 Make proxy_next_upstream_tries configurable
  docs/user-guide/annotations.md
  docs/user-guide/configmap.md
  internal/file/bindata.go
  internal/ingress/annotations/proxy/main.go
  internal/ingress/annotations/proxy/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/defaults/main.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/M

#2238 Correct typo
  internal/ingress/controller/nginx.go
  internal/ingress/types.go
Labels: cncf-cla: yes, size/XS

#2239 fix-link
  docs/examples/customization/custom-configuration/README.md
Labels: approved, cncf-cla: yes, size/XS

#2236 Add missing configuration in #2235
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/XS

#2240 fix:"any value other" should be "any other value"
  README.md
Labels: approved, cncf-cla: yes, size/XS

#2220 fix: cannot set $service_name if use rewrite
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/XS

#2241 Revert "Get file max from fs/file-max. (#2050)"
  internal/ingress/controller/util.go
Labels: approved, cncf-cla: yes, size/S

#2242 add http/2
  images/echoheaders/Makefile
  images/echoheaders/README.md
  images/echoheaders/echo-app.yaml
  images/echoheaders/nginx.conf
Labels: approved, cncf-cla: yes, size/XS

#2244 fix: empty ingress path
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/S

#2246 Fix grpc json tag name
  internal/ingress/controller/config/config.go
  internal/ingress/types.go
Labels: approved, cncf-cla: yes, size/XS

#2229 Configurable load balancing with EWMA
  docs/user-guide/configmap.md
  internal/file/bindata.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/balancer/ewma.lua
  rootfs/etc/nginx/lua/util.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: cncf-cla: yes, size/L

#1785 Add deployment docs for AWS NLB
  deploy/README.md
  deploy/provider/aws/service-nlb.yaml
Labels: cncf-cla: yes, size/M

#2255 Update annotations.md
  docs/user-guide/annotations.md
Labels: approved, cncf-cla: yes, size/XS

#2267 Update README.md
  docs/examples/rewrite/README.md
Labels: cncf-cla: yes, size/XS

#2187 Managing a whitelist for _/nginx_status
  docs/user-guide/configmap.md
  internal/file/bindata.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/configmap_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/data/config.json
Labels: approved, cncf-cla: yes, size/L

#2270 Revert deleted code in #2146
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, size/XS

#2271 Use SharedIndexInformers in place of Informers
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/L

#2263 clean up tmpl
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S

#2272 Disable opentracing for nginx internal urls
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S

#2274 Typo fixes in modsecurity.md
  docs/user-guide/modsecurity.md
Labels: cncf-cla: yes, size/XS

#2273 Update go to 1.10.1
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#2276 Update README.md
  images/nginx/README.md
Labels: approved, cncf-cla: yes, size/XS

#2280 Fix bug when auth req is enabled(external authentication)
  internal/file/bindata.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S
