Repository kubernetes/ingress-nginx, pull requests merged in 2018-04, with the labels that each got.

#2254 e2e tests for dynamic configuration and Lua features and a bug fix
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  test/e2e/e2e.go
  test/e2e/framework/framework.go
  test/e2e/framework/k8s.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, size/L

#2283 Fix flaky e2e tests
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, size/S

#2243 Add NoAuthLocations and default it to "/.well-known/acme-challenge"
  docs/user-guide/configmap.md
  hack/verify-bindata.sh
  internal/file/bindata.go
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/no_auth_locations.go
Labels: approved, cncf-cla: yes, size/L

#2285 Update controller.go
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, size/XS

#2289 Fix custom-error-pages image publication script
  images/custom-error-pages/Makefile
Labels: approved, cncf-cla: yes, size/XS

#2290 Update nginx to 1.13.11
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/M

#2294 Fix HSTS without preload
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/XS

#2298 Disable dynamic configuration in s390x and ppc64le
  cmd/nginx/flags.go
Labels: approved, cncf-cla: yes, size/XS

#2300 Fix race condition when Ingress does not contains a secret
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/XS

#2301 include lua-resty-waf and its dependencies in the base Nginx image
  images/nginx/Dockerfile
  images/nginx/Makefile
  images/nginx/build.sh
  images/nginx/install_lua_resty_waf.sh
Labels: cncf-cla: yes, size/M

#2303 More lua dependencies
  images/nginx/build.sh
  images/nginx/install_lua_resty_waf.sh
Labels: approved, cncf-cla: yes, size/M

#2305 Fix issues building nginx image in different platforms
  images/nginx/install_lua_resty_waf.sh
Labels: approved, cncf-cla: yes, size/S

#2306 Disable lua waf where luajit is not available
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/M

#2308 Add verification of lua load balancer to health check
  internal/file/bindata.go
  internal/ingress/controller/checker.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/M

#2309 Configure upload limits for setup of lua load balancer
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/XS

#2304 Lua resty waf controller
  Makefile
  docs/user-guide/annotations.md
  internal/file/bindata.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/luarestywaf/main.go
  internal/ingress/annotations/luarestywaf/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/luarestywaf.go
Labels: approved, cncf-cla: yes, size/L

#2314 annotation to ignore given list of WAF rulesets
  docs/user-guide/annotations.md
  internal/file/bindata.go
  internal/ingress/annotations/luarestywaf/main.go
  internal/ingress/annotations/luarestywaf/main_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/luarestywaf.go
Labels: approved, cncf-cla: yes, size/M

#2315 extra waf rules per ingress
  docs/user-guide/annotations.md
  internal/file/bindata.go
  internal/ingress/annotations/luarestywaf/main.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/luarestywaf.go
Labels: approved, cncf-cla: yes, size/M

#2319 Add ingress-nginx survey
  README.md
Labels: cncf-cla: yes

#2321 Fix survey link
  README.md
Labels: cncf-cla: yes

#2327 Update nginx to 1.13.12
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/XS

#2328 Update nginx image
  Makefile
  test/e2e/up.sh
Labels: approved, cncf-cla: yes, size/XS

#2331 fix nil pointer when ssl with ca.crt
  internal/net/ssl/ssl.go
Labels: cncf-cla: yes, size/XS

#2333 disable lua for arch s390x and ppc64le
  cmd/nginx/flags.go
  internal/file/bindata.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#2340 Fix buildupstream name to work with dynamic session affinity
  internal/file/bindata.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#2342 Sync SSL certificates on events
  internal/ingress/controller/controller.go
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/controller/store/objectref.go
  internal/ingress/controller/store/objectref_test.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/sslcert.go
  internal/ingress/sslcert_test.go
  internal/task/queue.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2344 Escape variables in add-base-url annotation
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2347 Update owners
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#2348 Use same convention, curl + kubectl for GKE
  deploy/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2352 Correct some info in flags.go
  cmd/nginx/flags.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2351 Typo fix in cli-arguments.md
  docs/user-guide/cli-arguments.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2350 Correct some returned messages in server_tokens.go
  test/e2e/settings/server_tokens.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2353 Add proxy-add-original-uri-header config flag
  docs/user-guide/configmap.md
  internal/file/bindata.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/configmap_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#2345 Release nginx ingress controller 0.13.0
  Changelog.md
  Makefile
  deploy/provider/patch-service-with-rbac.yaml
  deploy/provider/patch-service-without-rbac.yaml
  deploy/with-rbac.yaml
  deploy/without-rbac.yaml
  docs/examples/customization/custom-errors/rc-custom-errors.yaml
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2366 fix: fill missing patch yaml config.
  deploy/provider/patch-service-with-rbac.yaml
  deploy/provider/patch-service-without-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2363 Review $request_id
  docs/examples/customization/configuration-snippets/ingress.yaml
  docs/user-guide/annotations.md
  docs/user-guide/configmap.md
  internal/file/bindata.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#2356 Add vts-sum-key config flag
  docs/user-guide/configmap.md
  internal/file/bindata.go
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#2346 Move ConfigMap updating methods into e2e/framework
  test/e2e/framework/framework.go
  test/e2e/lua/dynamic_configuration.go
  test/e2e/settings/no_auth_locations.go
  test/e2e/settings/proxy_protocol.go
  test/e2e/settings/server_tokens.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2372 fix the default cookie name in doc
  docs/examples/affinity/cookie/README.md
  docs/user-guide/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2377 DOCS: Add clarification regarding ssl passthrough
  docs/user-guide/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2369 Update nginx image to fix modsecurity crs issues
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2382 Accept ns/name Secret reference in annotations
  docs/user-guide/annotations.md
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2374 Remove most of the time.Sleep from the e2e tests
  .travis.yml
  Gopkg.lock
  Makefile
  internal/ingress/controller/store/store_test.go
  test/e2e/annotations/affinity.go
  test/e2e/annotations/alias.go
  test/e2e/annotations/auth.go
  test/e2e/annotations/luarestywaf.go
  test/e2e/defaultbackend/default_backend.go
  test/e2e/defaultbackend/ssl.go
  test/e2e/framework/echo.go
  test/e2e/framework/exec.go
  test/e2e/framework/framework.go
  test/e2e/framework/k8s.go
  test/e2e/framework/test_context.go
  test/e2e/framework/util.go
  test/e2e/lua/dynamic_configuration.go
  test/e2e/settings/no_auth_locations.go
  test/e2e/settings/proxy_protocol.go
  test/e2e/settings/server_tokens.go
  test/e2e/ssl/secret_update.go
  test/e2e/up.sh
  test/e2e/wait-for-nginx.sh
  test/manifests/ingress-controller/configmap.yaml
  test/manifests/ingress-controller/default-backend.yaml
  test/manifests/ingress-controller/rbac.yaml
  test/manifests/ingress-controller/service-nodeport.yaml
  test/manifests/ingress-controller/tcp-services-configmap.yaml
  test/manifests/ingress-controller/udp-services-configmap.yaml
  test/manifests/ingress-controller/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2383 Improve speed of e2e tests
  .gitignore
  .travis.yml
  Makefile
  test/e2e/framework/exec.go
  test/e2e/framework/framework.go
  test/e2e/lua/dynamic_configuration.go
  test/manifests/ingress-controller/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2385 include lua-resty-balancer in nginx image
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2388 Silence unnecessary MissingAnnotations errors
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2361 Check ingress rule contains HTTP paths
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2392 Ensure dep fix fsnotify
  Gopkg.lock
  Gopkg.toml
  Makefile
  internal/watch/file_watcher.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/.editorconfig
  vendor/gopkg.in/fsnotify/fsnotify.v1/.gitignore
  vendor/gopkg.in/fsnotify/fsnotify.v1/.travis.yml
  vendor/gopkg.in/fsnotify/fsnotify.v1/AUTHORS
  vendor/gopkg.in/fsnotify/fsnotify.v1/CHANGELOG.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/CONTRIBUTING.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/LICENSE
  vendor/gopkg.in/fsnotify/fsnotify.v1/README.md
  vendor/gopkg.in/fsnotify/fsnotify.v1/example_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/fen.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/fsnotify.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/fsnotify_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify_poller.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify_poller_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/inotify_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/integration_darwin_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/integration_test.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/kqueue.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/open_mode_bsd.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/open_mode_darwin.go
  vendor/gopkg.in/fsnotify/fsnotify.v1/windows.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2370 Update nginx image
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2398 Allow tls section without hosts in Ingress rule
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2399 Add test for store helper ListIngresses
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2401 Add tests for controller getEndpoints
  internal/ingress/controller/controller.go
  internal/ingress/controller/endpoints.go
  internal/ingress/controller/endpoints_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2379 Add busted unit testing framework for lua code
  .luacheckrc
  .travis.yml
  Makefile
  docs/development.md
  hack/verify-golint.sh
  internal/file/bindata.go
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/up.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2414 Fix golint installation
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2411 Update nginx-opentracing to 0.3.0
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2417 Automate building developer environment
  Makefile
  docs/development.md
  hack/build-dev-env.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2408 Read backends data even if buffered to temp file
  internal/file/bindata.go
  rootfs/etc/nginx/lua/configuration.lua
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2409 Add deployment instructions for Docker for Mac (Edge)
  deploy/README.md
  deploy/provider/docker-for-mac/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2421 Apply gometalinter suggestions
  internal/file/filesystem.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/luarestywaf/main.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/controller/util_test.go
  test/e2e/framework/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2365 Clean JSON before post request to update configuration
  internal/ingress/controller/controller.go
  internal/ingress/controller/endpoints.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/resolver/main.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2431 Improve readme file
  README.md
  docs/extra.css
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2433 Remove data races from tests
  internal/ingress/controller/nginx_test.go
  internal/ingress/controller/store/store_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2432 Fix broken links in the docs
  README.md
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/nginx-configuration/index.md
  docs/user-guide/tls.md
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2436 Update exposing-tcp-udp-services.md
  docs/user-guide/exposing-tcp-udp-services.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2386 upstream-hash-by annotation support for dynamic configuraton mode
  .luacheckrc
  internal/file/bindata.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/balancer/chash.lua
  rootfs/etc/nginx/lua/test/balancer/chash_test.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/util.lua
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2442 Release nginx ingress controller 0.14.0
  Changelog.md
  Makefile
  deploy/provider/patch-service-with-rbac.yaml
  deploy/provider/patch-service-without-rbac.yaml
  deploy/with-rbac.yaml
  deploy/without-rbac.yaml
  docs/examples/customization/custom-errors/rc-custom-errors.yaml
  docs/examples/static-ip/nginx-ingress-controller.yaml
  test/manifests/ingress-controller/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2440 TLS tests
  Makefile
  internal/ingress/controller/store/store_test.go
  test/e2e/framework/echo.go
  test/e2e/framework/ssl.go
  test/e2e/lua/dynamic_configuration.go
  test/e2e/settings/no_auth_locations.go
  test/e2e/settings/proxy_protocol.go
  test/e2e/settings/server_tokens.go
  test/e2e/settings/tls.go
  test/e2e/ssl/secret_update.go
  test/manifests/ingress-controller/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#2443 improve build-dev-env.sh script
  hack/build-dev-env.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2448 Update GitHub pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2446 always use x-request-id
  internal/file/bindata.go
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2449 Improve documentation format
  docs/deploy/index.md
  docs/development.md
  docs/examples/PREREQUISITES.md
  docs/examples/docker-registry/README.md
  docs/examples/external-auth/README.md
  docs/examples/static-ip/README.md
  docs/extra.css
  docs/troubleshooting.md
  docs/user-guide/custom-errors.md
  docs/user-guide/miscellaneous.md
  docs/user-guide/multiple-ingress.md
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/third-party-addons/modsecurity.md
  docs/user-guide/third-party-addons/opentracing.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2453 Add google analytics [ci skip]
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2455 Adjust size of tables and only adjust the first column on mobile
  docs/extra.css
Labels: approved, cncf-cla: yes, lgtm, size/S
