Repository kubernetes/ingress-nginx, pull requests merged in 2018-07, with the labels that each got.

#2727 Add e2e tests for Client-Body-Buffer-Size
  test/e2e/annotations/clientbodybuffersize.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2732 Improve logging
  internal/ingress/controller/controller.go
  internal/ingress/controller/endpoints.go
  internal/ingress/controller/endpoints_test.go
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/controller/store/configmap.go
  internal/ingress/controller/store/endpoint.go
  internal/ingress/controller/store/ingress.go
  internal/ingress/controller/store/ingress_annotation.go
  internal/ingress/controller/store/secret.go
  internal/ingress/controller/store/service.go
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2743 Clarify Installation Document by Separating Helm Steps
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2741 Add redirect uri for oauth2 login
  docs/examples/auth/oauth-external-auth/README.md
  docs/examples/auth/oauth-external-auth/dashboard-ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2744 fix: Use the correct opentracing plugin for Jaeger
  images/nginx/Makefile
  images/nginx/build.sh
  internal/ingress/controller/template/template.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2747 Update opentracing-cpp and modsecurity
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/S

#2748 Update nginx image to 0.54
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#2764 Use language neutral links to MDN
  docs/user-guide/nginx-configuration/configmap.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2765 Add FOSSA status badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2761 Fix spelling mistake
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2760 Fix ingress rule parsing error
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2767 Fix regression introduced in #2732
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2726 Cleanup prometheus metrics after a reload
  Makefile
  build/e2e-tests.sh
  build/go-in-docker.sh
  cmd/nginx/main.go
  cmd/nginx/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/metrics.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/metric/collector/collector.go
  internal/ingress/metric/collector/collector_test.go
  internal/ingress/metric/collectors/controller.go
  internal/ingress/metric/collectors/controller_test.go
  internal/ingress/metric/collectors/main.go
  internal/ingress/metric/collectors/nginx_status.go
  internal/ingress/metric/collectors/nginx_status_test.go
  internal/ingress/metric/collectors/process.go
  internal/ingress/metric/collectors/process_test.go
  internal/ingress/metric/collectors/socket.go
  internal/ingress/metric/collectors/socket_test.go
  internal/ingress/metric/collectors/testutils.go
  internal/ingress/metric/dummy.go
  internal/ingress/metric/main.go
  internal/ingress/sslcert.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  internal/net/ssl/ssl.go
  rootfs/etc/nginx/lua/monitor.lua
  rootfs/etc/nginx/lua/test/monitor_test.lua
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2776 Fix configuration hash calculation
  internal/ingress/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2777 Build docs using local docker image [ci skip]
  Makefile
  build/mkdocs/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#2778 Update docs and mkdoc dependencies [ci skip]
  docs/ingress-controller-catalog.md
  docs/user-guide/nginx-status-page.md
  requirements-docs.txt
Labels: approved, size/S

#2771 Grafana Dashboard
  deploy/grafana/dashboards/README.md
  deploy/grafana/dashboards/nginx.yaml
  deploy/grafana/dashboards/screenshot.png
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2779 Update grafana dashboard lebels
  deploy/grafana/dashboards/nginx.yaml
Labels: approved, cncf-cla: yes

#2780 Release 0.17.0
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
  docs/deploy/upgrade.md
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2782 Add Better Error Handling for SSLSessionTicketKey
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#2723 Docs: examples: fix link
  docs/examples/customization/configuration-snippets/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2770 Basic-Auth doc misleading: fix double quotes leading to nginx config error
  docs/examples/auth/basic/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2790 Update prometheus labels
  deploy/grafana/dashboards/nginx.yaml
  internal/ingress/metric/collectors/socket.go
  internal/ingress/metric/collectors/socket_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2795 start minikube before trying to build the image
  build/dev-env.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2792 Release 0.17.1
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
  docs/deploy/upgrade.md
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2789 Remove KubeConfig Dependency for Store Tests
  .travis.yml
  cmd/nginx/main.go
  cmd/nginx/main_test.go
  internal/ingress/controller/store/store_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2752 use format "range v := iterative object" and "range k, v := iterative object" when the type of iterative object is slice and map in the file nginx.tmpl
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#2762 Update index.md
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2812 modified annotation name "rewrite-to" to "rewrite-target" in comments
  internal/ingress/controller/template/template.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2816 doc log-format: add variables about ingress
  docs/user-guide/nginx-configuration/log-format.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2819 Catch errors waiting for controller deployment
  test/e2e/framework/exec.go
  test/e2e/wait-for-nginx.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2823 Multiple optimizations to build targets
  .gitignore
  Makefile
  build/e2e-tests.sh
  build/go-in-docker.sh
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2827 Use nginx image as base and install go on top
  build/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#2826 Remove setcap from image and update nginx to 0.15.1
  images/nginx/Makefile
  images/nginx/README.md
  images/nginx/build.sh
  images/nginx/install_lua_resty_waf.sh
  images/nginx/rc.yaml
Labels: approved, cncf-cla: yes, size/L

#2829 use resty-cli for running lua unit tests
  build/Dockerfile
  build/busted
  build/test-lua.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2830 Remove lua mocks
  build/busted
  build/test-lua.sh
  rootfs/etc/nginx/lua/test/balancer/chash_test.lua
  rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/defer_test.lua
  rootfs/etc/nginx/lua/test/mocks/ngx/balancer.lua
  rootfs/etc/nginx/lua/test/mocks/resty/chash.lua
  rootfs/etc/nginx/lua/test/mocks/resty/cookie.lua
  rootfs/etc/nginx/lua/test/mocks/resty/lock.lua
  rootfs/etc/nginx/lua/test/mocks/resty/md5.lua
  rootfs/etc/nginx/lua/test/mocks/resty/roundrobin.lua
  rootfs/etc/nginx/lua/test/mocks/resty/sha1.lua
  rootfs/etc/nginx/lua/test/mocks/resty/string.lua
  rootfs/etc/nginx/lua/test/monitor_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#2825 Refactoring of how we run as user
  Makefile
  rootfs/Dockerfile
  rootfs/entrypoint.sh
  test/manifests/ingress-controller/mandatory.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2852 fix custom-error-pages functionality in dynamic mode
  internal/ingress/controller/nginx_test.go
  rootfs/etc/nginx/lua/util/dns.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#2853 improve annotations/default_backend e2e test
  test/e2e/annotations/default_backend.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2794 enable dynamic backend configuration by default
  cmd/nginx/flags.go
  docs/user-guide/cli-arguments.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/configmap_test.go
  internal/ingress/controller/template/template.go
  test/e2e/annotations/affinity.go
  test/e2e/framework/framework.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2858 Update build image
  build/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2859 Fix inconsistent metric labels
  internal/ingress/metric/collectors/controller.go
  internal/ingress/metric/collectors/controller_test.go
Labels: approved, cncf-cla: yes, lgtm

#2866 Update index.md
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2863 Replace minikube for e2e tests
  .travis.yml
  Makefile
  build/build.sh
  build/e2e-tests.sh
  build/go-in-docker.sh
  hack/boilerplate/boilerplate.py
  test/e2e/dind-cluster-v1.11.sh
  test/e2e/down.sh
  test/e2e/up.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2867 fix bug with lua e2e test suite
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2868 Use an existing e2e image
  build/go-in-docker.sh
  images/e2e/Dockerfile
  images/e2e/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#2834 Added permanent-redirect-code
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/redirect/redirect.go
  internal/ingress/annotations/redirect/redirect_test.go
  test/e2e/annotations/redirect.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2876 Remove dashboard an tune sync-frequency
  test/e2e/dind-cluster-v1.11.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2877 Refactor entrypoint to avoid issues with volumes
  rootfs/Dockerfile
  rootfs/entrypoint.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#2872 Update nginx to 1.15.2
  images/nginx/Makefile
  images/nginx/README.md
  images/nginx/build.sh
  images/nginx/rc.yaml
Labels: approved, cncf-cla: yes, size/M
