Repository kubernetes/ingress-nginx, pull requests merged in 2018-06, with the labels that each got.

#2592 Typo fix: are be->are/to on->to
  docs/examples/auth/client-certs/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2595 Typo fix: successfull->successful
  internal/ingress/controller/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2598 Always sort upstream list to provide stable iteration order
  cmd/nginx/flags.go
  internal/ingress/controller/controller.go
  internal/ingress/types_equals.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2504 Add Timeout For TLS Passthrough
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/configmap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2600 typo fix futher to further && preformance to performance
  Changelog.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2601 fix changelog link in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2479 Document how the NGINX Ingress controller build nginx.conf
  docs/how-it-works.md
Labels: approved, cncf-cla: yes, size/M

#2602 Crossplat fixes
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2597 Fix arm paths for liblua.so and lua_package_cpath
  Makefile
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2603 Bump nginx influxdb module to f8732268d44aea706ecf8d9c6036e9b6dacc99b2
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2559 Add geoip2 module and DB to nginx build
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2486 Extend kubernetes interrelation variables in nginx.tmpl
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#2617 Update go to 1.10.3
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2623 Proofread cmd package and update flags description
  cmd/nginx/flag_test.go
  cmd/nginx/flags.go
  cmd/nginx/main.go
  cmd/nginx/main_test.go
  docs/user-guide/cli-arguments.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2624 Fix minor documentation example
  docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2625 Add annotation doc on proxy buffer size
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2619 Run as user dropping privileges
  internal/file/filesystem.go
  internal/ingress/annotations/auth/main.go
  internal/ingress/controller/checker.go
  internal/ingress/controller/checker_test.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/store/store.go
  internal/net/dns/dns_test.go
  internal/watch/file_watcher_test.go
  rootfs/Dockerfile
  rootfs/etc/nginx/nginx.conf
  rootfs/etc/nginx/template/nginx.tmpl
  test/manifests/ingress-controller/mandatory.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#2630 Update documentation for custom error pages
  docs/examples/customization/custom-errors/README.md
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/examples/customization/custom-errors/rc-custom-errors.yaml
  docs/examples/index.md
  docs/user-guide/custom-errors.md
  images/custom-error-pages/Makefile
  images/custom-error-pages/README.md
  images/custom-error-pages/main.go
  images/custom-error-pages/rootfs/etc/mime.types
Labels: cncf-cla: yes, size/XXL

#2636 Add missing equality comparisons for ingress.Server
  internal/ingress/types_equals.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2634 Disable resync period
  .travis.yml
  cmd/nginx/flags.go
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2639 Clarify log messages in controller package
  internal/ingress/controller/controller.go
  internal/ingress/controller/endpoints.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/tcp.go
  internal/ingress/controller/util.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2638 Wait the result of the controller deployment before running any test
  test/e2e/wait-for-nginx.sh
Labels: approved, cncf-cla: yes, size/XS

#2611 Add metric emitter lua module
  rootfs/etc/nginx/lua/defer.lua
  rootfs/etc/nginx/lua/monitor.lua
  rootfs/etc/nginx/lua/test/defer/defer_test.lua
  rootfs/etc/nginx/lua/test/monitor/monitor_test.lua
  rootfs/etc/nginx/lua/util.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/L

#2608 Expose UDP message on /metrics endpoint
  cmd/nginx/main.go
  internal/ingress/controller/metric/collector/scrape.go
  internal/ingress/controller/metric/collector/status.go
  internal/ingress/controller/metric/collector/status_test.go
  internal/ingress/controller/metric/collector/vts.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/stat_collector.go
  internal/ingress/controller/util.go
  internal/ingress/metric/collector/listener.go
  internal/ingress/metric/collector/listener_test.go
  internal/ingress/metric/collector/nginx_status_collector.go
  internal/ingress/metric/collector/process_collector.go
  internal/ingress/metric/collector/udp_collector.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2618 Update nginx to 1.15.0 and remove VTS module
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/XS

#2646 Rollback nginx 1.15.0 to 1.13.12
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/XS

#2644 Update nginx image version
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2614 fix nginx conf test error when not found active service endpoints
  internal/ingress/controller/controller.go
  test/e2e/e2e.go
  test/e2e/servicebackend/service_backend.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2451 fix for #1930, make sessions sticky, for ingress with multiple rules …
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/affinity.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2643 Remove VTS from the ingress controller
  docs/examples/customization/custom-upstream-check/README.md
  docs/examples/customization/custom-upstream-check/custom-upstream.png
  docs/examples/customization/custom-vts-metrics-prometheus/README.md
  docs/examples/customization/custom-vts-metrics-prometheus/imgs/prometheus-filter-key-path.png
  docs/examples/customization/custom-vts-metrics-prometheus/imgs/vts-dashboard-filter-key-path.png
  docs/examples/customization/custom-vts-metrics-prometheus/imgs/vts-dashboard.png
  docs/examples/customization/custom-vts-metrics-prometheus/nginx-vts-metrics-conf.yaml
  docs/examples/index.md
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/nginx-status-page.md
  images/nginx/README.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/vtsfilterkey/main.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/data/config.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#2651 Update nginx to 0.15.0
  images/nginx/Makefile
  images/nginx/build.sh
Labels: cncf-cla: yes

#2654 Hotfix: influxdb module enable disable toggle
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2655 Rollback nginx to 1.13.12
  images/nginx/Makefile
  images/nginx/build.sh
Labels: cncf-cla: yes

#2652 Use a unix socket instead udp for reception of metrics
  cmd/nginx/main.go
  internal/ingress/metric/collector/collector.go
  internal/ingress/metric/collector/collector_test.go
  internal/ingress/metric/collector/listener.go
  rootfs/etc/nginx/lua/monitor.lua
Labels: approved, cncf-cla: yes, size/L

#2658 Do not wait informer initialization to read configuration
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2659 Update nginx image
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2661 Add additional header when debug is enabled
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  images/custom-error-pages/Makefile
  images/custom-error-pages/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2664 refactor some lua code
  rootfs/etc/nginx/lua/balancer/chash.lua
  rootfs/etc/nginx/lua/balancer/ewma.lua
  rootfs/etc/nginx/lua/balancer/round_robin.lua
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/monitor.lua
  rootfs/etc/nginx/lua/test/defer_test.lua
  rootfs/etc/nginx/lua/test/monitor_test.lua
  rootfs/etc/nginx/lua/util.lua
  rootfs/etc/nginx/lua/util/defer.lua
  rootfs/etc/nginx/lua/util/split.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/L

#2666 Add documentation for proxy-cookie-domain annotation (#2034)
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2669 Remove unnecessary sync when the leader change
  internal/ingress/status/status.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2660 Change modsecurity directories
  rootfs/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#2672 After a configmap change parse ingress annotations (again)
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2673 Add new approvers to the project
  OWNERS
Labels: cncf-cla: yes

#2656 Improve configuration change detection
  Gopkg.lock
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/configmap_test.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  internal/task/queue.go
  internal/task/queue_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  vendor/github.com/mitchellh/hashstructure/LICENSE
  vendor/github.com/mitchellh/hashstructure/README.md
  vendor/github.com/mitchellh/hashstructure/hashstructure.go
  vendor/github.com/mitchellh/hashstructure/include.go
Labels: approved, cncf-cla: yes, size/XL

#2675 Update opentracing nginx module
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/M

#2676 Update opentracing configuration
  Makefile
  internal/ingress/controller/nginx.go
  internal/ingress/controller/template/template.go
  rootfs/Dockerfile
  rootfs/etc/nginx/opentracing.json
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/L

#2679 Release 0.16.0
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
  docs/deploy/upgrade.md
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, size/L

#2685 Fix qemu docker build
  .travis.yml
Labels: cncf-cla: yes

#2678 Refactor server type to include SSLCert
  internal/ingress/controller/controller.go
  internal/ingress/controller/metrics.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#2681 Typo fix in error message: encounted->encountered
  internal/ingress/controller/template/configmap.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2691 Update manifest to run as user
  Changelog.md
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
Labels: approved, cncf-cla: yes, size/M

#2692 Fix initial read of configuration configmap
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/XS

#2693 Revert #2669 [ci skip]
  internal/ingress/status/status.go
Labels: approved, cncf-cla: yes, size/XS

#2694 Add note about status update
  internal/ingress/status/status.go
Labels: cncf-cla: yes

#2695 Release 0.16.1
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
  docs/deploy/upgrade.md
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, size/M

#2696 If server_tokens is disabled completely remove the Server header
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/server_tokens.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2697 Enhance Distributed Tracing Documentation
  docs/examples/customization/configuration-snippets/ingress.yaml
  docs/images/jaeger-demo.png
  docs/user-guide/third-party-addons/opentracing.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2698 Improve best-cert guessing with empty tls.hosts
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
Labels: approved, cncf-cla: yes, size/M

#2701 Remove prometheus labels with high cardinality
  internal/ingress/metric/collector/collector.go
  rootfs/etc/nginx/lua/monitor.lua
  rootfs/etc/nginx/lua/test/monitor_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#2703 Release 0.16.2
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
  docs/deploy/upgrade.md
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, size/M

#2705 Remove duplicated securityContext
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, size/XS

#2717 GCE/GKE proxy mentioned for Azure
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2719 Sample rate configmap option for zipkin in nginx-opentracing
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/third-party-addons/opentracing.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/S
