Repository kubernetes/ingress-nginx, pull requests merged in 2018-05, with the labels that each got.

#2456 Assert or install go-bindata before incanting
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2457 Add Getting the Code section to Quick Start
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2454 Add gRPC annotation doc
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2464 Documentation fixes & improvements
  docs/deploy/upgrade.md
  docs/examples/README.md
  docs/examples/auth/oauth-external-auth/README.md
  docs/examples/auth/oauth-external-auth/dashboard-ingress.yaml
  docs/examples/auth/oauth-external-auth/images/dashboard.png
  docs/examples/auth/oauth-external-auth/images/github-auth.png
  docs/examples/auth/oauth-external-auth/images/oauth-login.png
  docs/examples/auth/oauth-external-auth/images/register-oauth-app-2.png
  docs/examples/auth/oauth-external-auth/images/register-oauth-app.png
  docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
  docs/examples/customization/custom-vts-metrics-prometheus/README.md
  docs/examples/customization/ssl-dh-param/README.md
  docs/examples/index.md
  docs/user-guide/default-backend.md
  docs/user-guide/miscellaneous.md
  docs/user-guide/multiple-ingress.md
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/log-format.md
  docs/user-guide/tls.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2467 Fixed broken link in deploy README
  deploy/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2307 Documentation: grpc example
  Makefile
  docs/examples/grpc/README.md
  docs/examples/grpc/app.yaml
  docs/examples/grpc/cert.yaml
  docs/examples/grpc/ingress.yaml
  docs/examples/grpc/svc.yaml
  images/grpc-fortune-teller/BUILD.bazel
  images/grpc-fortune-teller/Gopkg.lock
  images/grpc-fortune-teller/Gopkg.toml
  images/grpc-fortune-teller/README.md
  images/grpc-fortune-teller/WORKSPACE
  images/grpc-fortune-teller/app/BUILD.bazel
  images/grpc-fortune-teller/app/main.go
  images/grpc-fortune-teller/proto/fortune/BUILD.bazel
  images/grpc-fortune-teller/proto/fortune/doc.go
  images/grpc-fortune-teller/proto/fortune/fortune.proto
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2472 Refactor Lua balancer
  internal/file/bindata.go
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/balancer/chash.lua
  rootfs/etc/nginx/lua/balancer/resty.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/util.lua
Labels: approved, cncf-cla: yes, lgtm, size/L

#2490 add resty cookie
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2495 [ci skip] bump nginx baseimage version
  Makefile
  images/nginx/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2498 Add some clarification around multiple ingress controller behavior
  docs/user-guide/multiple-ingress.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2502 Update go version in fortune teller image
  images/grpc-fortune-teller/.gitignore
  images/grpc-fortune-teller/WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2501 Refactor update of status removing initial check for loadbalancer
  cmd/nginx/main.go
  internal/ingress/status/status.go
  internal/k8s/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2511 force backend sync when worker starts
  internal/file/bindata.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/S

#2514 Fix and simplify local dev workflow and execution of e2e tests
  .travis.yml
  Makefile
  hack/build-dev-env.sh
  test/manifests/ingress-controller/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2512 Remove warning when secret is used only for authentication
  internal/ingress/controller/store/backend_ssl.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2516 Release nginx ingress controller 0.15.0
  Changelog.md
  Makefile
  deploy/provider/patch-service-with-rbac.yaml
  deploy/provider/patch-service-without-rbac.yaml
  deploy/with-rbac.yaml
  deploy/without-rbac.yaml
  docs/deploy/upgrade.md
  docs/examples/customization/custom-errors/rc-custom-errors.yaml
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2523 Add tests for bind-address
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/template/configmap_test.go
  internal/ingress/controller/template/template_test.go
  test/data/config.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#2517 Fix typo about the kind of request
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2526 Fix upstream hash lua test
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2484 Fix bugs in Lua implementation of sticky sessions
  internal/file/bindata.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/balancer/ewma.lua
  rootfs/etc/nginx/lua/balancer/resty.lua
  rootfs/etc/nginx/lua/sticky.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/util.lua
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2531 Mention the #ingress-nginx Slack channel
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2528 Remove go-bindata
  .travis.yml
  Makefile
  hack/verify-bindata.sh
  internal/file/bindata.go
  internal/file/filesystem.go
  internal/file/structure.go
  rootfs/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2524 Add support for grpc_set_header
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/auth.go
  test/e2e/annotations/grpc.go
  test/e2e/annotations/luarestywaf.go
  test/e2e/framework/framework.go
  test/e2e/framework/grpc_fortune_teller.go
  test/e2e/lua/dynamic_configuration.go
  test/e2e/settings/proxy_protocol.go
  test/e2e/settings/server_tokens.go
  test/e2e/settings/tls.go
  test/e2e/ssl/secret_update.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2534 Set Focus for E2E Tests
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2537 Update nginx modules
  images/nginx/Makefile
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2540 DOCS: Correct ssl-passthrough annotation description.
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2542 Instrument controller to show configReload metrics
  internal/ingress/controller/controller.go
  internal/ingress/controller/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2423 Resolves issue with proxy-redirect nginx configuration
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/auth.go
  test/e2e/annotations/proxy.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2544 [docs] Fix manifest URL for GKE + Azure
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2505 Annotations for the InfluxDB module
  Makefile
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/influxdb/main.go
  internal/ingress/annotations/influxdb/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/template.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/influxdb.go
  test/e2e/framework/influxdb.go
  test/e2e/framework/k8s.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2548 Implement generate-request-id
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#2553 Update module-vts = 0.1.16 to fix duration metrics
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2558 Update qemu to 2.12.0 [ci skip]
  images/nginx/Makefile
Labels: approved, cncf-cla: yes, size/XS

#2554 use better defaults for proxy-next-upstream(-tries)
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2564 Add security contacts file [ci skip]
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, size/S

#2566 Fix wrong default value for `enable-brotli`
  docs/user-guide/nginx-configuration/configmap.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2569 Update nginx modules to fix core dump [ci skip]
  images/nginx/build.sh
Labels: approved, cncf-cla: yes, size/S

#2565 Update nginx version
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2570 Enable core dumps during tests
  test/manifests/ingress-controller/mandatory.yaml
Labels: approved, cncf-cla: yes, size/S

#2575 Print information about NGINX version
  cmd/nginx/main.go
  cmd/nginx/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2574 Fix default-backend annotation
  internal/ingress/annotations/annotations.go
  internal/ingress/controller/controller.go
  test/e2e/annotations/default_backend.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2543 introduce a balancer interface
  .luacheckrc
  .travis.yml
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/balancer/chash.lua
  rootfs/etc/nginx/lua/balancer/ewma.lua
  rootfs/etc/nginx/lua/balancer/resty.lua
  rootfs/etc/nginx/lua/balancer/round_robin.lua
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/test/balancer/chash_test.lua
  rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/mocks/ngx/balancer.lua
  rootfs/etc/nginx/lua/test/mocks/resty/chash.lua
  rootfs/etc/nginx/lua/test/mocks/resty/cookie.lua
  rootfs/etc/nginx/lua/test/mocks/resty/lock.lua
  rootfs/etc/nginx/lua/test/mocks/resty/md5.lua
  rootfs/etc/nginx/lua/test/mocks/resty/roundrobin.lua
  rootfs/etc/nginx/lua/test/mocks/resty/sha1.lua
  rootfs/etc/nginx/lua/test/mocks/resty/string.lua
  rootfs/etc/nginx/lua/test/up.sh
  rootfs/etc/nginx/lua/util.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2581 Improved link in modsecurity.md
  docs/user-guide/third-party-addons/modsecurity.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2583 docs: add secret scheme details to the example
  docs/examples/auth/basic/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2590 Typo fix: muthual autentication -> mutual authentication
  internal/ingress/annotations/authtls/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2588 Update nginx dependencies
  images/nginx/Makefile
  images/nginx/build.sh
  images/nginx/install_lua_resty_waf.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#2591 Access log improvements
  internal/ingress/controller/controller.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
