Repository kubernetes/ingress-nginx, pull requests merged in 2019-02, with the labels that each got.

#3673 used table functions of LuaJIT for better performance.
  rootfs/etc/nginx/lua/monitor.lua
Labels: approved, cncf-cla: yes, lgtm, size/S

#3619 add header-value annotation
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/canary/main.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/lua/balancer.lua
  test/e2e/annotations/canary.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3628 Fix 503 error generation on empty endpoints
  rootfs/etc/nginx/lua/balancer.lua
  test/e2e/framework/deployment.go
  test/e2e/framework/k8s.go
  test/e2e/lua/dynamic_certificates.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3731 Update a doc example that uses rewrite-target
  docs/user-guide/ingress-path-matching.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3684 Replace Status port using a socket
  Gopkg.lock
  cmd/nginx/flags.go
  cmd/nginx/main.go
  docs/user-guide/cli-arguments.md
  internal/ingress/controller/checker.go
  internal/ingress/controller/checker_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/metric/collectors/nginx_status.go
  internal/ingress/metric/collectors/nginx_status_test.go
  internal/ingress/metric/main.go
  internal/nginx/main.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/lua/dynamic_configuration.go
  vendor/github.com/tv42/httpunix/.gitignore
  vendor/github.com/tv42/httpunix/LICENSE
  vendor/github.com/tv42/httpunix/httpunix.go
  vendor/google.golang.org/api/key.json.enc
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3667 worker_connections should be less (3/4th) than worker_rlimit_nofile
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3737 Adjust probe timeouts
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3736 do not unnecessarily log
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3728 Fix flaky test
  internal/ingress/controller/store/store_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3739 dont log unnecessarily
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3750 Update go dependencies
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
  vendor/k8s.io/client-go/.travis.yml
  vendor/k8s.io/client-go/CHANGELOG.md
  vendor/k8s.io/client-go/README.md
  vendor/k8s.io/client-go/rest/config.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/transport/config.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/client-go/transport/token_source.go
  vendor/k8s.io/kubernetes/CHANGELOG-1.13.md
  vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go
  vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_volumes.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/util/boottime_util_darwin.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/boottime_util_linux.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/util_unsupported.go
  vendor/k8s.io/kubernetes/pkg/kubelet/util/util_windows.go
  vendor/k8s.io/kubernetes/pkg/util/mount/BUILD
  vendor/k8s.io/kubernetes/pkg/util/mount/fake.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_helper.go
  vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
  vendor/k8s.io/kubernetes/pkg/volume/util/BUILD
  vendor/k8s.io/kubernetes/pkg/volume/util/util.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, sig/node, sig/storage, size/XXL

#3751 Parse environment variables in OpenTracing configuration
  docs/user-guide/third-party-addons/opentracing.md
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3671 bugfix: fixed duplicated seeds.
  rootfs/etc/nginx/lua/lua_ingress.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#3686 Add debug binary to the docker image
  Gopkg.lock
  Makefile
  build/build.sh
  cmd/dbg/main.go
  docs/troubleshooting.md
  internal/nginx/main.go
  test/e2e/dbg/main.go
  test/e2e/e2e.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/README.md
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.mailmap
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/LICENSE.txt
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/zsh_completions.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3757 Add mention of secure-backends to backend-protocol docs
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3696 Apply annotations to default location
  internal/ingress/controller/controller.go
  test/e2e/defaultbackend/with_hosts.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3748 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
  internal/ingress/controller/util.go
  rootfs/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3747 Update nginx and modules
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#3764 delete confusing CustomErrors attribute to make things more explicit
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3765 simplify customhttperrors e2e test and add regression test and fix a bug
  internal/ingress/types_equals.go
  test/e2e/annotations/customhttperrors.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3766 Support Opentracing with Datadog - part 2
  Makefile
  docs/user-guide/third-party-addons/opentracing.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3767 Support Opentracing with Datadog - part 1
  images/nginx/Makefile
  images/nginx/README.md
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#3772 Fix dashboard link [skip ci]
  docs/examples/auth/oauth-external-auth/README.md
Labels: cncf-cla: yes

#3771 Do not log unnecessarily
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/XS

#3682 enable use-forwarded-headers for L7 LB
  deploy/provider/aws/patch-configmap-l7.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3775 Fix DNS lookup failures in L4 services
  rootfs/etc/nginx/lua/tcp_udp_configuration.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/tcpudp/tcp.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3695 > Don't reload nginx when L4 endpoints changed
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3756 Create custom annotation for satisfy "value"
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/satisfy/main.go
  internal/ingress/annotations/satisfy/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/satisfy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3740 Fix ingress updating for session-cookie-* annotation changes
  internal/ingress/types_equals.go
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
  test/e2e/annotations/affinity.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3782 Lua bridge tracer
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#3785 use latest base nginx image
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3784 use correct host for jaeger-collector-host in docs
  docs/user-guide/third-party-addons/opentracing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3791 - remove annotations in nginxcontroller struct
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3792 dont restart minikube when it is already running
  build/dev-env.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3794 use use-context that actually changes the context
  build/dev-env.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3795 do not warn when optional annotations arent set
  internal/ingress/annotations/authreq/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3787 Use UsePortInRedirects only if enabled
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/forcesslredirect.go
  test/e2e/settings/tls.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3793 Update mergo dependency
  Gopkg.lock
  Gopkg.toml
  internal/ingress/annotations/annotations.go
  internal/ingress/types.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3781 feat: configurable proxy buffers number
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/annotations/proxy/main.go
  internal/ingress/annotations/proxy/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/defaults/main.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/data/config.json
  test/e2e/annotations/proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3809 Upgrade openresty/lua-resty-balancer
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3730 Changes CustomHTTPErrors annotation to use custom default backend
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/customhttperrors.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3811 Fix e2e tests
  test/e2e/annotations/customhttperrors.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3799 Add /dbg certs command
  cmd/dbg/main.go
  internal/nginx/main.go
  rootfs/etc/nginx/lua/configuration.lua
Labels: approved, cncf-cla: yes, lgtm, size/L

#3810 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3812 Removes unused const from customhttperrors e2e test
  test/e2e/annotations/customhttperrors.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3813 Prevent dep from vendoring grpc-fortune-teller dependencies
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3779 Add kubectl plugin
  Gopkg.lock
  Gopkg.toml
  Makefile
  build/build-plugin.sh
  cmd/plugin/ingress-nginx.yaml.tmpl
  cmd/plugin/main.go
  cmd/plugin/request/request.go
  cmd/plugin/util/util.go
  docs/troubleshooting.md
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme/scheme.go
  vendor/k8s.io/cli-runtime/CONTRIBUTING.md
  vendor/k8s.io/cli-runtime/LICENSE
  vendor/k8s.io/cli-runtime/OWNERS
  vendor/k8s.io/cli-runtime/README.md
  vendor/k8s.io/cli-runtime/SECURITY_CONTACTS
  vendor/k8s.io/cli-runtime/code-of-conduct.md
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/builder_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/builder_flags_fake.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags_fake.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/doc.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/filename_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/io_options.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/json_yaml_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/jsonpath_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/kube_template_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/name_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/print_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/discard.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/interface.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/json.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/jsonpath.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/name.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/sourcechecker.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/template.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/typesetter.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/record_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/builder.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/client.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/doc.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/fake.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/helper.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/interfaces.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/mapper.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/result.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/scheme.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/selector.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/visitor.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/template_flags.go
  vendor/k8s.io/client-go/restmapper/category_expansion.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/restmapper/shortcut.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, sig/api-machinery, size/XXL

#3780 Enable access log for default backend
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/defaultbackend/default_backend.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3819 Fix e2e test in osx
  Makefile
  test/e2e-image/Dockerfile
  test/e2e-image/Makefile
  test/e2e-image/wait-for-nginx.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#3820 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3821 Update nginx to 1.15.9
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3822 Set default for satisfy annotation to nothing
  internal/ingress/annotations/satisfy/main.go
  internal/ingress/annotations/satisfy/main_test.go
  test/e2e/annotations/satisfy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3825 Release 0.23.0
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3827 Fix plugin install location
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
