Repository kubernetes/ingress-nginx, pull requests merged in 2019-09, with the labels that each got.

#4487 Refactor health checks and wait until NGINX process ends
  Makefile
  build/build.sh
  cmd/nginx/main.go
  cmd/waitshutdown/main.go
  internal/ingress/controller/checker.go
  internal/ingress/controller/checker_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/metric/collectors/nginx_status_test.go
  internal/nginx/main.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e-image/overlay/deployment-e2e.yaml
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4520 fix typo
  docs/user-guide/basic-usage.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4522 Fix relative links
  docs/user-guide/nginx-configuration/annotations.md
Labels: cncf-cla: yes, ok-to-test, size/XS

#4521 backward compatibility for k8s version < 1.14
  internal/admission/controller/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4527 Switch to official kind images
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, size/XS

#3164 Initial support for CRL in Ingress Controller
  docs/examples/auth/client-certs/README.md
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/controller/store/store.go
  internal/ingress/resolver/main.go
  internal/ingress/sslcert.go
  internal/net/ssl/ssl.go
  internal/net/ssl/ssl_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4528 Cleanup of docker images
  Makefile
  build/run-in-docker.sh
  docs/examples/customization/external-auth-headers/authsvc/Dockerfile
  docs/examples/customization/external-auth-headers/echosvc/Dockerfile
  images/404-server/README.md
  images/OWNERS
  images/README.md
  images/custom-error-pages/Makefile
  images/e2e-prow/Dockerfile
  images/e2e-prow/Makefile
  images/e2e/Dockerfile
  images/e2e/Makefile
  images/fastcgi-helloserver/Makefile
  images/httpbin/Makefile
  images/mkdocs/Dockerfile
  images/mkdocs/entrypoint.sh
  images/nginx/Makefile
  images/ubuntu-slim/README.md
  test/e2e-image/Dockerfile
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4530 Update nginx image to 0.92
  Makefile
  build/run-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4509 Update openresty and third party modules
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#4534 Show current reloads count, not total
  deploy/grafana/dashboards/nginx.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4535 Improve the time to run e2e tests
  build/run-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#4543 Correctly format ipv6 resolver config for lua
  rootfs/etc/nginx/lua/util/resolv_conf.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4506 Fix panic on multiple ingress mess up upstream is primary or not
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4531 WIP Remove nginx unix sockets
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/nginx/main.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/pod_security_policy_volumes.go
Labels: approved, cncf-cla: yes, size/M

#4484 Add terraform scripts to build nginx image
  build/build-nginx-image.sh
  build/images/nginx/.gitignore
  build/images/nginx/Dockerfile
  build/images/nginx/build-nginx.sh
  build/images/nginx/entrypoint.sh
  build/images/nginx/main.tf
  build/images/nginx/variables.tf
  build/images/nginx/versions.tf
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/L

#4545 Rollback luarocks version to 3.1.3
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes

#4547 Fix terraform build of nginx images
  build/build-nginx-image.sh
  build/images/nginx/.dockerignore
  build/images/nginx/.gitignore
  build/images/nginx/build-nginx.sh
  build/images/nginx/entrypoint.sh
  build/images/nginx/main.tf
  build/images/nginx/variables.tf
Labels: approved, cncf-cla: yes, size/L

#4548 regression test for the issue fixed in #4543
  rootfs/etc/nginx/lua/test/util/resolv_conf_test.lua
  rootfs/etc/nginx/lua/util/resolv_conf.lua
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4556 Allow multiple CA Certificates
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/sslcert.go
  internal/net/ssl/ssl.go
  internal/net/ssl/ssl_test.go
Labels: approved, cncf-cla: yes, size/M

#4557 Remove the_real_ip variable
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/nginx-configuration/log-format.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/config/config_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/data/config.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#4560 Support configuring basic auth credentials as a map of user/password hashes
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/auth/main.go
  internal/ingress/annotations/auth/main_test.go
  test/e2e/annotations/auth.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4570 Update nginx image
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#4569 allow to configure jaeger header names
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/third-party-addons/opentracing.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4571 Increase log level for identical CreationTimestamp warning
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4572 Fix log format after #4557
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/nginx-configuration/custom-template.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/config/config_test.go
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#4581 Fix spelling and remove local reference of 404 docker image
  docs/how-it-works.md
  docs/user-guide/default-backend.md
Labels: cncf-cla: yes

#4582 Update kubectl-plugin docs
  docs/kubectl-plugin.md
Labels: approved, cncf-cla: yes, size/M

#4583 Disable go modules
  Makefile
  build/build-plugin.sh
  build/cover.sh
  build/run-in-docker.sh
  build/test.sh
Labels: approved, cncf-cla: yes, size/S

#4584 Remove retries to ExternalName
  build/cover.sh
  build/test.sh
  internal/ingress/controller/endpoints.go
  internal/ingress/controller/endpoints_test.go
Labels: approved, cncf-cla: yes, size/M

#4587 Avoid unnecessary reloads generating lua_shared_dict directives
  internal/ingress/controller/template/template.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4514 Added new affinity mode for maximum session stickyness.
  docs/examples/affinity/cookie/README.md
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/annotations/sessionaffinity/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/balancer/sticky_balanced.lua
  rootfs/etc/nginx/lua/balancer/sticky_persistent.lua
  rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/util/nodemap_test.lua
  rootfs/etc/nginx/lua/util/nodemap.lua
  test/manifests/configuration-a.json
  test/manifests/configuration-b.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#4586 Fix reload when a configmap changes
  internal/ingress/annotations/parser/main.go
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4591 optimize: local cache global variable and avoid single lines over 80
  rootfs/etc/nginx/lua/util.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4550 Add support for configmap of headers for auth-url per ingress
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/authreq/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/resolver/mock.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/auth.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4594 cleanup unused certificates
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  rootfs/etc/nginx/lua/configuration.lua
  rootfs/etc/nginx/lua/test/configuration_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/L

#4592 refactor force ssl redirect logic
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/lua/certificate.lua
  rootfs/etc/nginx/lua/lua_ingress.lua
  rootfs/etc/nginx/lua/test/certificate_test.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#4596 sort auth proxy headers from configmap
  internal/ingress/controller/template/template.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4597 more meaningful assertion for tls hsts test
  test/e2e/settings/tls.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4598 delete redundant config
  images/nginx/rootfs/Dockerfile
  rootfs/Dockerfile
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4595 Rollback change of ModSecurity setting SecAuditLog
  docs/user-guide/third-party-addons/modsecurity.md
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4600 Update nginx image
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4601 Hsts refactoring
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/lua/certificate.lua
  rootfs/etc/nginx/lua/lua_ingress.lua
  rootfs/etc/nginx/lua/test/certificate_test.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#4602 fix bug with new and running configuration comparison
  internal/ingress/controller/nginx.go
  test/e2e/lua/dynamic_certificates.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4588 tls user guide --default-ssl-certificate clarification
  docs/user-guide/tls.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4604 Change default for proxy-add-original-uri-header
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  test/e2e/annotations/grpc.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4606 Mount temporal directory volume for ingress controller
  build/run-in-docker.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4611 Fix custom default backend switch to default
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, size/M

#4607 Release 0.26.0
  Changelog.md
  Makefile
  deploy/cloud-generic/deployment.yaml
  deploy/cloud-generic/kustomization.yaml
  deploy/static/mandatory.yaml
  deploy/static/with-rbac.yaml
  docs/troubleshooting.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4617 Fix ports collision when hostNetwork=true
  cmd/nginx/flags.go
  cmd/nginx/main.go
  docs/user-guide/cli-arguments.md
  internal/ingress/controller/controller.go
  internal/nginx/main.go
Labels: approved, cncf-cla: yes, size/M

#4619 Issue 4244
  cmd/nginx/main.go
  internal/ingress/controller/checker_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#4618 Release 0.26.1
  Changelog.md
  Makefile
  deploy/cloud-generic/deployment.yaml
  deploy/cloud-generic/kustomization.yaml
  deploy/static/mandatory.yaml
  deploy/static/with-rbac.yaml
Labels: approved, cncf-cla: yes, size/S

#4620 ISSUE-4244 e2e test
  test/e2e-image/namespace-overlays/custom-health-check-path/deployment-patch.yaml
  test/e2e-image/namespace-overlays/custom-health-check-path/kustomization.yaml
  test/e2e/settings/customize_health_check_path.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4087 Define Modsecurity Snippet via ConfigMap
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/modsecurity_snippet.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
