Repository kubernetes/ingress-nginx, pull requests merged in 2019-06, with the labels that each got.

#4140 update modsecurity to latest, libmodsecurity to v3.0.3 and owasp-scrs…
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#4150 Update nginx
  Makefile
  build/run-in-docker.sh
  images/e2e/Dockerfile
  internal/ingress/controller/store/store_test.go
  internal/ingress/controller/template/configmap_test.go
  internal/net/net_test.go
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#4153 Add clarification on how to enable path matching
  docs/user-guide/ingress-path-matching.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4159 Partially revert usage of kustomize for installation
  deploy/static/configmap.yaml
  deploy/static/mandatory.yaml
  deploy/static/namespace.yaml
  deploy/static/provider/aws/patch-configmap-l4.yaml
  deploy/static/provider/aws/patch-configmap-l7.yaml
  deploy/static/provider/aws/service-l4.yaml
  deploy/static/provider/aws/service-l7.yaml
  deploy/static/provider/aws/service-nlb.yaml
  deploy/static/provider/baremetal/service-nodeport.yaml
  deploy/static/provider/cloud-generic.yaml
  deploy/static/rbac.yaml
  deploy/static/with-rbac.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/XL

#4160 SSL expiration metrics cannot be tied to dynamic updates
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4048 Change upstream on error when sticky session balancer is used
  docs/examples/affinity/cookie/README.md
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/annotations/sessionaffinity/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
  rootfs/etc/nginx/lua/util/split.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4164 fix source file mods
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/authreq/main_test.go
  internal/ingress/annotations/authreqglobal/main.go
  internal/ingress/annotations/authreqglobal/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/configmap_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4166 Session Affinity ChangeOnFailure should be boolean
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/annotations/sessionaffinity/main_test.go
  internal/ingress/types.go
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#4162 Add "text/javascript" to compressible MIME types
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  test/data/config.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4169 simplify sticky balancer and fix a bug
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/util/split.lua
Labels: approved, cncf-cla: yes, lgtm, size/L

#4119 Only load module ngx_http_modsecurity_module.so when option enable-mo…
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4191 increase lua_shared_dict config data
  internal/ingress/controller/template/template.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4185 Fix: fillout missing health check timeout on health check.
  cmd/nginx/flags.go
  internal/ingress/controller/controller.go
  internal/nginx/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4187 Add unit test cases for balancer lua module
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4204 Add e2e test for service type=ExternalName
  test/e2e/servicebackend/service_externalname.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4128 feature(collectors): Added services to collectorLabels
  internal/ingress/metric/collectors/socket.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4217 Fix typo in annotations
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4219 Get AuthTLS annotation unit tests to 100%
  internal/ingress/annotations/authtls/main_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4212 Add e2e tests for grpc
  go.mod
  go.sum
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/grpc.go
  vendor/github.com/moul/pb/grpcbin/go-grpc/export.go
  vendor/github.com/moul/pb/grpcbin/go-grpc/grpcbin.pb.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4220 Migrate to openresty
  images/nginx/Makefile
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
  images/nginx/rootfs/install_lua_resty_waf.sh
  images/nginx/rootfs/patches/openresty-ssl_cert_cb_yield.patch
Labels: approved, cncf-cla: yes, lgtm, size/L

#4221 Switch to openresty image
  Makefile
  build/run-in-docker.sh
  images/e2e/Dockerfile
  images/e2e/Makefile
  internal/ingress/controller/util.go
  rootfs/Dockerfile
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e-image/Dockerfile
  test/e2e-prow/Dockerfile
  test/e2e-prow/Makefile
  test/e2e/annotations/redirect.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4224 fix monitor test after move to openresty
  rootfs/etc/nginx/lua/test/monitor_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4223 Remove travis-ci badge
  README.md
Labels: approved, cncf-cla: yes, size/XS

#4226 Update nginx image
  Makefile
  build/run-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4227 Fix misspelled and e2e check
  cmd/plugin/lints/deployment.go
  cmd/plugin/lints/ingress.go
  cmd/plugin/util/util.go
  internal/ingress/controller/store/store.go
  test/e2e/dbg/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4225 Update image dependencies
  images/nginx/Makefile
  images/nginx/README.md
  images/nginx/rc.yaml
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/S

#4228 Add notes on timeouts while using long GRPC streams
  docs/examples/grpc/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4229 Do not send empty certificates to nginx
  internal/ingress/controller/nginx.go
  internal/ingress/sslcert.go
  test/e2e/ssl/secret_update.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4180 Service type=ExternalName can be defined with ports
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4233 Update nginx image to 0.90
  Makefile
  build/run-in-docker.sh
  images/e2e/Dockerfile
  images/nginx/README.md
  images/nginx/rc.yaml
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3852 Enable arm again
  Makefile
  build/run-ingress-controller.sh
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/L

#4236 Add e2e test suite to detect memory leaks in lua
  Makefile
  build/run-e2e-suite.sh
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e-image/e2e.sh
  test/e2e/e2e.go
  test/e2e/framework/framework.go
  test/e2e/leaks/lua_ssl.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4250 Lint shell scripts
  build/build-plugin.sh
  build/build.sh
  build/cover.sh
  build/dev-env.sh
  build/run-in-docker.sh
  build/run-ingress-controller.sh
  build/static-check.sh
  build/test-lua.sh
  build/test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#4235 Add new lints
  cmd/plugin/lints/ingress.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4254 Update kind to 0.4.0
  test/e2e-prow/Dockerfile
  test/e2e/kind.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4251 Refactor prometheus leader helper
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/metric/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4253 Remove kubeclient configuration
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4249 test to make sure dynamic cert works trailing dot in domains
  test/e2e/lua/dynamic_certificates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
