Repository kubernetes/ingress-nginx, pull requests merged in 2019-08, with the labels that each got.

#4383 Add support for psp
  docs/examples/psp/README.md
  docs/examples/psp/psp.yaml
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4329 Update references to oauth2_proxy
  docs/examples/auth/oauth-external-auth/README.md
  docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#4389 Fix docs build due to an invalid link
  build/mkdocs/Dockerfile
  docs/examples/psp/README.md
  requirements-docs.txt
Labels: approved, cncf-cla: yes, size/XS

#4410 fix dev-env script
  build/dev-env.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4415 more dev-env script improvements
  build/dev-env.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#4405 Lua shared cfg
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/configmap_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/lua/dynamic_configuration.go
  test/e2e/settings/lua_shared_dicts.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4416 Remove invalid log "Failed to executing diff command: exit status 1"
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4418 Remove dynamic TLS records
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/configmap_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/data/config.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4086 Resolve #4038, move X-Forwarded-Port variable to the location context
  docs/development.md
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e-image/Dockerfile
  test/e2e-image/namespace-overlays/forwarded-port-headers/deployment-patch.yaml
  test/e2e-image/namespace-overlays/forwarded-port-headers/kustomization.yaml
  test/e2e-image/namespace-overlays/forwarded-port-headers/service-patch.yaml
  test/e2e/framework/exec.go
  test/e2e/framework/framework.go
  test/e2e/settings/listen_nondefault_ports.go
  test/e2e/wait-for-nginx.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4420 Cleanup
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/authreq/main_test.go
  internal/ingress/types.go
  internal/k8s/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4423 Add quote function in template
  docs/user-guide/nginx-configuration/custom-template.md
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4426 Update klog
  go.mod
  go.sum
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/net/publicsuffix/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/imports/mkindex.go
  vendor/golang.org/x/tools/imports/mkstdlib.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, size/XXL

#4428 Add timezone value into $geoip2_time_zone variable
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4435 Add option to use existing images
  build/run-ingress-controller.sh
Labels: cncf-cla: yes, size/S

#4438 Add helper to extract prometheus metrics in e2e tests
  test/e2e/framework/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4437 Refactor version helper
  internal/nginx/main.go
  version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4439 Move listen logic to go
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/L

#4440 Fixes for CVE-2018-16843, CVE-2018-16844, CVE-2019-9511, CVE-2019-9513, and CVE-2019-9516
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
  images/nginx/rootfs/patches/patch.2019.h2.txt
Labels: approved, cncf-cla: yes, size/L

#4443 Lua resolv conf parser
  build/dev-env.sh
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/lua/configuration.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/configuration_test.lua
  rootfs/etc/nginx/lua/test/dns_helper.lua
  rootfs/etc/nginx/lua/test/helpers.lua
  rootfs/etc/nginx/lua/test/run.lua
  rootfs/etc/nginx/lua/test/util/dns_test.lua
  rootfs/etc/nginx/lua/test/util/resolv_conf_test.lua
  rootfs/etc/nginx/lua/util/dns.lua
  rootfs/etc/nginx/lua/util/resolv_conf.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4379 Allow Requests to be Mirrored to different backends
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/mirror/main.go
  internal/ingress/annotations/mirror/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/mirror.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#4441 Release 0.25.1
  Changelog.md
  Makefile
Labels: approved, cncf-cla: yes, size/S

#4445 use latest openresty with CVE patches
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
  images/nginx/rootfs/patches/patch.2019.h2.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#4356 Only support SSL dynamic mode
  .gitignore
  build/run-e2e-suite.sh
  cmd/nginx/flags.go
  cmd/nginx/main.go
  cmd/nginx/main_test.go
  cmd/nginx/nginx.go
  docs/kubectl-plugin.md
  internal/file/filesystem.go
  internal/file/filesystem_test.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/authtls/main_test.go
  internal/ingress/controller/checker.go
  internal/ingress/controller/checker_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/metric/collectors/controller.go
  internal/ingress/metric/collectors/controller_test.go
  internal/ingress/resolver/main.go
  internal/ingress/sslcert.go
  internal/ingress/sslcert_test.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  internal/net/ssl/ssl.go
  internal/net/ssl/ssl_test.go
  internal/nginx/main.go
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/authtls.go
  test/e2e/framework/framework.go
  test/e2e/framework/util.go
  test/e2e/lua/dynamic_certificates.go
  test/e2e/settings/default_ssl_certificate.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4422 teach lua about search and ndots settings in resolv.conf
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/tcp_udp_balancer.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/helpers.lua
  rootfs/etc/nginx/lua/test/run.lua
  rootfs/etc/nginx/lua/test/util/dns_test.lua
  rootfs/etc/nginx/lua/util/dns.lua
  test/e2e/servicebackend/service_externalname.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4446 lua-shared-dicts improvements, fixes and documentation
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/configmap_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/lua/dynamic_configuration.go
  test/e2e/settings/lua_shared_dicts.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4351 KEP: Remove static SSL configuration mode
  build/cover.sh
  build/test.sh
  docs/enhancements/20190724-only-dynamic-ssl.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4412 Add nginx ssl_early_data option support
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4448 ewma improvements
  build/test-lua.sh
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/configmap_test.go
  rootfs/etc/nginx/lua/balancer/ewma.lua
  rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
  rootfs/etc/nginx/lua/test/util_test.lua
  rootfs/etc/nginx/lua/util.lua
Labels: approved, cncf-cla: yes, lgtm, size/L

#4450 Add nginx proxy_max_temp_file_size configuration option
  internal/ingress/annotations/proxy/main.go
  internal/ingress/annotations/proxy/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/defaults/main.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4449 Fix service type external name using the name
  internal/ingress/controller/controller.go
  test/e2e/servicebackend/service_externalname.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4452 Fix test description on error
  internal/ingress/annotations/sessionaffinity/main_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4451 post data to Lua only if it changes
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4455 KEP: availability zone aware routing
  docs/enhancements/20190815-zone-aware-routing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4456 Fix file permissions to support volumes
  cmd/nginx/main.go
  internal/file/filesystem.go
  internal/file/structure.go
  internal/ingress/controller/checker_test.go
  internal/ingress/controller/controller_test.go
  internal/net/ssl/ssl.go
  test/e2e/settings/pod_security_policy_volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4458 implementation proposal for zone aware routing
  docs/enhancements/20190815-zone-aware-routing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4459 cleanup logging message typos in rewrite.go
  test/e2e/annotations/rewrite.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4460 cleanup: fix typos in framework.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4327 Add proxy_ssl_* directives
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/proxyssl/main.go
  internal/ingress/annotations/proxyssl/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/store/store.go
  internal/ingress/types.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/proxyssl.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#4409 sort ingress by namespace and name when ingress.CreationTimestamp identical
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4466 Add rate limit units and error status
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#4476 Initialize nginx process error channel
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4485 Update images to 0.25.1
  deploy/cloud-generic/deployment.yaml
  deploy/cloud-generic/kustomization.yaml
  deploy/static/mandatory.yaml
  deploy/static/with-rbac.yaml
Labels: cncf-cla: yes

#4471 Lint code using staticcheck
  cmd/plugin/request/request.go
  internal/ingress/annotations/fastcgi/main_test.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/defaults/main.go
  test/e2e/annotations/auth.go
  test/e2e/defaultbackend/default_backend.go
  test/e2e/framework/exec.go
  test/e2e/framework/k8s.go
  test/e2e/lua/dynamic_configuration.go
  test/e2e/settings/configmap_change.go
  test/e2e/settings/global_external_auth.go
  test/e2e/settings/ingress_class.go
  test/e2e/settings/tls.go
  test/e2e/status/update.go
Labels: approved, cncf-cla: yes, size/M

#4489 Fix log format markdown
  docs/user-guide/nginx-configuration/configmap.md
Labels: cncf-cla: yes

#4463 Always set headers with add-headers option
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4490 Refactor ingress status IP address
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
Labels: approved, cncf-cla: yes, size/L

#4501 Move nginx helper
  internal/ingress/controller/nginx.go
  internal/ingress/controller/process/nginx.go
  internal/nginx/main.go
Labels: approved, cncf-cla: yes, size/S

#4500 Fix nginx variable service_port (nginx)
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/L
