Repository kubernetes/ingress-nginx, pull requests merged in 2019-04, with the labels that each got.

#3955 Plugin select deployment using replicaset name
  cmd/plugin/request/request.go
  cmd/plugin/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3958 Refactor equals
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/ipwhitelist/main.go
  internal/ingress/annotations/luarestywaf/main.go
  internal/ingress/annotations/ratelimit/main.go
  internal/ingress/controller/util.go
  internal/ingress/type_equals_test.go
  internal/ingress/types_equals.go
  internal/sets/match.go
  internal/sets/match_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3807 Lua plugin system - MVP
  rootfs/etc/nginx/lua/plugins.lua
  rootfs/etc/nginx/lua/plugins/hello_world/main.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#3960 Fix segfault on reference to nonexistent configmap
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3968 Update nginx image
  images/nginx/Makefile
  images/nginx/README.md
  images/nginx/rc.yaml
Labels: approved, cncf-cla: yes, size/XS

#3969 Update nginx image to 0.84
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#3970 Release 0.24.0
  Changelog.md
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#3975 Update yaml files to 0.24.0 [skip-ci]
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, size/XS

#3987 Link to kubectl plugin docs in nav
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3980 Refactor isIterable
  internal/sets/match.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3978 Fix CA certificate example docs
  docs/examples/PREREQUISITES.md
  docs/examples/auth/client-certs/README.md
  docs/examples/auth/client-certs/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3990 Fix dynamic cert issue with default-ssl-certificate
  internal/ingress/controller/store/backend_ssl.go
  test/e2e/defaultbackend/custom_default_backend.go
  test/e2e/settings/default_ssl_certificate.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3999 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4007 do not create empty access_by_lua_block
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#4000 Dynamic ssl improvements
  cmd/nginx/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/store/backend_ssl.go
  rootfs/etc/nginx/lua/certificate.lua
  rootfs/etc/nginx/lua/test/certificate_test.lua
  rootfs/etc/nginx/lua/test/fixtures/default-cert.pem
  rootfs/etc/nginx/lua/test/fixtures/example-com-cert.pem
  test/e2e/settings/default_ssl_certificate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3991 Release 0.24.1
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4004 Remove valgrind
  images/nginx/rootfs/build.sh
  internal/ingress/controller/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4008 refactor GetFakeSSLCert
  cmd/nginx/main.go
  internal/ingress/controller/controller_test.go
  internal/net/ssl/ssl.go
  internal/net/ssl/ssl_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4005 Support proxy_next_upstream_timeout
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/annotations/proxy/main.go
  internal/ingress/annotations/proxy/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/defaults/main.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/proxy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4014 Update plugin krew manifest
  build/build-plugin.sh
  cmd/plugin/ingress-nginx.yaml.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#4009 Update nginx to 1.15.12
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#4010 Update nginx image and Go to 1.12.4
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#4022 Add e2e test coverage for mult-auth
  test/e2e/annotations/satisfy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3966 Documentation example code fix
  docs/examples/rewrite/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4034 🔧 fix navigation error in file baremetal.md
  docs/deploy/baremetal.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4040 Fix default Content-Type for custom-error-pages example
  images/custom-error-pages/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4042 Release custom error pages image v0.4 [skip-ci]
  images/custom-error-pages/Makefile
Labels: cncf-cla: yes, size/XS

#4036 Docs have incorrect command in baremetal.md
  docs/deploy/baremetal.md
Labels: approved, cncf-cla: yes, lgtm, size/S
