Repository kubernetes/ingress-nginx, pull requests merged in 2019-01, with the labels that each got.

#3582 Sort ingresses by creation timestamp
  internal/ingress/controller/controller.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3602 Update nginx image
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3596 Fix proxy_host variable configuration
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/proxy_host.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3174 Generalize Rewrite Block Creation and Deprecate AddBaseUrl (not backwards compatible)
  docs/examples/rewrite/README.md
  docs/user-guide/ingress-path-matching.md
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/rewrite/main.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/rewrite.go
  test/manifests/configuration-a.json
  test/manifests/configuration-b.json
  test/manifests/configuration-c.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#3342 Allow privilege escalation
  build/e2e-tests.sh
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
  test/e2e/settings/pod_security_policy.go
  test/manifests/ingress-controller/mandatory.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3615 Pass k8s `Service` data through to the TCP balancer script.
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3592 Add inside the User Guide documentation section a basic usage section and example
  docs/user-guide/basic-usage.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3627 Typo: docs/examples/rewrite/README.md
  docs/examples/rewrite/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3396 New balancer implementation: consistent hash subset
  docs/examples/chashsubset/deployment.yaml
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/upstreamhashby/main.go
  internal/ingress/annotations/upstreamhashby/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/defaults/main.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/balancer/chash.lua
  rootfs/etc/nginx/lua/balancer/chashsubset.lua
  rootfs/etc/nginx/lua/test/balancer/chash_test.lua
  rootfs/etc/nginx/lua/test/balancer/chashsubset_test.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  test/e2e/annotations/upstreamhashby.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3625 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#3620 Added server alias to metrics
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3507 Remove temporal configuration file after a while
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3586 Add --disable-catch-all option to disable catch-all server
  cmd/nginx/flags.go
  docs/user-guide/cli-arguments.md
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  test/e2e/framework/framework.go
  test/e2e/settings/disable_catch_all.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3632 Fixed: error parsing with-rbac.yaml: error converting YAML to JSON
  deploy/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3633 Fix a bug in Ingress update handler
  internal/ingress/controller/store/store.go
  test/e2e/settings/disable_catch_all.go
  test/e2e/settings/ingress_class.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3635 Fix duplicate alternative backend merging
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3634 canary by cookie should support hypen in cookie name
  rootfs/etc/nginx/lua/balancer.lua
  test/e2e/annotations/canary.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3640 add limit connection status code
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/S

#3643 Update nginx
  images/nginx/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3644 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3649 Empty access_by_lua_block breaks satisfy any
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3637 Add support for redirect https to https (from-to-www-redirect)
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
  internal/net/ssl/ssl.go
  internal/net/ssl/ssl_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/authtls.go
  test/e2e/annotations/fromtowwwredirect.go
  test/e2e/framework/framework.go
  test/e2e/lua/dynamic_certificates.go
  test/e2e/settings/tls.go
  test/e2e/ssl/secret_update.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3660 Revert max-worker-connections default value
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, size/S

#3363 Document for cookie expires annotation
  docs/examples/affinity/cookie/README.md
  docs/examples/affinity/cookie/ingress.yaml
  rootfs/etc/nginx/lua/balancer/sticky.lua
  test/e2e/annotations/affinity.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3664 Fix invalid validation creating prometheus valid host values
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3658 Release 0.22.0
  Changelog.md
  Makefile
  deploy/mandatory.yaml
  deploy/with-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#3666 rename sysctlFSFileMax to rlimitMaxNumFiles to reflect what it actually does
  internal/ingress/controller/nginx.go
  internal/ingress/controller/util.go
  internal/ingress/controller/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3680 mention rewrite-target change for 0.22.0
  Changelog.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3674 used cjson.safe instead of pcall.
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/configuration.lua
  rootfs/etc/nginx/lua/monitor.lua
  rootfs/etc/nginx/lua/tcp_udp_balancer.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#3693 Correcting links for gRPC Fortune Teller app
  docs/examples/grpc/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3698 Fix --disable-catch-all
  internal/ingress/controller/store/store.go
  test/e2e/framework/framework.go
  test/e2e/settings/disable_catch_all.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3701 Update usage documentation for default-backend annotation
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3704 make sure dev-env forces context to be minikube
  build/dev-env.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
