Repository kubernetes/ingress-nginx, pull requests merged in 2019-03, with the labels that each got.

#3833 bump luajit version to v2.1-20190228
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3835 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3836 Update mkdocs [skip ci]
  build/mkdocs/Dockerfile
  requirements-docs.txt
Labels: cncf-cla: yes, size/XS

#3829 Prevent e2e-tests from running on non-local clusters
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3743 Remove session-cookie-hash annotation
  docs/examples/affinity/cookie/README.md
  docs/examples/affinity/cookie/ingress.yaml
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/annotations/sessionaffinity/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/configuration_test.lua
  rootfs/etc/nginx/lua/util.lua
  test/e2e/annotations/affinity.go
  test/manifests/configuration-a.json
  test/manifests/configuration-b.json
  test/manifests/configuration-c.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#3846 Fix race condition in metric process collector test
  internal/ingress/metric/collectors/process_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3847 Add missing basic usage documentation link
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3849 Use Gauge instead of Counter for connections_active Prometheus metric
  internal/ingress/metric/collectors/nginx_status.go
  internal/ingress/metric/collectors/nginx_status_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3856 Fix ssl-dh-param issue when secret does not exit
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3871 Fix name of field used to sort ingresses [skip-ci]
  docs/how-it-works.md
Labels: approved, cncf-cla: yes, size/XS

#3874 Update embargo doc link in SECURITY_OWNERS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3864 ing.Service with multiple hosts fix
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/M

#3884 update GKE header to match link in contents
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3886 Clean up ssl package and fix dynamic cert mode
  cmd/nginx/main.go
  internal/ingress/controller/store/backend_ssl.go
  internal/net/ssl/ssl.go
  internal/net/ssl/ssl_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3853 Remove authbind
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
  images/nginx/rootfs/entrypoint.sh
  internal/ingress/controller/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3875 Allow the use of a secret located in a different namespace
  internal/ingress/annotations/auth/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3887 Remove useless nodeip calls and deprecate --force-namespace-isolation
  cmd/nginx/flags.go
  docs/user-guide/cli-arguments.md
  internal/ingress/controller/controller.go
  internal/k8s/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3890 Make sure cli-arguments doc is in alphabetical order
  docs/user-guide/cli-arguments.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3885 Refactor status update
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/status.go
  internal/ingress/metric/collectors/controller.go
  internal/ingress/metric/dummy.go
  internal/ingress/metric/main.go
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3870 Improve kubectl plugin
  cmd/plugin/commands/backends/backends.go
  cmd/plugin/commands/certs/certs.go
  cmd/plugin/commands/conf/conf.go
  cmd/plugin/commands/exec/exec.go
  cmd/plugin/commands/general/general.go
  cmd/plugin/commands/info/info.go
  cmd/plugin/commands/ingresses/ingresses.go
  cmd/plugin/commands/logs/logs.go
  cmd/plugin/commands/ssh/ssh.go
  cmd/plugin/kubectl/kubectl.go
  cmd/plugin/main.go
  cmd/plugin/request/request.go
  cmd/plugin/util/util.go
  internal/nginx/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3889 Separate out annotation assignment logic
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3895 Correctly format ipv6 resolver config for lua
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3808 make dynamic SSL mode default
  cmd/nginx/flags.go
  docs/user-guide/cli-arguments.md
  test/e2e/annotations/authtls.go
  test/e2e/annotations/fromtowwwredirect.go
  test/e2e/lua/dynamic_certificates.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3882 Add support for IPV6 resolvers
  rootfs/etc/nginx/lua/test/util/dns_test.lua
  rootfs/etc/nginx/lua/util/dns.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#3806 Migrate e2e cluster to kind
  .gitignore
  .travis.yml
  Makefile
  test/e2e/kind.yaml
  test/e2e/run.sh
  test/e2e/up.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#3908 Update nginx image
  Makefile
  build/go-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3918 Set `X-Request-ID` for the `default-backend`, too.
  docs/user-guide/custom-errors.md
  images/custom-error-pages/main.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/default_backend.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3927 Update apiVersion to apps/v1, drop duplicate line
  docs/examples/customization/custom-errors/custom-default-backend.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3934 Update nginx image
  build/go-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3933 Update nginx to 1.15.10
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#3900 Add lint subcommand to plugin
  cmd/plugin/commands/lint/main.go
  cmd/plugin/lints/deployment.go
  cmd/plugin/lints/ingress.go
  cmd/plugin/main.go
  cmd/plugin/request/request.go
  cmd/plugin/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3841 Improve "Sticky session" docs
  docs/examples/affinity/cookie/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3839 Fix panic on multiple non-matching canary
  internal/ingress/controller/controller.go
  test/e2e/annotations/canary.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3932 Fix dynamic SSL certificate for aliases and redirect-from-to-www
  internal/ingress/controller/nginx.go
  test/e2e/annotations/fromtowwwredirect.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3947 Adds a log warning when falling back to default fake cert
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3798 Move some configuration logic from Nginx config to Lua code
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/lua/lua_ingress.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/forcesslredirect.go
  test/e2e/settings/tls.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3945 fix typo: delete '`'
  docs/user-guide/tls.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3950 Fix forwarded host parsing
  rootfs/etc/nginx/lua/lua_ingress.lua
  test/e2e/settings/forwarded_headers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3786 Fix x-forwarded-prefix annotation
  cmd/plugin/lints/ingress.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/xforwardedprefix/main.go
  internal/ingress/annotations/xforwardedprefix/main_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/types.go
  test/e2e/annotations/xforwardedprefix.go
Labels: approved, cncf-cla: yes, lgtm, size/L
