Repository kubernetes/ingress-nginx, pull requests merged in 2020-11, with the labels that each got.

#6401 Fix controller service annotations
  charts/ingress-nginx/templates/controller-service.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6389 Support prefix pathtype
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/lua/lua_ingress.lua
  test/e2e/ingress/pathtype_prefix.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#6356 Add securitycontext settings on defaultbackend
  charts/ingress-nginx/templates/default-backend-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6412 Improve ingress class error message
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, size/XS

#6415 Prepare release 0.41.0
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6419 Release chart 3.8.0 - v0.41.0
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, cncf-cla: yes, size/XL

#6420 Release v0.41.0
  Changelog.md
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/M

#6422 Add comment indicating server-snippet section
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6426 Alternate to respecting setting admissionWebhooks.failurePolicy in values.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6417 Reload nginx when L4 proxy protocol change
  internal/ingress/types_equals.go
  internal/ingress/types_equals_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6445 fix: empty IngressClassName, Error handling
  internal/ingress/annotations/class/main.go
  internal/ingress/annotations/class/main_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6447 Improve class.IsValid logs
  go.mod
  go.sum
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/S

#6423 Add Default backend HPA autoscaling.
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
  charts/ingress-nginx/templates/default-backend-hpa.yaml
  charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6443 Refactor handling of path Prefix and Exact
  go.mod
  go.sum
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/location.go
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/lua/lua_ingress.lua
  test/e2e/annotations/rewrite.go
  test/e2e/ingress/pathtype_exact.go
  test/e2e/ingress/pathtype_mixed.go
Labels: approved, cncf-cla: yes, size/L

#6453 Prepare release 0.41.1
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6454 Release chart 3.10.0
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, size/S

#6455 Release v0.41.1
  Changelog.md
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/XL

#6468 Prepare release 0.41.2
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6471 Release chart 3.10.1
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, size/S

#6472 Release 0.41.2
  Changelog.md
  charts/ingress-nginx/CHANGELOG.md
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/XL

#6473 Enable external auth e2e tests
  test/e2e/annotations/auth.go
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, size/M

#6481 docs(annotations): explicit redirect status code
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6486 Fix typo
  docs/deploy/hardening-guide.md
  docs/enhancements/20190815-zone-aware-routing.md
  docs/examples/grpc/README.md
  docs/user-guide/ingress-path-matching.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6494 Update development.md with docker version and experimental feature requirment
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6493 Support Keda Autoscaling
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-hpa.yaml
  charts/ingress-nginx/templates/controller-keda.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6480 Refactor extraction of ingress pod details
  cmd/nginx/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/status.go
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
  internal/k8s/main.go
  internal/k8s/main_test.go
  internal/k8s/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, size/L

#6499 Fix opentracing propagation on auth-url
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6501 Add Chart changelog instructions
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6485 Fix sum value of nginx process connections
  deploy/grafana/dashboards/nginx.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6294 Allow customisation of redirect URL parameter in external auth redirects
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/authreq/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/configmap_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/auth.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#6505 Reorder HPA resource list to work with GitOps tooling
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-hpa.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6514 Remove helm2 support and update docs
  .github/workflows/helm.yaml
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#6526 Fix helm repo update command
  charts/ingress-nginx/README.md
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/XS

#6529 Fix ErrorLogLevel in stream contexts
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6533 Update nginx to 1.19.5
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/M
