Repository kubernetes/ingress-nginx, pull requests merged in 2020-12, with the labels that each got.

#6550 Ensure any change in the charts directory trigger ci tests
  .github/workflows/ci.yaml
Labels: approved, cncf-cla: yes, size/XS

#6553 fixes: allow user to specify the maxmium number of retries in stream block
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6558 Update kindest image
  .github/workflows/ci.yaml
  build/dev-env.sh
  test/e2e/run-chart-test.sh
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, size/S

#6544 Fix the name of default backend variable
  charts/ingress-nginx/templates/default-backend-hpa.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6574 Release helm chart v3.13.0
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6561 Disable HTTP/2 in the webhook server
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, size/XS

#6560 Fix nginx ingress variables for definitions without hosts
  internal/ingress/controller/template/template.go
  test/e2e/ingress/without_host.go
Labels: approved, cncf-cla: yes, size/M

#6566 fix docs log-format-upstream sample
  docs/user-guide/nginx-configuration/configmap.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6541 fixed misspell
  rootfs/etc/nginx/lua/plugins/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6470 Added role binding for 'ingress-nginx-admission' to PSP example (#6018)
  docs/examples/psp/psp.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6576 Fix nginx ingress variables for definitions with Backend
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/template.go
  test/e2e/ingress/without_host.go
Labels: approved, cncf-cla: yes, size/L

#6577 Update build TAG
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6578 Update helm chart-testing image
  test/e2e/run-chart-test.sh
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, size/S

#6469 Allow custom service names for controller and backend (#6457)
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6579 Update README.md
  docs/examples/rewrite/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6580 fix for 6564
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6587 feat(nginx.tmpl): Add support for GeoLite2-Country and GeoIP2-Country databases
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6586 fix(chart): Move 'maxmindLicenseKey' to `controller.maxmindLicenseKey`
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6592 Update github actions
  .github/workflows/ci.yaml
  .github/workflows/docs.yaml
  .github/workflows/helm.yaml
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6593 Rollback chart-releaser action
  .github/workflows/helm.yaml
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6594 Fix chart-releaser action
  .github/workflows/helm.yaml
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6595 Fix helm chart releaser action
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6596 Fix helm chart releaser action
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6598 Add a link to the helm ingress-nginx `CHANGELOG.md` file to the `README.md` file
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6607 fix flaky lua tests
  rootfs/etc/nginx/lua/test/configuration_test.lua
  rootfs/etc/nginx/lua/test/monitor_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#6546 bugfix: update trafficShapingPolicy not working in ewma load-balance
  rootfs/etc/nginx/lua/balancer/ewma.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6608 make sure canary attributes are reset on ewma backend sync
  rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/S

#6614 Refactor ingress nginx variables
  internal/ingress/controller/location.go
  internal/ingress/controller/template/template.go
  internal/ingress/types.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/S

#6617 Allow FQDN for ExternalName Service
  internal/ingress/controller/endpoints.go
  internal/ingress/controller/endpoints_test.go
  test/e2e/servicebackend/service_externalname.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6621 Update go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/L

#6623 fix typo
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6620 Fix sticky session not set for host in server-alias annotation (#6448)
  internal/ingress/controller/controller.go
  test/e2e/annotations/affinity.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6627 Update nginx to 1.19.6
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/S

#6528 Spelling
  docs/deploy/hardening-guide.md
  docs/e2e-tests.md
  docs/enhancements/YYYYMMDD-kep-template.md
  docs/examples/affinity/cookie/README.md
  docs/user-guide/cli-arguments.md
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/annotations/auth/main_test.go
  internal/ingress/annotations/authtls/main_test.go
  internal/ingress/annotations/proxyssl/main_test.go
  internal/ingress/annotations/ratelimit/main_test.go
  internal/ingress/annotations/secureupstream/main.go
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/metric/collectors/process.go
  internal/ingress/status/status_test.go
  internal/ingress/types.go
  internal/net/ssl/ssl_test.go
  internal/task/queue_test.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/certificate.lua
  rootfs/etc/nginx/lua/configuration.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/monitor_test.lua
  test/data/config.json
  test/e2e/annotations/affinity.go
  test/e2e/annotations/influxdb.go
  test/e2e/annotations/proxy.go
  test/e2e/framework/framework.go
  test/e2e/framework/k8s.go
  test/e2e/ingress/pathtype_exact.go
  test/e2e/leaks/lua_ssl.go
  test/e2e/servicebackend/service_externalname.go
  test/manifests/configuration-a.json
  test/manifests/configuration-b.json
  test/manifests/configuration-c.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#6629 Add kind e2e tests support for k8s v1.20.0
  .github/workflows/ci.yaml
Labels: approved, cncf-cla: yes, size/XS

#6628 Update nginx image
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#6636 Fix link to kustomize docs
  deploy/static/provider/aws/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6635 Update test images and go to 1.15.6
  images/echo/Makefile
  images/nginx/README.md
  images/nginx/rc.yaml
  images/test-runner/Makefile
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, size/S

#6638 Update test images
  build/run-in-docker.sh
  test/e2e-image/Dockerfile
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, size/XS

#6642 Update README.md
  docs/examples/customization/configuration-snippets/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6652 Change helm chart tag name to disambiguate purpose
  .github/workflows/helm.yaml
Labels: approved, cncf-cla: yes, size/XS

#6646 Adding LoadBalancerIP value for internal service to Helm chart
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-service-internal.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6660 Fix chart-releaser action
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6665 added AKS specific documentation
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6600 Bugfix: some requests fail with 503 when nginx reload
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6639 Don't pick tried endpoint & count the latest in ewma balancer
  rootfs/etc/nginx/lua/balancer/ewma.lua
  rootfs/etc/nginx/lua/test/balancer/ewma_test.lua
  rootfs/etc/nginx/lua/test/util/split.lua
  rootfs/etc/nginx/lua/util/split.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#6672 Prepare release v0.42.0
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6674 Release helm chart v3.17.0
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/S

#6675 Release v0.42.0
  Changelog.md
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/XL

#6676 include new resty lua libs in base image
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#6680 Update cloudbuild gcb-docker-gcloud image
  cloudbuild.yaml
  images/cfssl/cloudbuild.yaml
  images/echo/cloudbuild.yaml
  images/fastcgi-helloserver/cloudbuild.yaml
  images/httpbin/cloudbuild.yaml
  images/nginx/cloudbuild.yaml
  images/test-runner/cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/S

#6682 Update nginx image
  Makefile
  images/echo/Makefile
  images/nginx/README.md
  images/nginx/rc.yaml
  images/test-runner/Makefile
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6683 Remove dead code
  internal/ingress/annotations/annotations_test.go
  internal/ingress/controller/checker.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/template/template.go
  test/e2e/framework/framework.go
  test/e2e/lua/dynamic_configuration.go
  test/e2e/settings/ocsp/ocsp.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6684 Update ingress-nginx test image
  build/run-in-docker.sh
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6685 Add GeoIP Local mirror support
  charts/ingress-nginx/templates/controller-daemonset.yaml
  cmd/nginx/flags.go
  cmd/nginx/flags_test.go
  internal/nginx/maxmind.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6688 feat: allow volume-type emptyDir in controller podsecuritypolicy
  charts/ingress-nginx/templates/controller-psp.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6691 Helm: Ingress config change
  charts/ingress-nginx/templates/controller-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6692 add string split function to template funcMap
  docs/user-guide/nginx-configuration/custom-template.md
  internal/ingress/controller/template/template.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6694 Release helm chart
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/S

#6697 Do not assume ingress-nginx is using recommended labels
  internal/k8s/main.go
Labels: approved, cncf-cla: yes, size/S

#6700 Prepare release 0.43.0
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6701 Release helm chart v3.19.0
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/S

#6702 Release ingress-nginx 0.43.0
  Changelog.md
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/XL

#6695 include lua-resty-ipmatcher and lua-resty-global-throttle inn the base image
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#6705 Update nginx alpine image to 3.12
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/XS
