Repository kubernetes/ingress-nginx, pull requests merged in 2020-09, with the labels that each got.

#6104 Misc fixes for nginx-ingress chart for better keel and prom-oper
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6087 Adding parameter for externalTrafficPolicy in internal controller service spec.
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-service-internal.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5881 Doc: Adding initial hardening guide
  docs/deploy/hardening-guide.md
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#6097 Return unique addresses from service
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6098 Update kubernetes kind e2e versions
  .github/workflows/ci.yaml
Labels: approved, cncf-cla: yes, size/XS

#5757 feat: support to define trusted addresses for proxy protocol in stream block
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/proxy_protocol.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6099 Update go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XL

#6111 Update kind node version to v1.19.0
  build/dev-env.sh
Labels: approved, cncf-cla: yes, size/XS

#6112 Update go dependencies to fix build logr errors
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/M

#6113 Require Kubernetes v1.14 or higher and deprecate extensions
  cmd/nginx/main.go
  internal/admission/controller/main.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/status/status.go
Labels: approved, cncf-cla: yes, size/L

#6114 Update go to 1.5.1 and add arm64
  images/test-runner/Makefile
  images/test-runner/rootfs/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#6115 Increase cloudbuild timeout value
  images/test-runner/cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS

#6116 Update e2e image
  build/run-in-docker.sh
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#6118 Cleanup github actions
  .github/workflows/ci.yaml
  .github/workflows/docs.yaml
  .github/workflows/helm.yaml
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/M

#6122 Update trace modules
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/L

#6125 Library dd-opentracing cannot be static
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/XS

#6129 Update test runner image
  images/test-runner/Makefile
Labels: approved, cncf-cla: yes, size/XS

#6130 Update deploy instructions with corrections
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6143 Update default gzip level
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, size/XS

#6128 Fixed proxy protocol link
  docs/user-guide/exposing-tcp-udp-services.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6145 Switch modules to dynamic and remove http_dav_module
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/S

#6148 Update cloudbuild jobs
  cloudbuild.yaml
  images/cfssl/cloudbuild.yaml
  images/echo/cloudbuild.yaml
  images/fastcgi-helloserver/cloudbuild.yaml
  images/httpbin/cloudbuild.yaml
  images/nginx/cloudbuild.yaml
  images/test-runner/cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/S

#6149 Update qemu-user-static image
  hack/init-buildx.sh
Labels: approved, cncf-cla: yes, size/XS

#6153 Add install command for Scaleway
  deploy/static/provider/scw/deploy.yaml
  deploy/static/provider/scw/kustomization.yaml
  docs/deploy/index.md
  hack/generate-deploy-scripts.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#6101 Add annotation to set value for burst multiplier on rate limit
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/ratelimit/main.go
  internal/ingress/annotations/ratelimit/main_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6150 Reject ingresses that use the default annotation if a custom one was provided
  cmd/nginx/flags.go
  internal/ingress/annotations/parser/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6154 chart: add `topologySpreadConstraint` to controller
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6127 AKS example of adding an internal loadbalancer
  charts/ingress-nginx/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6166 Update kind and kindest/node images
  .github/workflows/ci.yaml
  test/e2e/run-chart-test.sh
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, size/S

#6167 Update chart requirements
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/L

#6169 Fix Typo in example prometheus rules
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6177 Fix make help task to display options
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#6181 Improve prerequisite instructions
  docs/examples/PREREQUISITES.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6180 Fix helm chart admissionReviewVersions regression
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
Labels: approved, cncf-cla: yes, size/XS

#6176 Update go modules
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/L

#6184 Update static manifest yaml files
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, cncf-cla: yes, size/L

#5229 Grammar and spelling fixes
  docs/enhancements/20190815-zone-aware-routing.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6171 Docs: remove redundant --election-id arg from Multiple Ingresses
  docs/user-guide/multiple-ingress.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6186 Fix logr dependency issue
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/M

#6170 delete redundant NGINX config about X-Forwarded-Proto
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/forwarded_headers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6187 Add validation support for networking.k8s.io/v1
  internal/admission/controller/main.go
Labels: approved, cncf-cla: yes, size/S

#6190 Change server-tokens default value to false
  docs/deploy/hardening-guide.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  test/e2e/settings/pod_security_policy.go
  test/e2e/settings/pod_security_policy_volumes.go
Labels: approved, cncf-cla: yes, size/S

#6172 Update OSFileWatcher to support symlinks
  internal/watch/file_watcher.go
  internal/watch/file_watcher_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6196 disable session tickets by default
  docs/deploy/hardening-guide.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6198 Delete OCSP Response cache when certificate renewed
  build/test-lua.sh
  rootfs/etc/nginx/lua/certificate.lua
  rootfs/etc/nginx/lua/configuration.lua
  rootfs/etc/nginx/lua/test/configuration_test.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6200 Move ocsp_response_cache:delete after certificate_data:set
  rootfs/etc/nginx/lua/configuration.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6162 Add helm chart options to expose metrics service as NodePort
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-service-metrics.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6203 Refactor key/value parsing
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6214 Update annotations.md - improvements to the documentation of Client Certificate Authentication
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6215 Update the comment for Makefile taks live-docs
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6221 corrected reference for release
  docs/enhancements/20190724-only-dynamic-ssl.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6226 Change defaults
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/configmap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6233 Add admission controller e2e test
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  internal/admission/controller/main.go
  internal/admission/controller/main_test.go
  internal/admission/controller/server.go
  internal/admission/controller/server_test.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/store/ingress.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
  test/e2e-image/namespace-overlays/admission/values.yaml
  test/e2e/admission/admission.go
  test/e2e/e2e.go
Labels: approved, cncf-cla: yes, size/L

#6217 Add annotation to configure CORS Access-Control-Expose-Headers
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/cors/main.go
  internal/ingress/annotations/cors/main_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/cors.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6231 Clear redundant Cross-Origin-Allow- headers from response
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6235 Update go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/L

#6211 Migrate to structured logging (klog)
  cmd/nginx/flags.go
  cmd/nginx/main.go
  cmd/waitshutdown/main.go
  internal/admission/controller/main.go
  internal/admission/controller/server.go
  internal/file/file.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/secureupstream/main.go
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/status.go
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/tcp.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/util.go
  internal/ingress/metric/collectors/controller.go
  internal/ingress/metric/collectors/nginx_status.go
  internal/ingress/metric/collectors/socket.go
  internal/ingress/metric/main.go
  internal/ingress/status/status.go
  internal/k8s/main.go
  internal/net/dns/dns.go
  internal/net/ssl/ssl.go
  internal/nginx/main.go
  internal/task/queue.go
  test/e2e/annotations/affinitymode.go
  test/e2e/framework/framework.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, size/L

#5348 Ability to separately disable access log in http and stream contexts
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/disableaccesslog.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6241 Update e2e tests list doc
  docs/e2e-tests.md
Labels: approved, cncf-cla: yes, size/L

#6240 Fix e2e test error
  test/e2e/annotations/disableaccesslog.go
Labels: approved, cncf-cla: yes, size/M

#6243 Update nginx to 1.19.3
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/XS

#6246 Cleanup proxy protocol e2e test
  test/e2e/settings/proxy_protocol.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6250 Update nginx image and go to 1.15.2
  images/echo/Makefile
  images/test-runner/Makefile
Labels: approved, cncf-cla: yes, size/S

#6247 Update nginx image
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#6251 Update test runner image
  build/run-in-docker.sh
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#6252 Prepare for release v0.40.0
  TAG
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/XS
