Repository kubernetes/ingress-nginx, pull requests merged in 2020-08, with the labels that each got.

#5971 Fixed typo "permanen"
  test/e2e/annotations/redirect.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5965 feat(baremetal): Add kustomization.yaml
  deploy/static/provider/aws/kustomization.yaml
  deploy/static/provider/baremetal/kustomization.yaml
  deploy/static/provider/cloud/kustomization.yaml
  deploy/static/provider/do/kustomization.yaml
  deploy/static/provider/kind/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5980 fix for 5590
  docs/enhancements/YYYYMMDD-kep-template.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5984 Fix panic in ingress class validation
  internal/ingress/annotations/class/main.go
  internal/ingress/annotations/class/main_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4139 Always collect metrics when --metrics-per-host=false
  docs/user-guide/monitoring.md
  internal/ingress/metric/collectors/socket.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5987 Fix wait times in e2e tests
  test/e2e/annotations/auth.go
  test/e2e/framework/framework.go
  test/e2e/gracefulshutdown/shutdown.go
Labels: approved, cncf-cla: yes, size/XS

#5990 Fix nginx command env variable reference
  internal/ingress/controller/util.go
Labels: approved, cncf-cla: yes, size/S

#5994 Clean up minikube installation instructions
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6000 Fix error message formatting
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6001 Update psp example
  docs/examples/psp/psp.yaml
Labels: approved, cncf-cla: yes, size/M

#6004 Update nginx to 1.19.2
  images/nginx/cloudbuild.yaml
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/XS

#6008 Rollback update of Jaeger library to 0.5.0 and update datadog to 1.2.0
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/S

#6014 Update go dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/L

#6022 fix typo in development.md
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6020 Added missing backend protocol.
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6038 Document migration path to ingress-nginx chart from stable/nginx-ingress
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  docs/deploy/upgrade.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#6044 Chart readme fixes
  charts/ingress-nginx/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#6046 Add new Dockerfile label org.opencontainers.image.revision
  Makefile
  build/build-plugin.sh
  build/build.sh
  cloudbuild.yaml
  rootfs/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#6047 Increase wait times in e2e tests
  test/e2e/annotations/limitconnections.go
  test/e2e/framework/framework.go
  test/e2e/gracefulshutdown/shutdown.go
Labels: approved, cncf-cla: yes, size/XS

#6052 Fix flaky e2e test
  test/e2e/settings/global_external_auth.go
Labels: approved, cncf-cla: yes, size/XS

#6056 Rollback to Poll instead of PollImmediate
  test/e2e/annotations/auth.go
  test/e2e/framework/framework.go
  test/e2e/framework/k8s.go
  test/e2e/framework/ssl.go
  test/e2e/framework/util.go
  test/e2e/settings/listen_nondefault_ports.go
Labels: approved, cncf-cla: yes, size/M

#6039 Add configurable serviceMonitor metricRelabelling and targetLabels
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6042 Fix typo
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6075 Sync helm chart affinity examples
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, size/S

#6076 Update NLB idle timeout information
  deploy/static/provider/aws/deploy.yaml
  docs/deploy/index.md
  hack/generate-deploy-scripts.sh
Labels: approved, cncf-cla: yes, size/S

#6080 Use k8s.gcr.io vanity domain
  Makefile
  build/run-in-docker.sh
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  docs/deploy/upgrade.md
  images/echo/Makefile
  images/nginx/README.md
  images/nginx/rc.yaml
  images/test-runner/Makefile
  test/e2e-image/Dockerfile
  test/e2e/framework/deployment.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: approved, cncf-cla: yes, size/L

#6081 Prepare for release v0.35.0
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6082 Add build_id dockerfile label
  Makefile
  rootfs/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#6088 Add new env variables to cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, size/XS

#6090 Rollback TAG version
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6091 Prepare for release v0.35.0
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6093 Release v0.35.0
  Changelog.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/XL
