Repository kubernetes/ingress-nginx, pull requests merged in 2020-10, with the labels that each got.

#6253 Release v0.40.0
  Changelog.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/XL

#6258 Fix chart markdown link
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, size/XS

#6259 Release helm chart
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6264 Update triage/support label references to kind/support
  .github/ISSUE_TEMPLATE/support-question.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6265 Add support for admission review v1beta1
  internal/admission/controller/convert.go
  internal/admission/controller/main.go
  internal/admission/controller/main_test.go
  internal/admission/controller/server.go
  internal/admission/controller/server_test.go
Labels: approved, cncf-cla: yes, size/L

#6266 Prepare for release v0.40.1
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6267 Release v0.40.1
  Changelog.md
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/L

#6268 Update helm chart
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, size/XS

#6272 Update hardening guide doc
  docs/deploy/hardening-guide.md
Labels: approved, cncf-cla: yes, size/XS

#6278 Sync user guide with config defaults changes
  docs/user-guide/nginx-configuration/configmap.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6282 Enable e2e tests for k8s v1.16
  .github/workflows/ci.yaml
Labels: approved, cncf-cla: yes, size/XS

#6283 Start v0.41.0 cycle
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6284 Improve HandleAdmission resiliency
  internal/admission/controller/main.go
  internal/admission/controller/main_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6285 Prepare release 0.40.2
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6286 Release 0.40.2
  Changelog.md
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/XL

#6288 Update to 0.40.2 in helm chart
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, size/XS

#6037 Do not append a trailing slash on redirects
  rootfs/etc/nginx/lua/lua_ingress.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/forcesslredirect.go
  test/e2e/annotations/fromtowwwredirect.go
  test/e2e/settings/tls.go
  test/e2e/ssl/http_redirect.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6260 Allow Helm Chart to customize admission webhook's annotations, timeoutSeconds, namespaceSelector, objectSelector and cert files locations
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
  hack/generate-deploy-scripts.sh
  test/e2e-image/namespace-overlays/admission/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6299 Fix helm chart release
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/XS

#6255 Update datadog opentracing plugin to v1.2.0
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#6305 Add default linux nodeSelector
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6319 Update static manifests
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, cncf-cla: yes, size/L

#6321 Fix typo
  docs/deploy/hardening-guide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6316 Numerals in podAnnotations in quotes #6315
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/ci/daemonset-podannotations-values.yaml
  charts/ingress-nginx/ci/deployment-podannotations-values.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6261 Add datadog environment as a configuration option
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/third-party-addons/opentracing.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6325 Filter out secrets that belong to Helm v3
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6326 Fix liveness and readiness probe path in daemonset chart
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6331 fix for 6219
  docs/user-guide/miscellaneous.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6366 Enable validation of ingress definitions from extensions package
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  cmd/nginx/main.go
  internal/admission/controller/main.go
  internal/admission/controller/main_test.go
  internal/ingress/annotations/class/main.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/status/status_test.go
  internal/k8s/main.go
  test/e2e/admission/admission.go
  test/e2e/framework/framework.go
  test/e2e/ingress/pathtype_exact.go
  test/e2e/settings/ingress_class.go
Labels: approved, cncf-cla: yes, size/L

#6349 Refactor Exact path matching
  internal/ingress/controller/template/template.go
  test/e2e/ingress/pathtype_exact.go
Labels: approved, cncf-cla: yes, size/XS

#6348 Add validation for wildcard server names
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/M

#6372 Check pod is ready
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
Labels: approved, cncf-cla: yes, size/S

#6373 Remove k8s.io/kubernetes dependency
  go.mod
  go.sum
  hack/update-codegen.sh
  internal/ingress/controller/controller.go
  internal/ingress/controller/util.go
  internal/ingress/status/status.go
  test/e2e/framework/framework.go
  test/e2e/framework/k8s.go
Labels: approved, cncf-cla: yes, size/L

#6375 Improve log messages
  internal/admission/controller/main.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, size/M

#6382 fix: OWASP CoreRuleSet rules for NodeJS and Java
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6383 Update nginx to 1.19.4
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
  images/nginx/rootfs/patches/nginx-1.17.8-no_Werror.patch
  images/nginx/rootfs/patches/nginx-1.19.3-balancer_status_code.patch
  images/nginx/rootfs/patches/nginx-1.19.3-cache_manager_exit.patch
  images/nginx/rootfs/patches/nginx-1.19.3-delayed_posted_events.patch
  images/nginx/rootfs/patches/nginx-1.19.3-hash_overflow.patch
  images/nginx/rootfs/patches/nginx-1.19.3-init_cycle_pool_release.patch
  images/nginx/rootfs/patches/nginx-1.19.3-larger_max_error_str.patch
  images/nginx/rootfs/patches/nginx-1.19.3-no_Werror.patch
  images/nginx/rootfs/patches/nginx-1.19.3-proxy_host_port_vars.patch
  images/nginx/rootfs/patches/nginx-1.19.3-resolver_conf_parsing.patch
  images/nginx/rootfs/patches/nginx-1.19.3-reuseport_close_unused_fds.patch
  images/nginx/rootfs/patches/nginx-1.19.3-single_process_graceful_exit.patch
  images/nginx/rootfs/patches/nginx-1.19.3-socket_cloexec.patch
  images/nginx/rootfs/patches/nginx-1.19.3-ssl_cert_cb_yield.patch
  images/nginx/rootfs/patches/nginx-1.19.3-ssl_sess_cb_yield.patch
  images/nginx/rootfs/patches/nginx-1.19.3-stream_proxy_get_next_upstream_tries.patch
  images/nginx/rootfs/patches/nginx-1.19.3-stream_ssl_preread_no_skip.patch
  images/nginx/rootfs/patches/nginx-1.19.3-upstream_pipelining.patch
  images/nginx/rootfs/patches/nginx-1.19.3-upstream_timeout_fields.patch
Labels: approved, cncf-cla: yes, size/L

#6385 Update helm stable repo
  charts/ingress-nginx/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6384 Update nginx image to 1.19.4
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#6388 Update nginx image in project images
  images/echo/Makefile
  images/nginx/README.md
  images/nginx/rc.yaml
  images/test-runner/Makefile
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, size/S

#6390 Update go to 1.15.3
  images/test-runner/Makefile
Labels: cncf-cla: yes, size/XS

#6391 Update alpine packages
  images/test-runner/rootfs/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#6395 Update jettech/kube-webhook-certgen image
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, size/XS

#6377 Added loadBalancerSourceRanges for internal lbs
  charts/ingress-nginx/templates/controller-service-internal.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6403 Initial helm chart changelog
  charts/ingress-nginx/Changelog.md
Labels: approved, cncf-cla: yes, size/L
