Repository kubernetes/ingress-nginx, pull requests merged in 2020-03, with the labels that each got.

#5202 Refactored client body buffer size TC-s.
  test/e2e/annotations/clientbodybuffersize.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5201 Added TC for proxy connect, read, and send timeout
  test/e2e/annotations/proxy.go
  test/e2e/settings/proxy_connect_timeout.go
  test/e2e/settings/proxy_read_timeout.go
  test/e2e/settings/proxy_send_timeout.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5205 Add OWNERS file for helm chart
  charts/ingress-nginx/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5213 Make quote function to render pointers in the template properly
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5216 Check go exists in $PATH
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5211 Update NGINX to 1.17.9
  images/nginx/Makefile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/XS

#5221 Update NGINX image
  Makefile
  build/run-in-docker.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#5217 Added affinity-mode tc and refactored affinity.go
  test/e2e/annotations/affinity.go
  test/e2e/annotations/affinitymode.go
  test/e2e/framework/k8s.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5225 Avoid secret without tls.crt and tls.key but a valid ca.crt
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, size/XS

#5226 Fix $service_name and $service_port variables values without host
  internal/ingress/controller/template/template.go
Labels: approved, cncf-cla: yes, size/XS

#5194 I found a typo :)
  docs/user-guide/nginx-configuration/configmap.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5232 Refacored proxy ssl TC-s
  test/e2e/annotations/proxyssl.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5207 [helm chart] Hardcode component names.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/NOTES.txt
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/templates/clusterrolebinding.yaml
  charts/ingress-nginx/templates/controller-configmap-addheaders.yaml
  charts/ingress-nginx/templates/controller-configmap-proxyheaders.yaml
  charts/ingress-nginx/templates/controller-configmap-tcp.yaml
  charts/ingress-nginx/templates/controller-configmap-udp.yaml
  charts/ingress-nginx/templates/controller-configmap.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/controller-hpa.yaml
  charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/controller-prometheusrules.yaml
  charts/ingress-nginx/templates/controller-psp.yaml
  charts/ingress-nginx/templates/controller-role.yaml
  charts/ingress-nginx/templates/controller-rolebinding.yaml
  charts/ingress-nginx/templates/controller-service-metrics.yaml
  charts/ingress-nginx/templates/controller-service-webhook.yaml
  charts/ingress-nginx/templates/controller-service.yaml
  charts/ingress-nginx/templates/controller-serviceaccount.yaml
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
  charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/default-backend-psp.yaml
  charts/ingress-nginx/templates/default-backend-role.yaml
  charts/ingress-nginx/templates/default-backend-rolebinding.yaml
  charts/ingress-nginx/templates/default-backend-service.yaml
  charts/ingress-nginx/templates/default-backend-serviceaccount.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5175 Migrate the backends handle logic to function
  rootfs/etc/nginx/lua/configuration.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#4958 Add a forwarded protocol map for included x-forwarded-proto.
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4632 run lua plugin tests
  .luacheckrc
  build/test-lua.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5241 Fix controller container name
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5246 Remove checks for older versions
  charts/ingress-nginx/templates/controller-configmap.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5250 Use rbac scope feature in e2e tests
  test/e2e/wait-for-nginx.sh
Labels: approved, cncf-cla: yes, size/L

#5251 Add support for custom healthz path in helm chart
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5249 Add support for hostPort in Deployment
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5252 Check chart controller image tag
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5258 Cleanup of chart labels
  build/dev-env.sh
  go.sum
  test/e2e-image/namespace-overlays/custom-health-check-path/values.yaml
  test/e2e-image/namespace-overlays/forwarded-port-headers/values.yaml
  test/e2e/framework/exec.go
  test/e2e/framework/framework.go
  test/e2e/settings/pod_security_policy.go
  test/e2e/settings/pod_security_policy_volumes.go
  test/e2e/wait-for-nginx.sh
Labels: approved, cncf-cla: yes, size/M

#5268 do not require go for building
  Makefile
  build/run-in-docker.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#5262 Add Maxmind Editions support
  cmd/nginx/flags.go
  cmd/nginx/flags_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/nginx/maxmind.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5266 Redirect for app-root should preserve current scheme
  internal/ingress/annotations/rewrite/main.go
  internal/ingress/annotations/rewrite/main_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/approot.go
Labels: approved, cncf-cla: yes, size/M

#5264 Fix reference to DH param secret, recommend larger parameter size
  docs/examples/customization/ssl-dh-param/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5269 Ensure DeleteDeployment waits until there are no pods running
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, size/XS

#5274 [docs]: fix deploy Prerequisite section
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5276 Fix the ability to disable ModSecurity at location level
  internal/ingress/annotations/modsecurity/main.go
  internal/ingress/annotations/modsecurity/main_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  test/e2e/annotations/modsecurity.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5281 Remove unnecessary logs
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/plugins/hello_world/test/.empty
  rootfs/etc/nginx/lua/tcp_udp_balancer.lua
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5277 refactoring: use more specific var name
  rootfs/etc/nginx/lua/certificate.lua
  rootfs/etc/nginx/lua/test/certificate_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/S

#5283 Add retries for dns in tcp e2e test
  test/e2e/tcpudp/tcp.go
Labels: approved, cncf-cla: yes, size/S

#5284 Wait for update in tcp e2e test
  test/e2e/tcpudp/tcp.go
Labels: approved, cncf-cla: yes, size/XS

#5289 Update go and e2e image
  build/images/ingress-controller/build-ingress-controller.sh
  build/images/nginx/build-nginx.sh
  build/run-in-docker.sh
  images/e2e-prow/Dockerfile
  images/e2e/Makefile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#5290 Add DS_PROMETHEUS datasource for templating
  deploy/grafana/dashboards/request-handling-performance.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5298 Increase e2e concurrency
  Makefile
  cmd/nginx/flags_test.go
Labels: approved, cncf-cla: yes, size/XS

#5301 Forward X-Request-ID to auth service
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/XS

#5296 Added proxy-ssl-location-only test.
  test/e2e/annotations/proxyssl.go
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
