Repository kubernetes/ingress-nginx, pull requests merged in 2020-05, with the labels that each got.

#5481 fix first backend sync
  rootfs/etc/nginx/lua/balancer.lua
Labels: approved, cncf-cla: yes, lgtm, size/S

#5487 Add note about firewall ports for admission webhook
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/S

#5486 Release 0.32.0
  Changelog.md
  Makefile
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  docs/deploy/index.md
  docs/deploy/upgrade.md
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, size/XL

#5488 Update kind
  images/e2e-prow/Makefile
  test/e2e/run-chart-test.sh
Labels: approved, cncf-cla: yes, size/XS

#5503 Update job-patchWebhook.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5504 Add configuration option for the imagePullSecrets in the webhook jobs
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5494 Add configuration option for the runAsUser parameter of the webhook patch job
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5512 Wrong filename in documantation example
  docs/examples/tls-termination/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5516 build: remove unnecessary tag line in e2e
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5491 Actually enable TLSv1.3 by default
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  test/e2e/settings/tls.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5536 Fix error setting $service_name NGINX variable
  internal/ingress/controller/template/template.go
  test/e2e/ingress/multiple_rules.go
Labels: approved, cncf-cla: yes, size/L

#5522 Remove duplicate annotation parsing for annotationAffinityCookieChangeOnFailure
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/annotations/sessionaffinity/main_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5553 Check service If publish-service flag is defined
  cmd/nginx/main.go
Labels: approved, cncf-cla: yes, size/M

#5463 Wait before any request to the ingress controller pod
  test/e2e/framework/framework.go
  test/e2e/lua/dynamic_configuration.go
Labels: approved, cncf-cla: yes, size/XS

#5563 Use ingress-nginx-* naming in docs to match the default deployments
  docs/deploy/baremetal.md
  docs/deploy/index.md
  docs/examples/customization/configuration-snippets/README.md
  docs/examples/customization/custom-configuration/README.md
  docs/examples/customization/custom-configuration/configmap.yaml
  docs/examples/customization/custom-errors/README.md
  docs/examples/customization/custom-headers/README.md
  docs/examples/customization/custom-headers/configmap.yaml
  docs/examples/customization/ssl-dh-param/README.md
  docs/examples/customization/ssl-dh-param/configmap.yaml
  docs/user-guide/third-party-addons/opentracing.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5566 Update configmap name in custom-headers/README.md
  docs/examples/customization/custom-headers/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5572 [chart] Add toleration support for admission webhooks
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5584 Add note about initial delay during first start
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/S

#5582 Allow pulling images by digest
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5586 Add MaxMind GeoIP2 Anonymous IP support
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5596 Update go dependencies
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/cgroups.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/dryrun.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/helper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/arguments.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/process.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/integration/internal/tinyca.go
Labels: approved, cncf-cla: yes, size/XL

#5603 Update nginx to 1.19.0
  images/nginx/Makefile
  images/nginx/rc.yaml
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/S

#5604 Update debian-base image
  build/images/ingress-controller/Dockerfile
  build/images/nginx/Dockerfile
  images/fastcgi-helloserver/rootfs/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#5606 Update nginx image and go to 1.14.3
  Makefile
  build/images/ingress-controller/build-ingress-controller.sh
  build/images/nginx/build-nginx.sh
  build/run-in-docker.sh
  images/e2e/Dockerfile
  images/e2e/Makefile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#5578 Use image promoter to push images to gcr
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5534 Add annotation ssl-prefer-server-ciphers.
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/sslcipher/main.go
  internal/ingress/annotations/sslcipher/main_test.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/sslciphers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5621 Update terraform build images
  build/build-nginx-image.sh
  build/images/ingress-controller/.dockerignore
  build/images/ingress-controller/Dockerfile
  build/images/ingress-controller/build.sh
  build/images/ingress-controller/entrypoint.sh
  build/images/ingress-controller/main.tf
  build/images/ingress-controller/variables.tf
  build/images/nginx/.dockerignore
  build/images/nginx/Dockerfile
  build/images/nginx/build.sh
  build/images/nginx/entrypoint.sh
  build/images/nginx/main.tf
  build/images/nginx/variables.tf
Labels: approved, cncf-cla: yes, size/L

#5624 feat: add lj-releng tool to check Lua code for finding the potential problems
  images/e2e/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5625 Update nginx image to use alpine 3.12
  images/nginx/Makefile
  images/nginx/rootfs/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#5626 Update nginx image
  images/nginx/Makefile
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/S

#5619 Use new multi-arch nginx image
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5629 Build multi-arch images by default
  Makefile
  build/images/ingress-controller/build.sh
  build/run-in-docker.sh
  images/cfssl/Makefile
  images/cfssl/rootfs/Dockerfile
  images/e2e-prow/Makefile
  images/e2e/Dockerfile
  images/e2e/Makefile
  images/echo/Dockerfile
  images/echo/Makefile
  images/echo/nginx.conf
  images/fastcgi-helloserver/Makefile
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/httpbin/Makefile
  images/httpbin/rootfs/Dockerfile
  test/e2e-image/Dockerfile
  test/e2e/framework/deployment.go
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, size/L

#5630 Fix makefile task names
  build/dev-env.sh
  build/images/nginx/build.sh
  build/run-ingress-controller.sh
  test/e2e-image/Makefile
Labels: approved, cncf-cla: yes, size/S

#5631 Update e2e image
  build/run-in-docker.sh
  images/e2e-prow/Makefile
  images/e2e/Dockerfile
  images/e2e/Makefile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#5632 Update buildx progress configuration
  build/build-ingress-controller.sh
  build/build-nginx-image.sh
  images/cfssl/Makefile
  images/e2e-prow/Makefile
  images/echo/Makefile
  images/fastcgi-helloserver/Makefile
  images/httpbin/Makefile
Labels: approved, cncf-cla: yes, size/XS

#5613 fix oauth2-proxy image repository
  docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
