Repository kubernetes/ingress-nginx, pull requests merged in 2020-02, with the labels that each got.

#4996 Fix status update for clusters where networking.k8s.io is not available
  internal/ingress/status/status.go
Labels: approved, cncf-cla: yes, size/XS

#4995 Cleanup main makefile and remove the need of sed
  Makefile
  build/build.sh
  rootfs/Dockerfile
Labels: approved, cncf-cla: yes, size/M

#4999 Fix limitrange definition
  deploy/cloud-generic/deployment.yaml
  deploy/static/mandatory.yaml
Labels: approved, cncf-cla: yes, size/S

#5003 Fix server aliases
  internal/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, size/S

#5000 Update python syntax in OAuth2 example
  docs/examples/auth/oauth-external-auth/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5010 Update nginx image
  images/nginx/38cb695de87cfeadcba5eeaf57f39e41d529aa1f.tar.gz
  images/nginx/Makefile
  images/nginx/README.md
  images/nginx/rc.yaml
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
  images/nginx/rootfs/patches/nginx-1.17.8-balancer_status_code.patch
  images/nginx/rootfs/patches/nginx-1.17.8-cache_manager_exit.patch
  images/nginx/rootfs/patches/nginx-1.17.8-hash_overflow.patch
  images/nginx/rootfs/patches/nginx-1.17.8-larger_max_error_str.patch
  images/nginx/rootfs/patches/nginx-1.17.8-reuseport_close_unused_fds.patch
  images/nginx/rootfs/patches/nginx-1.17.8-single_process_graceful_exit.patch
  images/nginx/rootfs/patches/nginx-1.17.8-socket_cloexec.patch
  images/nginx/rootfs/patches/nginx-1.17.8-ssl_cert_cb_yield.patch
  images/nginx/rootfs/patches/nginx-1.17.8-ssl_sess_cb_yield.patch
  images/nginx/rootfs/patches/nginx-1.17.8-upstream_pipelining.patch
  images/nginx/rootfs/patches/nginx-1.17.8-upstream_timeout_fields.patch
Labels: approved, cncf-cla: yes, lgtm, size/L

#5011 Update nginx image, go to 1.13.7 and e2e image
  Makefile
  build/images/ingress-controller/build-ingress-controller.sh
  build/images/nginx/build-nginx.sh
  build/run-in-docker.sh
  images/e2e/Dockerfile
  images/e2e/Makefile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#5009 Move mod-security logic from template to go code
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, size/L

#5016 Fix dep-ensure task
  Makefile
  images/grpc-fortune-teller/go.mod
Labels: cncf-cla: yes, size/XS

#5018 Update developer document on dependency updates
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5015 Refactor mirror feature
  cmd/plugin/lints/ingress.go
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/authreq/main_test.go
  internal/ingress/annotations/mirror/main.go
  internal/ingress/annotations/mirror/main_test.go
  internal/ingress/annotations/parser/main.go
  internal/ingress/annotations/parser/main_test.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/template.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/mirror.go
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#5028 Add echo image to avoid building and installing dependencies in each …
  images/echo/Dockerfile
  images/echo/Makefile
  images/echo/nginx.conf
  test/e2e/framework/deployment.go
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, size/L

#5020 docs(deploy): fix helm install command for helm v3
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5036 Disable DIND in script run-in-docker.sh
  build/run-in-docker.sh
Labels: cncf-cla: yes, size/XS

#5037 Cleanup README.md
  README.md
Labels: cncf-cla: yes, size/M

#5035 Update github.com/paultag/sniff dependency
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#5038 Update code to use pault.ag/go/sniff package
  go.mod
  go.sum
  internal/ingress/controller/tcp.go
  vendor/github.com/armon/go-proxyproto/protocol.go
  vendor/github.com/mitchellh/go-ps/README.md
  vendor/github.com/mitchellh/go-ps/go.mod
  vendor/github.com/mitchellh/go-ps/process_freebsd.go
  vendor/github.com/mitchellh/go-ps/process_unix.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
  vendor/pault.ag/go/sniff/LICENSE
  vendor/pault.ag/go/sniff/parser/parser.go
Labels: approved, cncf-cla: yes, size/L

#5031 Update kindest/node version to v1.17.2
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, size/XS

#5041 36.94% size reduction of image assets using lossless compression from ImgBot
  deploy/grafana/dashboards/screenshot.png
  docs/images/baremetal/baremetal_overview.jpg
  docs/images/baremetal/cloud_overview.jpg
  docs/images/baremetal/hostnetwork.jpg
  docs/images/baremetal/metallb.jpg
  docs/images/baremetal/nodeport.jpg
  docs/images/baremetal/user_edge.jpg
  docs/images/elb-l7-listener.png
  docs/images/grafana.png
  docs/images/jaeger-demo.png
  docs/images/prometheus-dashboard.png
  docs/images/zipkin-demo.png
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5043 Cleanup docs
  Makefile
  docs/examples/customization/custom-errors/README.md
  docs/examples/docker-registry/README.md
  docs/user-guide/fcgi-services.md
  docs/user-guide/ingress-path-matching.md
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/tls.md
  labels.yaml
  requirements-docs.txt
Labels: cncf-cla: yes, size/M

#5032 Fix fortune-teller app manifest
  docs/examples/grpc/app.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5042 Fix X-Forwarded-Proto based on proxy-protocol server port
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/lua/lua_ingress.lua
  test/e2e/settings/proxy_protocol.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5040 Update documentation and remove hack fixed by upstream cookie library
  docs/user-guide/nginx-configuration/annotations.md
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5050 Add flag to allow custom ingress status update intervals
  cmd/nginx/flags.go
  docs/user-guide/cli-arguments.md
  internal/ingress/status/status.go
Labels: approved, cncf-cla: yes, size/S

#5052 Change the handling of ConfigMap creation
  internal/ingress/controller/store/store.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5053 Validation of header in authreq should be done only in the key
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/authreq/main_test.go
Labels: approved, cncf-cla: yes, size/XS

#5055 Only set mirror source when a target is configured
  internal/ingress/annotations/mirror/main.go
  internal/ingress/annotations/mirror/main_test.go
  test/e2e/annotations/mirror.go
Labels: approved, cncf-cla: yes, size/XS

#5059 Remove minikube and only use kind
  build/dev-env.sh
  build/run-in-docker.sh
  build/run-ingress-controller.sh
  deploy/kind/kustomization.yaml
  deploy/kind/service-hostport.yaml
  docs/deploy/index.md
  docs/development.md
  docs/user-guide/third-party-addons/opentracing.md
Labels: approved, cncf-cla: yes, size/L

#5061 Fix scripts to run in osx
  build/dev-env.sh
  test/e2e/run.sh
Labels: cncf-cla: yes

#5062 Ensure scripts and dev-env works in osx
  Makefile
  build/dev-env.sh
Labels: cncf-cla: yes

#5068 docs: reference buildx as a requirement for docker builds
  Makefile
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5070 Update go to 1.13.8
  build/images/ingress-controller/build-ingress-controller.sh
  build/images/nginx/build-nginx.sh
  build/run-in-docker.sh
  images/e2e/Makefile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#5069 Enable grpc e2e tests
  deploy/kind/deployment.yaml
  deploy/kind/kustomization.yaml
  test/e2e/annotations/grpc.go
  test/e2e/annotations/influxdb.go
  test/e2e/framework/deployment.go
  test/e2e/framework/exec.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/framework/framework.go
  test/e2e/framework/grpc_fortune_teller.go
  test/e2e/framework/influxdb.go
  test/e2e/framework/k8s.go
  test/e2e/run.sh
  test/e2e/servicebackend/service_backend.go
Labels: approved, cncf-cla: yes, size/L

#5067 Make sure set-cookie is retained from external auth endpoint
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/auth.go
Labels: approved, cncf-cla: yes, size/M

#5073 oauth-external-auth: README.md: Link to oauth2-proxy, dashboard-ingress.yaml
  docs/examples/auth/oauth-external-auth/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5071 Add gzip-min-length as a Configuration Option
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/configmap_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5065 Created test case for add headers configmap
  test/e2e/settings/custom_header.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5075 Release 0.29.0
  Changelog.md
  Makefile
  deploy/cloud-generic/deployment.yaml
  deploy/cloud-generic/kustomization.yaml
  deploy/static/mandatory.yaml
  deploy/static/with-rbac.yaml
  docs/deploy/index.md
  docs/deploy/upgrade.md
  docs/examples/grpc/README.md
  docs/examples/psp/README.md
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/L

#5083 Cleanup docker build
  build/images/ingress-controller/build-ingress-controller.sh
  images/nginx/38cb695de87cfeadcba5eeaf57f39e41d529aa1f.tar.gz
  images/nginx/Makefile
Labels: approved, cncf-cla: yes, size/S

#5081 Fixed incorrect documentation of cli flag --default-backend-service
  docs/examples/customization/custom-errors/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5084 Cleanup docker build
  images/nginx/rootfs/Dockerfile
  rootfs/Dockerfile
Labels: cncf-cla: yes

#5085 Cleanup build of nginx image
  images/nginx/Makefile
Labels: cncf-cla: yes

#5087 Fox docker opencontainers version label
  rootfs/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#5086 Migration e2e installation to helm
  Makefile
  build/dev-env.sh
  deploy/aws/l4/kustomization.yaml
  deploy/aws/l7/kustomization.yaml
  deploy/aws/nlb/kustomization.yaml
  deploy/baremetal/kustomization.yaml
  deploy/cloud-generic/deployment.yaml
  deploy/cloud-generic/kustomization.yaml
  deploy/cloud-generic/role-binding.yaml
  deploy/cloud-generic/role.yaml
  deploy/cloud-generic/service-account.yaml
  deploy/cloud-generic/service.yaml
  deploy/cluster-wide/cluster-role-binding.yaml
  deploy/cluster-wide/cluster-role.yaml
  deploy/cluster-wide/kustomization.yaml
  deploy/kind/deployment.yaml
  deploy/kind/kustomization.yaml
  deploy/kind/service-hostport.yaml
  internal/ingress/controller/store/store.go
  test/e2e-image/Dockerfile
  test/e2e-image/Makefile
  test/e2e-image/namespace-overlays/custom-health-check-path/deployment-patch.yaml
  test/e2e-image/namespace-overlays/custom-health-check-path/kustomization.yaml
  test/e2e-image/namespace-overlays/custom-health-check-path/values.yaml
  test/e2e-image/namespace-overlays/forwarded-port-headers/deployment-patch.yaml
  test/e2e-image/namespace-overlays/forwarded-port-headers/kustomization.yaml
  test/e2e-image/namespace-overlays/forwarded-port-headers/service-patch.yaml
  test/e2e-image/namespace-overlays/forwarded-port-headers/values.yaml
  test/e2e-image/overlay/deployment-e2e.yaml
  test/e2e-image/overlay/deployment-namespace-patch.yaml
  test/e2e-image/overlay/kustomization.yaml
  test/e2e-image/overlay/role.yaml
  test/e2e-image/overlay/service-cluster-patch.yaml
  test/e2e-image/overlay/service-protocol-tcp.yaml
  test/e2e/annotations/proxy.go
  test/e2e/framework/deployment.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/framework/framework.go
  test/e2e/framework/util.go
  test/e2e/run.sh
  test/e2e/settings/customize_health_check_path.go
  test/e2e/settings/pod_security_policy.go
  test/e2e/settings/pod_security_policy_volumes.go
  test/e2e/status/update.go
  test/e2e/tcpudp/tcp.go
  test/e2e/wait-for-nginx.sh
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/XXL

#5088 Remove .cache directory with make clean.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5089 Abort any task in case of errors running shell commands
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5092 Print information about e2e suite tests
  Makefile
  hack/print-e2e-suite.sh
Labels: approved, cncf-cla: yes, size/M

#5093 Generate doc with list of e2e tests
  docs/e2e-tests.md
  hack/generate-e2e-suite-doc.sh
Labels: cncf-cla: yes, size/L

#5095 Update datadog tracer to v1.1.3
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5094 Remove comment from e2e_test.go
  test/e2e/e2e_test.go
Labels: approved, cncf-cla: yes, size/XS

#5098 Fix make dev-env
  build/dev-env.sh
Labels: approved, cncf-cla: yes, size/M

#5091 Add case for when user agent is nil
  rootfs/etc/nginx/lua/test/util/same_site_test.lua
  rootfs/etc/nginx/lua/util/same_site.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5100 Ensure make dev-env support rolling updates
  build/dev-env.sh
Labels: cncf-cla: yes, size/S

#5097 New e2e test: log-format-escape-json and log-format-upstream
  test/e2e/settings/log-format.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5101 Add keep-alive config check test
  test/e2e/settings/keep-alive.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5105 Reuse-port check e2e tc (config check only)
  test/e2e/settings/reuse-port.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5111 ingress-path-matching: doc typo
  docs/user-guide/ingress-path-matching.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5123 Ensure helm repository and charts are available
  Makefile
  build/dev-env.sh
Labels: cncf-cla: yes

#5127 Update changelog
  Changelog.md
Labels: cncf-cla: yes

#5124 make dev-env improvements
  build/dev-env.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#5122 refactor ssl handling in preparation of OCSP stapling
  rootfs/etc/nginx/lua/certificate.lua
  rootfs/etc/nginx/lua/configuration.lua
Labels: approved, cncf-cla: yes, lgtm, size/M

#5117 Hash size e2e check test case
  test/e2e/settings/hash-size.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5134 Update list of e2e tests
  docs/e2e-tests.md
Labels: cncf-cla: yes, size/L

#5132 Lint go code
  test/e2e/annotations/serversnippet.go
  test/e2e/framework/framework.go
  test/e2e/framework/util.go
  test/e2e/lua/dynamic_certificates.go
  test/e2e/settings/hash-size.go
  test/e2e/settings/keep-alive.go
  test/e2e/settings/reuse-port.go
Labels: approved, cncf-cla: yes, size/L

#5136 Add upstream keep alive tests
  test/e2e/settings/keep-alive.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5135 Correct spelling of the word "Original" in annotations documentation
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5103 Added configmap test for no-tls-redirect-locations
  test/e2e/settings/no_tls_redirect_locations.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5109 Added basic limit-rate configmap test.
  test/e2e/settings/limit_rate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5139 Fixes https://github.com/kubernetes/ingress-nginx/issues/5120
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5140 Added configmap test for ssl-ciphers.
  test/e2e/settings/ssl_ciphers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5125 Added tc for limit-connection annotation
  test/e2e/annotations/canary.go
  test/e2e/annotations/limitconnections.go
  test/e2e/framework/k8s.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5141 Allow service type ExternalName with different port and targetPort
  internal/ingress/controller/controller.go
  internal/ingress/controller/endpoints.go
Labels: approved, cncf-cla: yes, size/M

#4963 fix: Fix typo
  test/e2e/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5145 Refactor the HSTS related test file and add config check to the HSTS tests
  test/e2e/settings/tls.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5080 Add label selector for plugin
  cmd/plugin/commands/backends/backends.go
  cmd/plugin/commands/certs/certs.go
  cmd/plugin/commands/conf/conf.go
  cmd/plugin/commands/exec/exec.go
  cmd/plugin/commands/general/general.go
  cmd/plugin/commands/logs/logs.go
  cmd/plugin/commands/ssh/ssh.go
  cmd/plugin/request/request.go
  cmd/plugin/util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5149 Use helm template instead of update to install dev cluster
  build/dev-env.sh
Labels: approved, cncf-cla: yes, size/XS

#5150 Update default VariablesHashBucketSize value to 256
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, size/XS

#5151 Check there is a difference in the template besides the checksum
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, size/XS

#5153 Update nginx and e2e images
  Makefile
  build/run-in-docker.sh
  images/e2e-prow/Dockerfile
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#5152 Clean template
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5131 Add request handling performance dashboard
  deploy/grafana/dashboards/.markdownlint.json
  deploy/grafana/dashboards/README.md
  deploy/grafana/dashboards/request-handling-performance.json
  deploy/grafana/dashboards/request-handling.png
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#5155 Release 0.30.0
  Changelog.md
  Makefile
  deploy/static/mandatory.yaml
  deploy/static/with-rbac.yaml
  docs/deploy/index.md
  docs/deploy/upgrade.md
  docs/examples/grpc/README.md
  docs/examples/psp/README.md
  docs/examples/static-ip/nginx-ingress-controller.yaml
Labels: approved, cncf-cla: yes, size/M

#5158 Fix push task
  Makefile
Labels: cncf-cla: yes

#5157 Added limit-rate annotation test
  test/e2e/annotations/limitrate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5160 Fix e2e test run.sh
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5162 Migrate release of docs from travis-ci to github actions
  .github/actions/mkdocs/Dockerfile
  .github/actions/mkdocs/action.sh
  .github/actions/mkdocs/action.yml
  .github/workflows/main.yaml
  .travis.yml
  .travis/common.sh
  .travis/publish-docs.sh
  .travis/release-from-travis.sh
Labels: approved, cncf-cla: yes, size/L

#5163 Cleanup build of documentation and update to mkdocs 1.1
  Makefile
  images/mkdocs/Dockerfile
  images/mkdocs/entrypoint.sh
  requirements-docs.txt
Labels: cncf-cla: yes, size/M

#4981 Applying proxy-ssl-* directives on locations only
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5114 Feat: add header-pattern annotation.
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/canary/main.go
  internal/ingress/controller/controller.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/lua/balancer.lua
  test/e2e/annotations/canary.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5165 Use local chart directory for dev-env and e2e tests
  build/dev-env.sh
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  test/e2e-image/.gitignore
  test/e2e-image/Dockerfile
  test/e2e-image/Makefile
  test/e2e/wait-for-nginx.sh
Labels: approved, cncf-cla: yes, size/S

#5166 proxy_ssl_name support
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/proxyssl/main.go
  internal/ingress/annotations/proxyssl/main_test.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5169 Cleanup e2e directory
  test/e2e-image/.gitignore
  test/e2e/down.sh
Labels: approved, cncf-cla: yes, size/S

#5172 Add script to check helm chart
  Makefile
  hack/verify-chart-lint.sh
Labels: cncf-cla: yes, size/S

#5173 Update go to 1.14
  build/images/ingress-controller/build-ingress-controller.sh
  build/images/nginx/build-nginx.sh
  images/e2e-prow/Dockerfile
  images/e2e-prow/Makefile
  images/e2e/Makefile
Labels: approved, cncf-cla: yes, size/S

#5170 Update go dependencies
  go.mod
  go.sum
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go
  vendor/k8s.io/cloud-provider/cloud.go
  vendor/k8s.io/cloud-provider/go.mod
  vendor/k8s.io/cloud-provider/go.sum
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, size/XXL

#5174 Update e2e image
  build/run-in-docker.sh
  hack/verify-chart-lint.sh
  images/e2e/Dockerfile
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#5171 Sync chart PR #20984
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/clusterrole.yaml
  charts/ingress-nginx/templates/clusterrolebinding.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, size/XS

#5178 Adding annotations support to helm chart configmaps
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-configmap.yaml
  charts/ingress-nginx/templates/tcp-configmap.yaml
  charts/ingress-nginx/templates/udp-configmap.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#5182 Update go mod for 1.14
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cncf-cla: yes, size/M

#5181 Fix public function comment
  cmd/plugin/request/request.go
Labels: approved, cncf-cla: yes, size/XS

#5183 Remove unused docker file
  .dockerignore
Labels: approved, cncf-cla: yes, size/XS

#5190 Refactored test/e2e/annotations/proxy.go
  test/e2e/annotations/proxy.go
  test/e2e/settings/proxy_next_upstream.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test

#5185 [helm chart] Use recommended labels and label helpers
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/addheaders-configmap.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/templates/clusterrole.yaml
  charts/ingress-nginx/templates/clusterrolebinding.yaml
  charts/ingress-nginx/templates/controller-configmap.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/controller-hpa.yaml
  charts/ingress-nginx/templates/controller-metrics-service.yaml
  charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/controller-prometheusrules.yaml
  charts/ingress-nginx/templates/controller-psp.yaml
  charts/ingress-nginx/templates/controller-role.yaml
  charts/ingress-nginx/templates/controller-rolebinding.yaml
  charts/ingress-nginx/templates/controller-service.yaml
  charts/ingress-nginx/templates/controller-serviceaccount.yaml
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
  charts/ingress-nginx/templates/controller-webhook-service.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
  charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/default-backend-psp.yaml
  charts/ingress-nginx/templates/default-backend-role.yaml
  charts/ingress-nginx/templates/default-backend-rolebinding.yaml
  charts/ingress-nginx/templates/default-backend-service.yaml
  charts/ingress-nginx/templates/default-backend-serviceaccount.yaml
  charts/ingress-nginx/templates/proxyheaders-configmap.yaml
  charts/ingress-nginx/templates/tcp-configmap.yaml
  charts/ingress-nginx/templates/udp-configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5192 Update helm templates to match new chart name
  charts/ingress-nginx/.helmignore
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/NOTES.txt
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/addheaders-configmap.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/templates/clusterrole.yaml
  charts/ingress-nginx/templates/clusterrolebinding.yaml
  charts/ingress-nginx/templates/controller-configmap.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/controller-hpa.yaml
  charts/ingress-nginx/templates/controller-metrics-service.yaml
  charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/controller-prometheusrules.yaml
  charts/ingress-nginx/templates/controller-psp.yaml
  charts/ingress-nginx/templates/controller-role.yaml
  charts/ingress-nginx/templates/controller-rolebinding.yaml
  charts/ingress-nginx/templates/controller-service.yaml
  charts/ingress-nginx/templates/controller-serviceaccount.yaml
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
  charts/ingress-nginx/templates/controller-webhook-service.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
  charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/default-backend-psp.yaml
  charts/ingress-nginx/templates/default-backend-role.yaml
  charts/ingress-nginx/templates/default-backend-rolebinding.yaml
  charts/ingress-nginx/templates/default-backend-service.yaml
  charts/ingress-nginx/templates/default-backend-serviceaccount.yaml
  charts/ingress-nginx/templates/proxyheaders-configmap.yaml
  charts/ingress-nginx/templates/tcp-configmap.yaml
  charts/ingress-nginx/templates/udp-configmap.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
