Repository kubernetes/ingress-nginx, pull requests merged in 2021-05, with the labels that each got.

#7101 Remove usage of codecov.io for the time being
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6838 Adding note to Custom Timeouts in Annotation Docs.
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#6993 Fix cookieAffinity log printing error
  internal/ingress/annotations/sessionaffinity/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7046 [Helm] allow configuring controller container name
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6994 Fixed oauth2 callback url
  docs/examples/auth/oauth-external-auth/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7114 Fixed markdown typo in deploy/index.md
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7027 baremetal docs: fix example IP address
  docs/deploy/baremetal.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7104 Create development guide section
  docs/developer-guide/code-overview.md
  docs/developer-guide/getting-started.md
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#7131 fix: use exponential backoff policy to listen on `nginx.StatusPort` in unit test cases
  internal/ingress/controller/checker_test.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/metric/collectors/nginx_status_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6740 Bugfix: non-host canary ingress use default server name as host to merge
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7126 set x-forwarded-scheme to be the same as x-forwarded-proto
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/settings/forwarded_headers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7137 Add support for custom probes
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#7150 Remove "Development" from Welcome page
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7144 Allow preservation of trailing slashes on TLS redirects via annotation.
  internal/ingress/annotations/rewrite/main.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/template.go
  internal/ingress/defaults/main.go
  rootfs/etc/nginx/lua/lua_ingress.lua
  test/e2e/annotations/preservetrailingslash.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#7095 updated values.yaml and templates to have separate values for registr…
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7134 feat: multiple-cors-allow-origin support
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/cors/main.go
  internal/ingress/annotations/cors/main_test.go
  test/e2e/annotations/cors.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6955 perf: json encoding share to eatch request
  rootfs/etc/nginx/lua/monitor.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#7168 Revert "feat: multiple-cors-allow-origin support"
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/cors/main.go
  internal/ingress/annotations/cors/main_test.go
  test/e2e/annotations/cors.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7179 Upgrade Nginx to 1.20.1
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7182 Update the sha for nginx 1.20.1
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7183 Updating sha 256 sum for nginx 1.20.1
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7061 Fix typo in docs
  docs/how-it-works.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS, ¯\_(ツ)_/¯

#7174 Commented by default deprecated repository key/value pair
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6734 Update controller-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, ok-to-test, size/XS

#7185 update release docs with build.sh SHA requirements
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
