Repository kubernetes/ingress-nginx, pull requests merged in 2021-04, with the labels that each got.

#6971 Fix crl not reload when crl got updated in the ca secret
  internal/ingress/controller/store/store.go
  internal/ingress/types_equals.go
  internal/ingress/types_equals_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7021 Generate release v0.45
  TAG
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7024 Release helm chart v3.27.0
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7026 Prepare for v0.45.0 release
  Changelog.md
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL, tide/merge-method-squash

#7029 Update the docs to reflect correct release
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#6900 Support existing PSPs in Helm chart
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml
  charts/ingress-nginx/templates/controller-psp.yaml
  charts/ingress-nginx/templates/controller-role.yaml
  charts/ingress-nginx/templates/default-backend-psp.yaml
  charts/ingress-nginx/templates/default-backend-role.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6520 Update the basic auth example
  docs/examples/auth/basic/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7020 [Helm] Add option to specify job label for ServiceMonitor
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7078 Add Exoscale in the documentation
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/exoscale/kustomization.yaml
  docs/deploy/index.md
  hack/generate-deploy-scripts.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#7069 Update catch-all ingress requirement logic
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/store/store.go
  test/e2e/settings/disable_catch_all.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6885 [docs] Documentation for Oracle Cloud Infrastructure integration
  charts/ingress-nginx/README.md
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7081 Proposing myself as an approver temporarily
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7067 Documentation: minikube - ingress-nginx instead of kube-system namespace
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6999 fix(dashboard): use regex for ingress
  deploy/grafana/dashboards/request-handling-performance.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6841 Readme Syntax fix
  docs/examples/customization/custom-configuration/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6914 Update Ingress variable label
  deploy/grafana/dashboards/nginx.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7012 Update the link on ketama
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7088 ci: update kubernetes versions
  .github/workflows/ci.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6895 Update link to moved repo
  docs/user-guide/third-party-addons/modsecurity.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#7075 Change support request template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/support-question.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#6889 NIT: Correct comment re default of server-tokens=false
  internal/ingress/controller/config/config.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#6836 Update GKE internal LB annotations
  charts/ingress-nginx/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6942 [docs]: proxy-real-ip-cidr, mention default and comma-separated behavior
  docs/user-guide/nginx-configuration/configmap.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6879 Make setup instructions for Docker Desktop general
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7092 Remove localhost calls from external names
  .github/workflows/ci.yaml
  internal/ingress/controller/endpoints.go
  internal/ingress/controller/endpoints_test.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/tcp_udp_balancer.lua
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7098 Generate release v0.46
  TAG
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7100 Prep 0.46.0 release
  Changelog.md
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL
