Repository kubernetes/ingress-nginx, pull requests merged in 2021-01, with the labels that each got.

#6708 fix generated code for the new year
  internal/ingress/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6710 Update nginx base image
  Makefile
  images/echo/Makefile
  images/nginx/README.md
  images/nginx/rc.yaml
  images/test-runner/Makefile
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, size/S

#6712 Update tag version
  TAG
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6711 Update test container images
  build/run-in-docker.sh
  test/e2e-image/Dockerfile
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6717 fix ipmatcher installation
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#6718 generalize cidr parsing and improve lua tests
  internal/ingress/annotations/ratelimit/main.go
  internal/ingress/annotations/ratelimit/main_test.go
  internal/net/ipnet.go
  internal/net/ipnet_test.go
  rootfs/etc/nginx/lua/test/balancer/chash_test.lua
  rootfs/etc/nginx/lua/test/run.lua
  rootfs/etc/nginx/lua/test/util_test.lua
Labels: approved, cncf-cla: yes, lgtm, size/L

#6719 Update nginx image
  Makefile
  images/echo/Makefile
  images/nginx/README.md
  images/nginx/rc.yaml
  images/test-runner/Makefile
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6720 Update test runner image
  build/run-in-docker.sh
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6673 Add Global/Distributed Rate Limiting support
  build/test-lua.sh
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/globalratelimit/main.go
  internal/ingress/annotations/globalratelimit/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
  rootfs/etc/nginx/lua/global_throttle.lua
  rootfs/etc/nginx/lua/lua_ingress.lua
  rootfs/etc/nginx/lua/test/global_throttle_test.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/globalratelimit.go
  test/e2e/framework/framework.go
  test/e2e/framework/k8s.go
  test/e2e/settings/globalratelimit.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6723 fix link in annotation docs
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6669 chore: Add test to internal ingress resolver pkg
  internal/ingress/resolver/main_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#6667 Correct the value for setting a static IP
  charts/ingress-nginx/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6724 e2e test for requiring memcached setting to configure global rate limit
  test/e2e/admission/admission.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6727 Fix the documentation for the proxy-ssl-secret and the auth-tls-secret annotations
  docs/user-guide/nginx-configuration/annotations.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6679 Bugfix: fix incomplete log
  rootfs/etc/nginx/lua/tcp_udp_balancer.lua
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6726 add body_filter_by_lua_block lua plugin to ingress-nginx
  rootfs/etc/nginx/lua/plugins/README.md
  rootfs/etc/nginx/template/nginx.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6738 docs/deploy: fix grammar and inconsistencies
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#6741 Update mkdocs, fix nodeport link and add microk8s link
  .github/actions/mkdocs/Dockerfile
  Makefile
  docs/deploy/index.md
  mkdocs.yml
Labels: approved, cncf-cla: yes, size/M

#6730 Do not create HPA if default backend not enabled
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/default-backend-hpa.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6746 Move Azure deploy note to right item on doc page
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6754 Fix KEDA autoscaler resource
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/templates/controller-keda.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6760 Update alpine to 3.13
  docs/examples/customization/sysctl/patch.json
  images/cfssl/rootfs/Dockerfile
  images/httpbin/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, size/S

#6764 Update nginx image
  Makefile
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6761 Adding quotes in the serviceAccount name in Helm values.
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6785 Update kube-webhook-certgen image to v1.5.1
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, size/XS

#6767 Remove ClusterRole when scope option is enabled
  charts/ingress-nginx/templates/clusterrole.yaml
  charts/ingress-nginx/templates/controller-role.yaml
Labels: approved, cncf-cla: yes, size/S

#6787 Update static manifests
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, cncf-cla: yes, size/L

#6786 Release helm chart v3.21.0
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/S

#6789 Update e2e tests link markdown
  docs/e2e-tests.md
Labels: approved, cncf-cla: yes, size/M

#6790 :bug: return error if tempconfig missing
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6796 Updates to the custom default SSL certificate must trigger a reload
  internal/ingress/controller/controller.go
  internal/ingress/sslcert.go
  internal/ingress/types.go
  internal/ingress/types_equals.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#6749 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6756 Dashboard Panel supposed to show average is showing sum.
  deploy/grafana/dashboards/nginx.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5855 New option to set a shutdown grace period
  cmd/nginx/flags.go
  docs/user-guide/cli-arguments.md
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  test/e2e/framework/healthz.go
  test/e2e/gracefulshutdown/grace_period.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#6813 Added docs to clear up PROXY definition
  docs/user-guide/exposing-tcp-udp-services.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6802 Add value for configuring a custom Diffie-Hellman parameters file
  charts/ingress-nginx/templates/controller-configmap.yaml
  charts/ingress-nginx/templates/dh-param-secret.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#6815 Allow use of numeric namespaces in helm chart
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/templates/clusterrolebinding.yaml
  charts/ingress-nginx/templates/controller-prometheusrules.yaml
  charts/ingress-nginx/templates/controller-rolebinding.yaml
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
  charts/ingress-nginx/templates/default-backend-rolebinding.yaml
Labels: approved, cncf-cla: yes, size/S

#6811 add --status-port flag to dbg
  cmd/dbg/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6817 corrected nginx configuration doc path
  charts/ingress-nginx/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6818 Release helm chart v3.22.0
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
Labels: approved, cncf-cla: yes, size/S

#6819 Update kind and kindest images
  .github/workflows/ci.yaml
  TAG
  build/dev-env.sh
  test/e2e/run-chart-test.sh
  test/e2e/run.sh
Labels: approved, cncf-cla: yes, size/S

#6823 Change break link for documentation
  deploy/static/provider/baremetal/kustomization.yaml
  deploy/static/provider/cloud/kustomization.yaml
  deploy/static/provider/do/kustomization.yaml
  deploy/static/provider/kind/kustomization.yaml
  deploy/static/provider/scw/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
