Repository kubernetes/ingress-nginx, pull requests merged in 2021-02, with the labels that each got.

#6830 Remove extra comma for Tracing Jaeger config json
  internal/ingress/controller/nginx.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6839 Prepare release v0.44.0
  TAG
Labels: approved, cncf-cla: yes, size/XS

#6842 Change chart-testing image
  test/e2e/run-chart-test.sh
Labels: approved, cncf-cla: yes, size/XS

#6840 Release helm chart v3.23.0
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, cncf-cla: yes, size/XL

#6843 Release v0.44.0
  Changelog.md
  charts/ingress-nginx/CHANGELOG.md
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, size/M

#6729 aledbf step down from ingress-nginx
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, sig/network, size/XS
