Repository kubernetes/ingress-nginx, pull requests merged in 2021-06, with the labels that each got.

#7189 Update the base nginx image for the 1.20.1 update
  Makefile
  images/nginx/rc.yaml
  images/test-runner/Makefile
  test/e2e/framework/deployment.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7209 Prepare to release v0.47.0
  TAG
  build/run-in-docker.sh
  test/e2e-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash

#7211 Release v0.47.0
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#7210 Prep 0.47.0 release
  Changelog.md
  docs/deploy/index.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7213 update the changlog with links and the release docs to ensure updates…
  Changelog.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7217 the container images didnt get updated
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#7218 fixing wording for #7094
  docs/user-guide/tls.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7221 Update test-runner to go 1.16
  images/test-runner/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7214 update docs with supported version of k8s, alpine and nginx
  README.md
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7216 Admission: Skip validation checks if an ingress is marked as deleted
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7239 Issue #7153: Add note about matching host names in TLS user guide
  docs/user-guide/tls.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6882 helm: add new ingressClass resource
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/controller-ingressclass.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, area/helm, cncf-cla: yes, lgtm, ok-to-test, size/M

#7248 Fix broken get started link in contributing doc
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7256 added namespace field in the namespace scoped resource templates of helm chart
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/ingress-nginx/templates/controller-configmap-addheaders.yaml
  charts/ingress-nginx/templates/controller-configmap-proxyheaders.yaml
  charts/ingress-nginx/templates/controller-configmap-tcp.yaml
  charts/ingress-nginx/templates/controller-configmap-udp.yaml
  charts/ingress-nginx/templates/controller-configmap.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/controller-hpa.yaml
  charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/controller-role.yaml
  charts/ingress-nginx/templates/controller-rolebinding.yaml
  charts/ingress-nginx/templates/controller-service-internal.yaml
  charts/ingress-nginx/templates/controller-service-metrics.yaml
  charts/ingress-nginx/templates/controller-service-webhook.yaml
  charts/ingress-nginx/templates/controller-service.yaml
  charts/ingress-nginx/templates/controller-serviceaccount.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
  charts/ingress-nginx/templates/default-backend-hpa.yaml
  charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/default-backend-role.yaml
  charts/ingress-nginx/templates/default-backend-rolebinding.yaml
  charts/ingress-nginx/templates/default-backend-service.yaml
  charts/ingress-nginx/templates/default-backend-serviceaccount.yaml
Labels: approved, area/helm, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#7255 Fix nilpointer in admission and remove failing test
  internal/ingress/controller/controller.go
  test/e2e/gracefulshutdown/shutdown.go
  test/e2e/gracefulshutdown/slow_requests.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/S

#7258 helm: release helm chart v3.34.0
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: approved, area/helm, cncf-cla: yes, lgtm, size/L

#7273 Prepare for v1.0.0-alpha.1 release
  TAG
Labels: approved, cncf-cla: yes, size/XS

#7274 Update changelog and matrix table for v1.0.0-alpha.1
  Changelog.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#7282 Add strongjz to Owners file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7287 Add tao12345666333 to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7219 add docs for syslog feature
  docs/user-guide/nginx-configuration/configmap.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7201 Fix link to e2e-tests.md in developer-guide
  docs/developer-guide/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7146 Use POD_NAMESPACE ENV expansion for namespace in DaemonSet
  charts/ingress-nginx/templates/controller-daemonset.yaml
Labels: approved, area/helm, cncf-cla: yes, lgtm, ok-to-test, size/S

#7190 chart: using Helm builtin capabilities check
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
Labels: approved, area/helm, cncf-cla: yes, lgtm, size/XS

#6944 Update proper default value for HTTP2MaxConcurrentStreams in Docs
  docs/user-guide/nginx-configuration/configmap.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, ok-to-test, size/XS

#7076 Rewrite clean-nginx-conf.sh in Go to speed up admission webhook
  go.mod
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/Dockerfile
  rootfs/ingress-controller/clean-nginx-conf.sh
  rootfs/ingress-controller/indent.sh
  test/data/cleanConf.expected.conf
  test/data/cleanConf.src.conf
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, priority/important-soon, size/XL, tide/merge-method-squash

#7107 Fix MaxWorkerOpenFiles calculation on high cores nodes
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/nginx.go
  test/e2e/settings/global_options.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7208 ingress/tcp: add additional error logging on failed `dial`
  internal/ingress/controller/tcp.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
