Repository kubernetes/ingress-nginx, pull requests merged in 2021-07, with the labels that each got.

#7307 replacing master with main for k/k8s.io links
  RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7313 Add file containing stable release
  RELEASE.md
  stable.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7314 Add configuration to disable external name service feature
  cmd/nginx/flags.go
  go.mod
  go.sum
  internal/ingress/controller/controller.go
  test/e2e/settings/disable_service_external_name.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7311 Handle named (non-numeric) ports correctly
  cmd/plugin/commands/ingresses/ingresses.go
  cmd/plugin/commands/ingresses/ingresses_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#7308 Updated v1beta1 to v1 as its deprecated
  docs/examples/affinity/cookie/ingress.yaml
  docs/examples/auth/client-certs/ingress.yaml
  docs/examples/customization/configuration-snippets/ingress.yaml
  docs/examples/customization/external-auth-headers/deploy/echo-service.yaml
  docs/examples/grpc/ingress.yaml
  docs/examples/tls-termination/README.md
  docs/user-guide/basic-usage.md
  docs/user-guide/fcgi-services.md
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/third-party-addons/opentracing.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#6990 Use net.Listen func to ensure the port is free
  internal/net/net.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7031 remove mercurial from build
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6940 Fix definition order of modsecurity directives for controller to match PR 5315
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/modsecurity.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/important-soon, size/M, tide/merge-method-squash

#7321 [Cherry Pick] - Add configuration to disable external name service feature (#7314)
  .github/workflows/ci.yaml
  build/run-e2e-suite.sh
  cmd/nginx/flags.go
  go.mod
  go.sum
  internal/ingress/controller/controller.go
  test/e2e/settings/disable_service_external_name.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, size/L

#7322 Rewrite clean-nginx-conf.sh in Go to speed up admission webhook (#7076)
  go.mod
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/Dockerfile
  rootfs/ingress-controller/clean-nginx-conf.sh
  rootfs/ingress-controller/indent.sh
  test/data/cleanConf.expected.conf
  test/data/cleanConf.src.conf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#7323 Fix definition order of modsecurity directives for controller to match PR 5315
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/modsecurity.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7242 Retry to download maxmind DB if it fails
  cmd/nginx/flags.go
  cmd/nginx/flags_test.go
  docs/user-guide/cli-arguments.md
  go.mod
  go.sum
  internal/nginx/maxmind.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7228 fix: discover mounted geoip db files
  cmd/nginx/flags.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/nginx/maxmind.go
  internal/nginx/maxmind_test.go
  test/e2e/settings/geoip2.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7298 Speed up admission hook by eliminating deep copy of Ingresses in CheckIngress
  internal/ingress/controller/location.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7334 Release v1.0.0-alpha.2
  TAG
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7333 [Cherry Pick 7298] Speed up admission hook by eliminating deep copy of Ingresses in CheckIngress
  internal/ingress/controller/location.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7335 Release v0.48
  TAG
Labels: approved, cncf-cla: yes, size/XS

#7336 Add changelog for v1.0.0-alpha.2
  Changelog.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#7339 New v0.48 Release
  TAG
Labels: approved, cncf-cla: yes, size/XS

#7332 controller: ignore non-service backends
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#7331 Fix forwarding of auth-response-headers to gRPC backends
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/auth.go
  test/e2e/annotations/grpc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#7350 update v0.48.1
  Changelog.md
  README.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  stable.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#7351 Update ci main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yaml
  .github/workflows/docs.yaml
  .github/workflows/helm.yaml
  cloudbuild.yaml
  hack/generate-e2e-suite-doc.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#7362 docs - changed basic usage syntax from v1beta1 to v1
  docs/user-guide/basic-usage.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7161 fix: allow scope/tcp/udp configmap namespace to be configured
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: approved, area/helm, cncf-cla: yes, lgtm, ok-to-test, size/S

#7319 Lower webhook timeout for digital ocean
  deploy/static/provider/do/deploy.yaml
  hack/generate-deploy-scripts.sh
Labels: approved, area/helm, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7364 Add cpanato as Helm chart approver
  charts/ingress-nginx/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7039 Add missing tests for store/endpoint
  internal/ingress/controller/store/endpoint_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7365 update OWNERS and aliases files
  OWNERS
  OWNERS_ALIASES
  charts/ingress-nginx/OWNERS
  images/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/M

#7361 prometheus & grafana - fix for usage docs
  deploy/grafana/kustomization.yaml
  deploy/prometheus/kustomization.yaml
  docs/user-guide/monitoring.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7366 update OWNERS and aliases files (#7365)
  OWNERS
  OWNERS_ALIASES
  charts/ingress-nginx/OWNERS
  images/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/M

#7382 fix broken link in synchronization loop pattern
  docs/how-it-works.md
Labels: approved, cncf-cla: yes, lgtm, needs-kind, needs-priority, needs-triage, ok-to-test, size/XS

#7360 grpc - replaced fortune-builder app with official greeter app
  docs/examples/grpc/README.md
  docs/examples/grpc/app.yaml
  docs/examples/grpc/cert.yaml
  docs/examples/grpc/ingress.yaml
  docs/examples/grpc/svc.yaml
  images/go-grpc-greeter-server/Makefile
  images/go-grpc-greeter-server/cloudbuild.yaml
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/grpc-fortune-teller/.gitignore
  images/grpc-fortune-teller/BUILD.bazel
  images/grpc-fortune-teller/Gopkg.lock
  images/grpc-fortune-teller/README.md
  images/grpc-fortune-teller/WORKSPACE
  images/grpc-fortune-teller/app/BUILD.bazel
  images/grpc-fortune-teller/app/main.go
  images/grpc-fortune-teller/go.mod
  images/grpc-fortune-teller/proto/fortune/BUILD.bazel
  images/grpc-fortune-teller/proto/fortune/fortune.proto
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#7355 Downgrade Lua modules for s390x
  images/nginx/rootfs/build.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#7353 aws-load-balancer-internal is a boolean value
  charts/ingress-nginx/README.md
  charts/ingress-nginx/ci/daemonset-internal-lb-values.yaml
  charts/ingress-nginx/ci/deployment-internal-lb-values.yaml
Labels: approved, area/helm, cncf-cla: yes, lgtm, ok-to-test, size/XS

#7224 docs：update troubleshooting.md
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#7394 reorder contributing infos
  README.md
Labels: approved, area/docs, cncf-cla: yes, kind/documentation, lgtm, needs-priority, needs-triage, ok-to-test, size/M

#7385 Update log-format.md
  docs/user-guide/nginx-configuration/log-format.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, needs-priority, ok-to-test, size/XS, triage/accepted

#7404 [Docs] Correct Ingress ServiceName and Service Ports in basic auth example
  docs/examples/auth/basic/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-kind, needs-ok-to-test, needs-priority, needs-triage, size/XS

#7405 update tag to v1.0.0-beta.1
  TAG
Labels: approved, cncf-cla: yes, lgtm, needs-kind, needs-priority, needs-triage, size/XS

#7406 update readme and changelog for v1.0.0-beta.1
  Changelog.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-kind, needs-priority, needs-triage, size/S

#6985 auto backend protocol for HTTP/HTTPS
  internal/ingress/annotations/backendprotocol/main.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  test/e2e/annotations/backendprotocol.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#7371 Enable session affinity for canaries
  build/run-in-docker.sh
  docs/examples/affinity/cookie/README.md
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/sessionaffinity/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  rootfs/etc/nginx/lua/balancer.lua
  rootfs/etc/nginx/lua/balancer/chashsubset.lua
  rootfs/etc/nginx/lua/balancer/ewma.lua
  rootfs/etc/nginx/lua/balancer/resty.lua
  rootfs/etc/nginx/lua/balancer/sticky.lua
  rootfs/etc/nginx/lua/test/balancer/sticky_test.lua
  rootfs/etc/nginx/lua/test/balancer_test.lua
  rootfs/etc/nginx/lua/test/util/split.lua
  rootfs/etc/nginx/lua/test/util/split_test.lua
  rootfs/etc/nginx/lua/util/split.lua
Labels: approved, area/docs, area/lua, cncf-cla: yes, lgtm, ok-to-test, size/XXL
