Repository kubernetes/ingress-nginx, pull requests merged in 2021-10, with the labels that each got.

#7733 Update docs/example/rewrite (sudden stickyingress)
  docs/examples/rewrite/README.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#7735 Add a note to README.md with context on CVE-2021-23017 patch
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#7736 Correct Nginx and Alpine version in legacy branch
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#7734 Docs: fix typo helm value (case sensitive) in the example
  docs/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#7719 fix path overlap check
  internal/ingress/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#7740 Prepare for v1.0.3 release
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#7741 fix overlap check when ingress is configured as canary (#7719)
  internal/ingress/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#7742 Prepare for v0.49.3 release
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#7743 Release v1.0.3
  Changelog.md
  README.md
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  stable.txt
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#7748 Release v0.49.3
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#7751 bump the version to fix the build issues
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  deploy/static/provider/aws/deploy-tls-termination.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, area/helm, needs-priority
