Repository kubernetes/ingress-nginx, pull requests merged in 2022-07, with the labels that each got.

#8765 Bump github/codeql-action from 1.0.26 to 2.1.14
  .github/workflows/scorecards.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8771 fix bullet md format
  docs/developer-guide/code-overview.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, needs-triage, needs-priority

#8365 Update deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  hack/manifest-templates/provider/exoscale/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, approved, ok-to-test, triage/accepted, needs-priority

#8738 Update docs to make it easier for noobs to follow step by step
  docs/user-guide/monitoring.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#8775 Remove stable
  stable.txt
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, priority/backlog, approved, triage/accepted

#8778 chore: remove stable.txt from release process
  RELEASE.md
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#8750 added announcement
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#8793 changed to alpine-v3.16
  docs/examples/customization/sysctl/patch.json
  images/cfssl/rootfs/Dockerfile
  images/httpbin/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/opentelemetry/rootfs/Dockerfile
  rootfs/Dockerfile.chroot
  test/e2e-image/Dockerfile
Labels: cncf-cla: yes, lgtm, area/docs, size/S, kind/feature, priority/critical-urgent, approved, ok-to-test, triage/accepted

#8400 Update nginx base image in one place
  .codecov.yml
  .github/workflows/ci.yaml
  Makefile
  NGINX_BASE
  build/build.sh
  build/run-e2e-suite.sh
  build/run-in-docker.sh
  images/echo/Makefile
  images/nginx/README.md
  images/test-runner/Makefile
  rootfs/Dockerfile
  rootfs/Dockerfile-chroot
  test/e2e-image/Dockerfile
  test/e2e-image/Makefile
  test/e2e/framework/deployment.go
  test/e2e/run-chart-test.sh
  test/e2e/run.sh
  test/test-lua.sh
  test/test.sh
Labels: cncf-cla: yes, lgtm, size/L, kind/feature, priority/backlog, approved, tide/merge-method-squash, triage/accepted

#8733 feat: migrate leaderelection lock to leases
  charts/ingress-nginx/templates/clusterrole.yaml
  charts/ingress-nginx/templates/controller-role.yaml
  internal/ingress/controller/status.go
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, approved, ok-to-test, needs-triage, area/helm, needs-priority, area/stabilization

#8796 fix: add MAC_OS variable for static-check
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8770 Add condition for monitoring.coreos.com/v1 API
  charts/ingress-nginx/templates/controller-prometheusrules.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#8798 Add v1.24.0 to test matrix
  .github/workflows/ci.yaml
  build/run-e2e-suite.sh
  build/run-in-docker.sh
  go.mod
  go.sum
  hack/generate-deploy-scripts.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#8558 Fix example Helm chart values to enable custom http errors
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, kind/bug, priority/backlog, approved, ok-to-test, triage/accepted

#8803 Update to nginx base with alpine v3.16
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8802 chore: start v1.3.0 release process
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8810 Prepare for v1.3.0
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8817 Fixed typo
  docs/user-guide/nginx-configuration/annotations.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8821 fix(docs): describe MetalLB configuration via CRDs rather than configMap
  docs/deploy/baremetal.md
Labels: cncf-cla: yes, lgtm, area/docs, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8827 feat: update mimalloc to 1.7.6
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/S, kind/bug, approved, ok-to-test, needs-triage, needs-priority

#8830 Migrate ginkgo to v2 in e2e-test-runner image
  images/test-runner/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8840 fix: test-runner Makefile
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8838 FIx typo x_forwarded_for
  docs/user-guide/nginx-configuration/configmap.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8807 bumped kubectl in test-runner to v1.24.0
  build/dev-env.sh
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority, area/stabilization

#8829 Decouple shared functions between controllers
  cmd/dataplane/main.go
  cmd/nginx/main.go
  cmd/nginx/main_test.go
  internal/ingress/annotations/auth/main.go
  internal/ingress/controller/checker_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/template/configmap.go
  internal/net/dns/dns_test.go
  internal/net/ssl/ssl.go
  internal/net/ssl/ssl_test.go
  internal/watch/file_watcher_test.go
  pkg/flags/flags.go
  pkg/flags/flags_test.go
  pkg/metrics/handler.go
  pkg/util/file/file.go
  pkg/util/file/file_test.go
  pkg/util/file/filesystem.go
  pkg/util/file/structure.go
  pkg/util/process/controller.go
  pkg/util/process/sigterm.go
  pkg/util/process/sigterm_test.go
  pkg/util/runtime/cpu_linux.go
  pkg/util/runtime/cpu_notlinux.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, kind/cleanup, needs-triage, needs-priority

#8804 added fixes for make dev-env
  Makefile
  build/build.sh
  build/run-in-docker.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority, area/stabilization

#8853 Move utils to better locations to help in decoupling
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/globalratelimit/main.go
  internal/ingress/annotations/ipwhitelist/main.go
  internal/ingress/annotations/ratelimit/main.go
  internal/ingress/controller/nginx.go
  internal/ingress/types_equals.go
  internal/net/ssl/ssl.go
  pkg/tcpproxy/tcp.go
  pkg/util/file/file_watcher.go
  pkg/util/file/file_watcher_test.go
  pkg/util/sets/match.go
  pkg/util/sets/match_test.go
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/critical-urgent, approved, ok-to-test, triage/accepted

#8854 Move APIs to be used by both controller and configurer
  hack/update-codegen.sh
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/endpoints.go
  internal/ingress/controller/endpoints_test.go
  internal/ingress/controller/location.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/controller/store/backend_ssl.go
  internal/ingress/controller/store/ingress.go
  internal/ingress/controller/store/ingress_annotation.go
  internal/ingress/controller/store/local_secret.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/controller/util.go
  internal/ingress/metric/collectors/controller.go
  internal/ingress/metric/collectors/controller_test.go
  internal/ingress/metric/dummy.go
  internal/ingress/metric/main.go
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
  internal/net/ssl/ssl.go
  pkg/apis/ingress/sslcert.go
  pkg/apis/ingress/types.go
  pkg/apis/ingress/types_equals.go
  pkg/apis/ingress/types_equals_test.go
  pkg/apis/ingress/zz_generated.deepcopy.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8855 Add docs on Election ID to Multiple Ingress Controller guide
  docs/index.md
  docs/user-guide/multiple-ingress.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8858 bump to alpine-3.16.1
  docs/examples/customization/sysctl/patch.json
  images/cfssl/rootfs/Dockerfile
  images/httpbin/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/opentelemetry/rootfs/Dockerfile
  rootfs/Dockerfile-chroot
  test/e2e-image/Dockerfile
Labels: cncf-cla: yes, lgtm, area/docs, size/S, kind/bug, approved, needs-triage, needs-priority

#8848 update dd-opentracing-cpp version in nginx build script
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted

#8860 changed baseimage sha & bumped ginkgo to 2.1.4 in test
  NGINX_BASE
  build/run-in-docker.sh
  images/nginx/rc.yaml
  test/e2e/run-chart-test.sh
  test/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#8861 update baseimage after bump of opentracing-cpp
  NGINX_BASE
  images/nginx/rc.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority, area/stabilization

#8863 fix: test-runner prow build
  images/test-runner/Makefile
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#8859 fix: make use of sed portable for BSD and GNU
  hack/generate-deploy-scripts.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-longterm, approved, ok-to-test, needs-triage, area/stabilization

#8864 fix: test-runner prow build
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8865 Revert "fix: test-runner prow build"
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8841 version (commit sha) bump for dependency github.com/moul/pb due to dependency licence
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted

#8869 fix: change cloudbuild configuration
  images/test-runner/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8866 Update gce docs
  Makefile
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/L, priority/backlog, kind/documentation, approved, ok-to-test, triage/accepted

#8870 fix: change all cloudbuild jobs configuration
  images/cfssl/cloudbuild.yaml
  images/custom-error-pages/cloudbuild.yaml
  images/echo/cloudbuild.yaml
  images/ext-auth-example-authsvc/cloudbuild.yaml
  images/fastcgi-helloserver/cloudbuild.yaml
  images/go-grpc-greeter-server/cloudbuild.yaml
  images/httpbin/cloudbuild.yaml
  images/kube-webhook-certgen/cloudbuild.yaml
  images/nginx/cloudbuild.yaml
  images/opentelemetry/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#7892 Add X-Forwarded-For in custom error template
  rootfs/etc/nginx/template/nginx.tmpl
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, priority/important-longterm, approved, lifecycle/stale, ok-to-test, triage/accepted
