Repository kubernetes/ingress-nginx, pull requests merged in 2022-08, with the labels that each got.

#8892 update to baseiamge built after CI changes
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/important-soon, approved, needs-kind, needs-triage

#8896 updated to new images built today
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/1.20/deploy.yaml
  deploy/static/provider/aws/1.21/deploy.yaml
  deploy/static/provider/aws/1.22/deploy.yaml
  deploy/static/provider/aws/1.23/deploy.yaml
  deploy/static/provider/aws/1.24/deploy.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/1.20/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/1.21/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/1.22/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/1.23/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/1.24/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/1.20/deploy.yaml
  deploy/static/provider/baremetal/1.21/deploy.yaml
  deploy/static/provider/baremetal/1.22/deploy.yaml
  deploy/static/provider/baremetal/1.23/deploy.yaml
  deploy/static/provider/baremetal/1.24/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/1.20/deploy.yaml
  deploy/static/provider/cloud/1.21/deploy.yaml
  deploy/static/provider/cloud/1.22/deploy.yaml
  deploy/static/provider/cloud/1.23/deploy.yaml
  deploy/static/provider/cloud/1.24/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/1.20/deploy.yaml
  deploy/static/provider/do/1.21/deploy.yaml
  deploy/static/provider/do/1.22/deploy.yaml
  deploy/static/provider/do/1.23/deploy.yaml
  deploy/static/provider/do/1.24/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/1.20/deploy.yaml
  deploy/static/provider/exoscale/1.21/deploy.yaml
  deploy/static/provider/exoscale/1.22/deploy.yaml
  deploy/static/provider/exoscale/1.23/deploy.yaml
  deploy/static/provider/exoscale/1.24/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/1.20/deploy.yaml
  deploy/static/provider/kind/1.21/deploy.yaml
  deploy/static/provider/kind/1.22/deploy.yaml
  deploy/static/provider/kind/1.23/deploy.yaml
  deploy/static/provider/kind/1.24/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/1.20/deploy.yaml
  deploy/static/provider/scw/1.21/deploy.yaml
  deploy/static/provider/scw/1.22/deploy.yaml
  deploy/static/provider/scw/1.23/deploy.yaml
  deploy/static/provider/scw/1.24/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  test/e2e-image/Makefile
  test/e2e/framework/deployment.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/L, priority/important-soon, approved, needs-kind, needs-triage, area/helm, area/stabilization

#8776 Trivy Image Scanning
  .github/workflows/vulnerability-scans.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted, area/stabilization

#8812 Reimplement kubectl plugin release workflow
  .github/workflows/plugin.yaml
  .goreleaser.yaml
  Makefile
  build/build-plugin.sh
  cmd/plugin/ingress-nginx.yaml.tmpl
  cmd/plugin/krew.yaml
Labels: cncf-cla: yes, lgtm, size/L, priority/important-longterm, approved, kind/cleanup, ok-to-test, needs-triage, area/stabilization, area/release

#8934 bump alpine to v3.16.2
  docs/examples/customization/sysctl/patch.json
  images/cfssl/rootfs/Dockerfile
  images/httpbin/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/opentelemetry/rootfs/Dockerfile
  rootfs/Dockerfile-chroot
  test/e2e-image/Dockerfile
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, needs-triage, needs-priority, area/stabilization

#8939 bump baseimage alpine to v3.16.2 for zlib CVE fix
  NGINX_BASE
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, triage/accepted, needs-priority

#8946 Clean old code and move helper functions
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
  internal/k8s/main.go
  pkg/util/ingress/ingress.go
  pkg/util/ingress/ingress_test.go
  test/e2e/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, needs-kind, needs-triage, needs-priority

#8948 updated testrunner and testecho images
  build/run-in-docker.sh
  docs/examples/customization/external-auth-headers/echo-service.yaml
  test/e2e-image/Makefile
  test/e2e/framework/deployment.go
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, needs-triage, needs-priority

#8881 Don't error log when no OCSP responder URL exists
  rootfs/etc/nginx/lua/certificate.lua
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority, area/lua

#8921 feat: using LeaseLock for election.
  charts/ingress-nginx/templates/controller-role.yaml
  internal/ingress/controller/status.go
  test/e2e/status/update.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, area/helm, needs-priority

#8928 Add NetworkPolicy support
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-wehbooks-networkpolicy.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/S, kind/feature, priority/important-longterm, approved, ok-to-test, needs-triage, area/helm

#8930 securityContext in admission-webhook now configurable e.g. to set seccompProfiles
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#8873 Document internal-logger-address cli arg
  docs/user-guide/cli-arguments.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#8665 Add protocol prefix to Metrics port (Helm)
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/controller-service-metrics.yaml
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#8905 fix(controller): typo in catch-all CheckIngress error message
  internal/ingress/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/backlog, approved, ok-to-test, triage/accepted

#8825 Fix defaultServer backend update for Ingress with defaultBackend.
  internal/ingress/controller/controller.go
  test/e2e/ingress/without_host.go
Labels: cncf-cla: yes, lgtm, size/S, kind/bug, approved, ok-to-test, needs-triage, needs-priority

#8944 Make keep-alive documentation more explicit for clarity
  docs/user-guide/nginx-configuration/configmap.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, priority/important-longterm, kind/documentation, approved, needs-triage

#8959 revert changes to configmap resource permissions
  build/run-in-docker.sh
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-role.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, area/helm, needs-priority

#8960 upgrade yamale and yamllint version
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8967 updated to testrunnerimage with updated yamle yamllint
  build/run-in-docker.sh
  test/e2e-image/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, triage/accepted, needs-priority, area/stabilization

#8969 fix: go-restful CVE #8745
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/L, kind/bug, priority/important-soon, approved, ok-to-test, area/dependency, needs-triage

#8966 added note on digitalocean annotations
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, kind/documentation, approved, needs-triage, needs-priority

#8916 adding cve finding and adding release-notes to PR template
  .github/ISSUE_TEMPLATE/cve_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, approved, triage/accepted, area/stabilization

#8976 Update apiserver to 0.25 to remove v2 go-restful
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/important-soon, approved, ok-to-test, needs-triage, area/security

#8970 bump Golang to 1.19 #8932
  .github/workflows/ci.yaml
  .github/workflows/plugin.yaml
  go.mod
  images/custom-error-pages/rootfs/Dockerfile
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/go.mod
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/important-longterm, approved, ok-to-test, triage/accepted, area/security

#8984 fixed deprecated ginkgo flags
  test/e2e-image/e2e.sh
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, triage/accepted, needs-priority, area/stabilization
