Repository kubernetes/ingress-nginx, pull requests merged in 2022-02, with the labels that each got.

#7829 Fix Helm Chart remove Capabilities.APIVersions for Kustomize to parse file
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-longterm, approved, ok-to-test, triage/accepted, area/helm

#8199 use functional options to reduce number of methods creating an EchoDeployment
  test/e2e/annotations/affinity.go
  test/e2e/annotations/affinitymode.go
  test/e2e/annotations/authtls.go
  test/e2e/annotations/canary.go
  test/e2e/annotations/cors.go
  test/e2e/annotations/customhttperrors.go
  test/e2e/annotations/proxyssl.go
  test/e2e/annotations/upstreamhashby.go
  test/e2e/framework/deployment.go
  test/e2e/ingress/multiple_rules.go
  test/e2e/loadbalance/ewma.go
  test/e2e/loadbalance/round_robin.go
  test/e2e/lua/dynamic_configuration.go
  test/e2e/settings/default_ssl_certificate.go
  test/e2e/settings/disable_catch_all.go
  test/e2e/settings/disable_service_external_name.go
  test/e2e/settings/ingress_class.go
  test/e2e/settings/namespace_selector.go
  test/e2e/status/update.go
  test/e2e/tcpudp/tcp.go
Labels: cncf-cla: yes, lgtm, size/L, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted

#8218 8217 fix removed extra v
  cmd/plugin/ingress-nginx.yaml.tmpl
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8163 Update the $req_id placeholder description
  docs/user-guide/nginx-configuration/log-format.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/important-soon, kind/documentation, approved, ok-to-test, triage/accepted

#8136 add ingressClass option to helm chart - back compatibility with ingress.class annotations
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/_params.tpl
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#8221 Do not validate ingresses with unknown ingress class in admission webhook endpoint
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/store/store.go
  test/e2e/admission/admission.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, needs-priority

#8227 Update libraries in webhook image
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, needs-priority

#8186 prometheus+grafana using servicemonitor
  docs/images/grafana-dashboard1.png
  docs/images/prometheus-dashboard1.png
  docs/user-guide/monitoring.md
Labels: cncf-cla: yes, lgtm, area/docs, size/L, needs-ok-to-test, priority/important-soon, kind/documentation, approved, triage/accepted

#8159 Adding some geoip variables and default values
  rootfs/etc/nginx/template/nginx.tmpl
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8236 webhook: remove useless code.
  internal/admission/controller/main.go
  internal/ingress/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8225 fix inconsistent-label-cardinality for prometheus metrics: nginx_ingress_controller_requests
  internal/ingress/metric/collectors/socket.go
  internal/ingress/metric/collectors/socket_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8185 Append elements on match, instead of removing for cors-annotations
  internal/ingress/annotations/cors/main.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-soon, approved, ok-to-test, triage/accepted

#8258 remove 0.46.0 from supported versions table
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, priority/important-soon, kind/documentation, approved, triage/accepted

#8244 Minor fix for missing pathType property
  charts/ingress-nginx/templates/NOTES.txt
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#8262 Updated confusing error
  docs/user-guide/monitoring.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#8253 Add a certificate info metric
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
  internal/ingress/metric/collectors/controller.go
  internal/ingress/metric/collectors/controller_test.go
  internal/ingress/metric/dummy.go
  internal/ingress/metric/main.go
  internal/ingress/sslcert.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8273 Issue#8241
  docs/user-guide/monitoring.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#8275 Start Release process for v1.1.2
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#8267 Add fsGroup value to admission-webhooks/job-patch charts
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-longterm, approved, ok-to-test, triage/accepted, area/helm
