Repository kubernetes/ingress-nginx, pull requests merged in 2022-11, with the labels that each got.

#9245 fix svc long name
  internal/ingress/controller/store/endpointslice.go
  internal/ingress/controller/store/endpointslice_test.go
  test/e2e/e2e.go
  test/e2e/endpointslices/longname.go
  test/e2e/framework/deployment.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9257 update base image of nginx to 1.21.6
  .github/workflows/ci.yaml
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/S, kind/feature, priority/backlog, approved, triage/accepted

#9258 Fix CVE-2022-32149
  go.sum
  images/ext-auth-example-authsvc/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#9244 Fix CVE-2022-1996
  go.mod
  go.sum
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/S, kind/bug, priority/backlog, approved, ok-to-test, triage/accepted

#9271 start 1.5.0 release
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, priority/critical-urgent, approved, triage/accepted

#9273 fix CVE-2022-27664
  go.sum
  images/ext-auth-example-authsvc/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, size/L, needs-ok-to-test, needs-kind, needs-triage, needs-priority

#9275 Add CVE-2022-27664 #9273 in latest release
  TAG
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#9280 Release 1.5.1
  .github/workflows/ci.yaml
  Changelog.md
  README.md
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#9242 add containerSecurityContext to extraModules init containers
  charts/ingress-nginx/README.md
  charts/ingress-nginx/ci/deployment-extra-modules-default-container-sec-context.yaml
  charts/ingress-nginx/ci/deployment-extra-modules-specific-container-sec-context.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#9278 PDB: Add `maxUnavailable`.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#9243 fix broken annotation yaml
  charts/ingress-nginx/templates/controller-serviceaccount.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#9290 run helm release on main only and when the chart/value changes only
  .github/workflows/helm.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, priority/backlog, approved, triage/accepted

#9225 Fixed indentation in commented-out autoscaling
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#9286 OpenTelemetry static linking
  images/opentelemetry/rootfs/CMakeLists.txt
  images/opentelemetry/rootfs/Dockerfile
  images/opentelemetry/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted

#9304 Missing controller.ingressClass in the documentation
  docs/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9295 added SAN to cert create command
  docs/user-guide/tls.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, kind/documentation, approved, triage/accepted, needs-priority

#9309 Validate ingress path fields
  internal/ingress/controller/store/store.go
  pkg/util/ingress/ingress.go
  pkg/util/ingress/ingress_test.go
  test/e2e/security/invalid_paths.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, needs-priority

#9277 fix(sec): upgrade gopkg.in/yaml.v3 to 3.0.0
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted

#9284 remove hardcoded datasource from grafana dashboard
  deploy/grafana/dashboards/nginx.json
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9310 remove the configmap related permissions
  charts/ingress-nginx/templates/controller-role.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#9336 fixed multiple ginkgo versions
  build/run-in-docker.sh
  images/test-runner/rootfs/Dockerfile
  test/e2e/run-chart-test.sh
  test/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, triage/accepted, needs-priority, area/stabilization

#9339 create nsswitch-conf only if missing
  images/test-runner/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, triage/accepted, needs-priority, area/stabilization

#9340 updated testrunner image sha to new image with ginkgo bumped to v2.5.1
  build/run-in-docker.sh
  test/e2e-image/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, triage/accepted, needs-priority

#9353 Fix typos found by codespell
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/README.md
  charts/ingress-nginx/README.md.gotmpl
Labels: cncf-cla: yes, lgtm, size/S, priority/important-soon, approved, kind/cleanup, ok-to-test, triage/accepted, area/helm
