Repository kubernetes/ingress-nginx, pull requests merged in 2022-10, with the labels that each got.

#9113 fixed broken helm version comparision
  build/dev-env.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, triage/accepted, needs-priority, area/stabilization

#9108 Release 1.4.0
  .github/workflows/ci.yaml
  Changelog.md
  README.md
  charts/ingress-nginx/CHANGELOG.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#9117 chore Fixed to Support Versions table
  Changelog.md
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9120 Updated incorrect version number in the Installation Guide
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9114 Updated the Developer guide with New Contributor information
  docs/developer-guide/getting-started.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9110 Remove deprecated net dependency
  TAG
  go.mod
  test/e2e/annotations/grpc.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9121 Fixed docs helm-docs version
  RELEASE.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9109 Fix CVE 2022 27664
  .github/workflows/ci.yaml
  .github/workflows/perftest.yaml
  TAG
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, needs-triage, area/helm, needs-priority

#9123 Rename controller-wehbooks-networkpolicy.yaml.
  charts/ingress-nginx/templates/controller-webhooks-networkpolicy.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#9124 upgrade to golang 1.19.2
  .github/workflows/ci.yaml
  .github/workflows/plugin.yaml
  Makefile
  build/dev-env.sh
  build/kind.yaml
  build/run-in-docker.sh
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/Dockerfile
  images/test-runner/Makefile
  test/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, needs-priority

#9103 fix e2e resource leak when ginkgo exit before clear resource
  test/e2e/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9131 fix: handle 401 and 403 by external auth
  rootfs/etc/nginx/template/nginx.tmpl
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9150 Move bowei to emeritus owner
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9149 fix null ports
  internal/ingress/controller/endpointslices.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9133 #7652 - Updated Helm chart to use the fullname for the electionID if not specified.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/_params.tpl
  charts/ingress-nginx/templates/controller-role.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/S, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#9098 Documentation added for implemented redirection in the proxy to ensure image pulling
  docs/troubleshooting.md
Labels: cncf-cla: yes, lgtm, area/docs, size/M, needs-ok-to-test, approved, needs-kind, tide/merge-method-squash, needs-triage, needs-priority

#9158 updating runner with golang 1.19.2
  build/run-in-docker.sh
  test/e2e-image/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted

#9172 GitHub Templates: Remove trailing whitespaces.
  .github/ISSUE_TEMPLATE/cve_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9147 Update helm chart changelog to show that kubernetes v1.21.x is no longer supported
  charts/ingress-nginx/CHANGELOG.md
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#9185 Add section to troubleshooting docs for failure to listen on port
  docs/troubleshooting.md
Labels: cncf-cla: yes, lgtm, area/docs, size/L, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#9189 start 1.4.1 release
  TAG
Labels: lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9195 Implement parseFloat for annotations
  internal/ingress/annotations/parser/main.go
  internal/ingress/annotations/parser/main_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9167 fix typo in docs.
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9186 add:(admission-webhooks) ability to set securityContext
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/S, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted, area/helm

#9210 Fix Markdown header level
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#8889 chore: bump NGINX version v1.21.4
  images/nginx/rootfs/build.sh
  images/nginx/rootfs/patches/nginx-1.19.9-no_Werror.patch
  images/nginx/rootfs/patches/nginx-1.21.4-balancer_status_code.patch
  images/nginx/rootfs/patches/nginx-1.21.4-cache_manager_exit.patch
  images/nginx/rootfs/patches/nginx-1.21.4-delayed_posted_events.patch
  images/nginx/rootfs/patches/nginx-1.21.4-hash_overflow.patch
  images/nginx/rootfs/patches/nginx-1.21.4-init_cycle_pool_release.patch
  images/nginx/rootfs/patches/nginx-1.21.4-larger_max_error_str.patch
  images/nginx/rootfs/patches/nginx-1.21.4-no_Werror.patch
  images/nginx/rootfs/patches/nginx-1.21.4-proxy_host_port_vars.patch
  images/nginx/rootfs/patches/nginx-1.21.4-resolver_conf_parsing.patch
  images/nginx/rootfs/patches/nginx-1.21.4-reuseport_close_unused_fds.patch
  images/nginx/rootfs/patches/nginx-1.21.4-single_process_graceful_exit.patch
  images/nginx/rootfs/patches/nginx-1.21.4-socket_cloexec.patch
  images/nginx/rootfs/patches/nginx-1.21.4-ssl_cert_cb_yield.patch
  images/nginx/rootfs/patches/nginx-1.21.4-ssl_sess_cb_yield.patch
  images/nginx/rootfs/patches/nginx-1.21.4-stream_proxy_get_next_upstream_tries.patch
  images/nginx/rootfs/patches/nginx-1.21.4-stream_ssl_preread_no_skip.patch
  images/nginx/rootfs/patches/nginx-1.21.4-upstream_pipelining.patch
  images/nginx/rootfs/patches/nginx-1.21.4-upstream_timeout_fields.patch
  images/nginx/rootfs/patches/patch.2021.resolver.txt
Labels: cncf-cla: yes, lgtm, size/L, kind/feature, priority/important-soon, approved, ok-to-test, triage/accepted

#9231 chore: update NGINX to 1.21.6
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority
