Repository kubernetes/ingress-nginx, pull requests merged in 2022-12, with the labels that each got.

#9350 added ginkgo junit reports
  build/run-e2e-suite.sh
  test/e2e-image/e2e.sh
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/important-soon, approved, triage/accepted, area/stabilization

#9357 removed deprecation messsage for ingressClass annotation
  docs/user-guide/multiple-ingress.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9346 fix(typo): pluralize provider
  docs/user-guide/basic-usage.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9348 fix(hpa): deprecated api version, bump to v2
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-hpa.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#9311 Enable profiler-address to be configured
  cmd/dataplane/main.go
  cmd/nginx/main.go
  internal/nginx/main.go
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9365 resolved ginkgo deprecation message
  go.mod
  go.sum
  test/e2e-image/e2e.sh
Labels: cncf-cla: yes, lgtm, size/M, priority/important-soon, approved, needs-kind, ok-to-test, triage/accepted, area/stabilization

#9251 fix: missing CORS headers when auth fails
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/auth.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9308 update OpenTelemetry image
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted, area/helm

#9372 [user-guide configmap] fix doc for global-auth-snippet
  docs/user-guide/nginx-configuration/configmap.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9361 integrated junit-reports with ghactions-part1-of-2
  .github/workflows/ci.yaml
  .github/workflows/junit-reports.yaml
  build/run-e2e-suite.sh
Labels: cncf-cla: yes, lgtm, size/S, priority/important-soon, approved, needs-kind, triage/accepted, area/stabilization

#9279 feat(helm): Optionally use cert-manager instead admission patch
  charts/ingress-nginx/README.md
  charts/ingress-nginx/README.md.gotmpl
  charts/ingress-nginx/ci/controller-admission-tls-cert-manager-values.yaml
  charts/ingress-nginx/templates/admission-webhooks/cert-manager.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#9381 doc: update NEW_CONTRIBUTOR.md
  NEW_CONTRIBUTOR.md
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, kind/documentation, approved, needs-triage, needs-priority

#9386 Add action for issues to project
  .github/workflows/project.yml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#9395 Add reporter for all tests
  .github/workflows/ci.yaml
  .github/workflows/junit-reports.yaml
Labels: cncf-cla: yes, lgtm, size/S, kind/feature, priority/backlog, approved, triage/accepted

#9401 ci: remove setup-kind step
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#9404 ci: remove setup-helm step
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#9408 Bump github.com/onsi/ginkgo/v2 from 2.5.1 to 2.6.0
  build/run-in-docker.sh
  images/test-runner/rootfs/Dockerfile
  test/e2e/run-chart-test.sh
  test/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9417 start upgrade to golang 1.19.4 and alpine 3.17.0
  .github/workflows/ci.yaml
  .github/workflows/plugin.yaml
  docs/examples/customization/sysctl/patch.json
  images/cfssl/rootfs/Dockerfile
  images/custom-error-pages/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/main.go
  images/httpbin/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/opentelemetry/rootfs/Dockerfile
  images/test-runner/Makefile
  images/test-runner/rootfs/Dockerfile
  rootfs/Dockerfile-chroot
Labels: cncf-cla: yes, lgtm, area/docs, size/L, kind/feature, priority/important-soon, approved, triage/accepted

#9429 Increase build time out for fastcgi gcloud image build
  images/fastcgi-helloserver/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#9428 patch otel docker file
  images/opentelemetry/rootfs/Dockerfile
Labels: cncf-cla: yes, size/XS, kind/bug, priority/backlog, approved, triage/accepted

#9427 cleanup: remove ioutil for new go version
  images/kube-webhook-certgen/rootfs/pkg/certs/certs_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/cleanup, needs-triage, needs-priority

#9430 update the nginx run container for alpine:3.17.0
  images/nginx/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9432 Bump github.com/onsi/ginkgo/v2 from 2.6.0 to 2.6.1
  build/run-in-docker.sh
  images/test-runner/rootfs/Dockerfile
  test/e2e/run-chart-test.sh
  test/e2e/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9253 HPA: Add `controller.autoscaling.annotations` to `values.yaml`.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#9434 force rebuild for curl cve
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#9440 CI updates
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/depreview.yaml
  .github/workflows/docs.yaml
  .github/workflows/helm.yaml
  .github/workflows/junit-reports.yaml
  .github/workflows/perftest.yaml
  .github/workflows/plugin.yaml
  .github/workflows/project.yml
  .github/workflows/scorecards.yml
  .github/workflows/vulnerability-scans.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, kind/cleanup, needs-triage, needs-priority

#9392 avoid builds and tests for non-code changes
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9444 test the new e2e test images
  build/run-in-docker.sh
  test/e2e-image/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9436 upgrade nginx base image
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9445 start release 1.5.2
  .github/workflows/ci.yaml
  TAG
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#9446 Update cloud build time out
  cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9224 Update command line arguments documentation
  docs/user-guide/cli-arguments.md
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, area/docs, size/M, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#9450 restart 1.5.2 release process
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9456 updated the link in RELEASE.md file
  RELEASE.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, kind/documentation, approved, ok-to-test, needs-triage, needs-priority

#9457 Add sslpassthrough tests
  build/build.sh
  build/run-in-docker.sh
  pkg/tcpproxy/tcp.go
  test/e2e/framework/deployment.go
  test/e2e/framework/httpexpect/request.go
  test/e2e/settings/ssl_passthrough.go
Labels: cncf-cla: yes, lgtm, size/L, kind/bug, priority/important-longterm, approved, triage/accepted

#9455 Automated Release controller-v1.5.2
  Changelog.md
  README.md
  changelog/Changelog-1.5.2.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog.md.gotmpl
  charts/ingress-nginx/changelog/Changelog-1.5.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
  hack/generate-e2e-suite-doc.sh
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, kind/feature, priority/backlog, approved, triage/accepted, area/helm

#9461 move tests to gh actions
  .github/workflows/ci.yaml
  Makefile
  internal/ingress/annotations/authreq/main.go
  internal/ingress/controller/template/template.go
  internal/ingress/resolver/mock.go
  pkg/util/runtime/cpu_linux.go
  rootfs/chroot.sh
  test/e2e/framework/util.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, needs-priority

#9463 Update changelog image paths for 1.5.2
  changelog/Changelog-1.5.2.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9469 Rollback 1.5.2
  TAG
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-1.5.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, approved, needs-kind, needs-triage, area/helm, needs-priority
