Repository kubernetes/ingress-nginx, pull requests merged in 2023-06, with the labels that each got.

#10021 added note on dns for localtesting
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, needs-triage, needs-priority

#10016 Upgrade to Golang 1.20.4
  images/custom-error-pages/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/test-runner/Makefile
  images/test-runner/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, tide/merge-method-squash, ok-to-test, needs-triage, needs-priority

#10028 chore(dep): upgrade github.com/emicklei/go-restful/v3 to 3.10
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10034 Fix typo in controller_test
  internal/ingress/controller/controller_test.go
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10054 docs: Updated the content of deploy/rbac.md
  docs/deploy/rbac.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, kind/documentation, approved, triage/accepted, needs-priority

#10055 Update broken links to k8s documentation in project
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  docs/index.md
  docs/troubleshooting.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, ok-to-test, triage/accepted, area/helm, needs-priority

#10062 Update Internal Load Balancer docs
  charts/ingress-nginx/README.md
  charts/ingress-nginx/README.md.gotmpl
Labels: cncf-cla: yes, lgtm, size/S, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10067 docs: canary weighted deployments example
  docs/examples/canary/README.md
  docs/examples/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10060 docs: add lua testing documentation
  docs/lua_tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, needs-triage, needs-priority

#10068 fix: add canary to sidebar in examples
  mkdocs.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10031 tracing: upgrade to dd-opentracing-cpp v1.3.7
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10048 chore: pkg imported more than once
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/store/store.go
  internal/net/ssl/ssl_test.go
  test/e2e/annotations/grpc.go
  test/e2e/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10049 unnecessary use of fmt.Sprint (S1039)
  internal/ingress/controller/checker_test.go
  test/e2e/annotations/connection.go
  test/e2e/framework/framework.go
  test/e2e/settings/enable_real_ip.go
  test/e2e/settings/forwarded_headers.go
  test/e2e/settings/keep-alive.go
  test/e2e/settings/listen_nondefault_ports.go
  test/e2e/settings/no_tls_redirect_locations.go
  test/e2e/settings/proxy_host.go
  test/e2e/settings/proxy_protocol.go
  test/e2e/settings/tls.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9993 Support for keda fallback settings
  charts/ingress-nginx/templates/controller-keda.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#9961 Adding feature to upgrade Oracle Cloud Infrastructure's Flexible Load Balancer and adjusting Health Check that were critical in the previous configuration
  deploy/static/provider/oci/deploy.yaml
  deploy/static/provider/oci/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved, needs-kind, ok-to-test, triage/accepted, needs-priority

#9889 Fix mirror-target values without path separator and port
  internal/ingress/annotations/mirror/main.go
  internal/ingress/annotations/mirror/main_test.go
  internal/ingress/controller/template/template.go
  test/e2e/annotations/mirror.go
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, approved, ok-to-test, needs-triage, needs-priority

#9864 Remove fastcgi feature
  .github/workflows/ci.yaml
  MANUAL_RELEASE.md
  docs/e2e-tests.md
  docs/kubectl-plugin.md
  docs/user-guide/fcgi-services.md
  docs/user-guide/nginx-configuration/annotations.md
  images/fastcgi-helloserver/Makefile
  images/fastcgi-helloserver/cloudbuild.yaml
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/fastcgi-helloserver/rootfs/main.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/backendprotocol/main.go
  internal/ingress/annotations/fastcgi/main.go
  internal/ingress/annotations/fastcgi/main_test.go
  internal/ingress/annotations/parser/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  pkg/apis/ingress/types.go
  pkg/apis/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/backendprotocol.go
  test/e2e/annotations/fastcgi.go
  test/e2e/framework/fastcgi_helloserver.go
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, approved, kind/cleanup, needs-triage, needs-priority

#9955 chore: move httpbun to be part of E2E framework
  test/e2e/HTTPBUN_IMAGE
  test/e2e/annotations/auth.go
  test/e2e/annotations/grpc.go
  test/e2e/annotations/satisfy.go
  test/e2e/framework/deployment.go
  test/e2e/framework/framework.go
  test/e2e/run-e2e-suite.sh
  test/e2e/servicebackend/service_externalname.go
  test/e2e/settings/brotli.go
  test/e2e/settings/disable_service_external_name.go
  test/e2e/settings/global_external_auth.go
  test/e2e/settings/listen_nondefault_ports.go
  test/e2e/settings/ssl_passthrough.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10035 add distroless otel init
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/controller-deployment.yaml
  images/opentelemetry/rootfs/Dockerfile
  images/opentelemetry/rootfs/build.sh
  images/opentelemetry/rootfs/go.mod
  images/opentelemetry/rootfs/init_module.go
  images/opentelemetry/rootfs/init_module.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, area/helm, needs-priority

#10073 docs: add netlify configuration
  Makefile
  netlify.toml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#10081 Revert "Remove fastcgi feature"
  .github/workflows/ci.yaml
  MANUAL_RELEASE.md
  docs/e2e-tests.md
  docs/kubectl-plugin.md
  docs/user-guide/fcgi-services.md
  docs/user-guide/nginx-configuration/annotations.md
  images/fastcgi-helloserver/Makefile
  images/fastcgi-helloserver/cloudbuild.yaml
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/fastcgi-helloserver/rootfs/main.go
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/backendprotocol/main.go
  internal/ingress/annotations/fastcgi/main.go
  internal/ingress/annotations/fastcgi/main_test.go
  internal/ingress/annotations/parser/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  pkg/apis/ingress/types.go
  pkg/apis/ingress/types_equals.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/backendprotocol.go
  test/e2e/annotations/fastcgi.go
  test/e2e/framework/fastcgi_helloserver.go
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, approved, needs-kind, needs-triage, needs-priority

#10087 docs: change Dockefile url ref main
  docs/examples/grpc/README.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10029 fix: remove default usage of obsolete nginx directives without explictly being set
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: cncf-cla: yes, lgtm, area/docs, size/L, approved, needs-kind, needs-triage, needs-priority

#10089 chore: remove echo friom canary tests
  test/e2e/annotations/canary.go
  test/e2e/framework/deployment.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, needs-kind, needs-triage, needs-priority

#9562 feat(helm): Add loadBalancerClass
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-service.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10120 Golang 1.20.5
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10117 Update typo in docs for lb scheme
  charts/ingress-nginx/README.md
  charts/ingress-nginx/README.md.gotmpl
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10110 chore: remove echo from snippet tests
  test/e2e/annotations/snippet.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, needs-priority

#10123 trigger release test
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10124 add gcloud ignore
  .gcloudignore
  images/test-runner/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10125 update test runner
  build/run-in-docker.sh
  test/e2e-image/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10126 rebuild nginx base container image
  TAG
  images/nginx/TAG
  images/nginx/cloudbuild.yaml
Labels: cncf-cla: yes, size/S, approved, needs-kind, needs-triage, needs-priority

#10127 bump pinned golang to 1.20.5
  images/custom-error-pages/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/httpbun/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/S, priority/important-soon, approved, needs-kind, triage/accepted

#8912 Set grpc :authority header from request header
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/grpc.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9406 Added a doc line to the missing helm value service.internal.loadBalancerIP
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, triage/needs-information, needs-kind, needs-triage, area/helm, needs-priority

#10139 Helm - Fix loadBalancerClass value syntax
  charts/ingress-nginx/templates/controller-service.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10144 netlify: Only trigger preview when there are changes in docs.
  netlify.toml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10148 Cut release v1.8.1
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved

#10156 Fix OCI manifest templates and regenerate the deploy files
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/oracle/kustomization.yaml
  hack/manifest-templates/provider/oracle/kustomization.yaml
  hack/manifest-templates/provider/oracle/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10161 release notes 1.8.1
  README.md
  changelog/Changelog-1.8.1.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.7.1.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority
