Repository kubernetes/ingress-nginx, pull requests merged in 2023-07, with the labels that each got.

#10158 Deprecate and remove AJP support
  docs/e2e-tests.md
  docs/user-guide/nginx-configuration/annotations.md
  images/nginx/rootfs/build.sh
  internal/ingress/annotations/backendprotocol/main.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/backendprotocol.go
Labels: cncf-cla: yes, lgtm, area/docs, size/M, approved, kind/deprecation, needs-triage, needs-priority

#10128 Fix golang-ci linter errors
  cmd/dataplane/main.go
  cmd/nginx/main.go
  cmd/plugin/commands/certs/certs.go
  cmd/plugin/kubectl/kubectl.go
  images/fastcgi-helloserver/rootfs/main.go
  images/kube-webhook-certgen/rootfs/pkg/k8s/k8s_test.go
  internal/admission/controller/main_test.go
  internal/admission/controller/server.go
  internal/ingress/controller/checker_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/nginx.go
  internal/ingress/controller/store/endpointslice_test.go
  internal/ingress/controller/store/store.go
  internal/ingress/controller/store/store_test.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  internal/ingress/metric/collectors/process_test.go
  internal/ingress/metric/collectors/socket_test.go
  internal/ingress/status/status.go
  internal/ingress/status/status_test.go
  internal/net/dns/dns_test.go
  internal/net/ssl/ssl.go
  internal/net/ssl/ssl_test.go
  pkg/flags/flags.go
  pkg/tcpproxy/tcp.go
  pkg/util/file/file_test.go
  pkg/util/file/file_watcher_test.go
  pkg/util/process/sigterm_test.go
  test/e2e/annotations/affinitymode.go
  test/e2e/endpointslices/topology.go
  test/e2e/framework/deployment.go
  test/e2e/framework/httpexpect/chain.go
  test/e2e/security/request_smuggling.go
  test/e2e/settings/proxy_protocol.go
  test/e2e/ssl/secret_update.go
  test/e2e/status/update.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10166 Cleanup errcheck code in test/e2e pkg
  test/e2e/endpointslices/topology.go
  test/e2e/settings/proxy_protocol.go
  test/e2e/ssl/secret_update.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10157 Expose continent data as geoip2 variables in the case of Maxmind city files
  rootfs/etc/nginx/template/nginx.tmpl
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10146 Clarify TCP/UDP service docs
  docs/user-guide/exposing-tcp-udp-services.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10151 revise Datadog trace sampling configuration
  internal/ingress/controller/config/config.go
  internal/ingress/controller/nginx.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9815 Scanning port 10247 lead to tcp connection 502 error
  rootfs/etc/nginx/lua/tcp_udp_configuration.lua
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority, area/lua

#10219 chore: bump OpenResty to v1.21.4.2
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted

#9534 Ignore deployment template's replicas if KEDA is enabled
  charts/ingress-nginx/templates/controller-deployment.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10084 [helm] pass service annotations through helm tpl engine
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-service-internal.yaml
  charts/ingress-nginx/templates/controller-service.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/S, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10230 Golang 1.20.6 for test runner
  images/cfssl/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/opentelemetry/rootfs/Dockerfile
  images/test-runner/Makefile
  rootfs/Dockerfile-chroot
  test/e2e-image/Dockerfile
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#10232 Fix images tags
  images/cfssl/Makefile
  images/cfssl/cloudbuild.yaml
  images/custom-error-pages/cloudbuild.yaml
  images/echo/cloudbuild.yaml
  images/ext-auth-example-authsvc/Makefile
  images/ext-auth-example-authsvc/cloudbuild.yaml
  images/fastcgi-helloserver/cloudbuild.yaml
  images/go-grpc-greeter-server/cloudbuild.yaml
  images/httpbun/cloudbuild.yaml
  images/kube-webhook-certgen/cloudbuild.yaml
  images/opentelemetry/cloudbuild.yaml
Labels: cncf-cla: yes, size/M, approved, needs-kind, needs-triage, needs-priority

#10235 fix NGINX deps sha256sum
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#10129 Add rolling update strategy to each static deployment file
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  hack/manifest-templates/provider/aws/nlb-with-tls-termination/values.yaml
  hack/manifest-templates/provider/aws/values.yaml
  hack/manifest-templates/provider/baremetal/values.yaml
  hack/manifest-templates/provider/cloud/values.yaml
  hack/manifest-templates/provider/do/values.yaml
  hack/manifest-templates/provider/exoscale/values.yaml
  hack/manifest-templates/provider/oracle/values.yaml
  hack/manifest-templates/provider/scw/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, tide/merge-method-squash, ok-to-test, needs-triage, needs-priority

#10180 [helm] configure allow to configure hostAliases
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority
