Repository kubernetes/ingress-nginx, pull requests merged in 2023-12, with the labels that each got.

#10673 Add extra configMaps support to helm chart
  .github/workflows/ci.yaml
  .gitignore
  charts/ingress-nginx/.helmignore
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/default-backend-extra-configmaps.yaml
  charts/ingress-nginx/tests/default-backend-extra-configmaps_test.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, kind/feature, approved, ok-to-test, needs-triage, area/helm, needs-priority

#10727 add new serivce type for internal use
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-service-internal.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10239 Helm Service: Align internal to external.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-service-internal.yaml
  charts/ingress-nginx/templates/controller-service.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, kind/feature, priority/backlog, needs-ok-to-test, approved, triage/accepted, area/helm

#10722 images: upgrade to Alpine 3.18.5
  images/cfssl/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/opentelemetry/rootfs/Dockerfile
  rootfs/Dockerfile-chroot
  test/e2e-image/Dockerfile
Labels: cncf-cla: yes, lgtm, size/S, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10732 upgrade go 1.21.5
  .github/workflows/ci.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/plugin.yaml
  go.mod
  go.work
  go.work.sum
  images/custom-error-pages/rootfs/Dockerfile
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/httpbun/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/go.mod
  images/nginx/TAG
  images/opentelemetry/rootfs/go.mod
  images/test-runner/Makefile
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/parser/validators.go
  magefiles/go.mod
  test/e2e/annotations/auth.go
  test/e2e/annotations/grpc.go
  test/e2e/framework/httpexpect/response.go
  test/e2e/settings/disable_sync_events.go
  test/e2e/settings/enable_real_ip.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, needs-priority

#10741 otel distroless
  images/opentelemetry/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10705 Update Documentation for Client-Cert Authentication misleading #10687
  docs/examples/auth/client-certs/README.md
Labels: cncf-cla: yes, lgtm, area/docs, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10750 update images from golang upgrade
  NGINX_BASE
  build/run-in-docker.sh
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  test/e2e-image/Makefile
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, needs-triage, needs-priority

#10742 Deployment/DaemonSet: Remove `distroless` from `extraModules` templating.
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#10755 Docs: Keep title in navbar in upcase
  mkdocs.yml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, ok-to-test, triage/accepted

#10731 Add more unit tests to helm chart
  .github/workflows/ci.yaml
  charts/ingress-nginx/tests/controller-configmap-addheaders_test.yaml
  charts/ingress-nginx/tests/controller-configmap-proxyheaders_test.yaml
  charts/ingress-nginx/tests/controller-configmap_test.yaml
  charts/ingress-nginx/tests/controller-daemonset_test.yaml
  charts/ingress-nginx/tests/controller-deployment_test.yaml
  charts/ingress-nginx/tests/controller-hpa_test.yaml
  charts/ingress-nginx/tests/controller-keda_test.yaml
  charts/ingress-nginx/tests/controller-networkpolicy_test.yaml
  charts/ingress-nginx/tests/controller-service-internal_test.yaml
  charts/ingress-nginx/tests/controller-service-metrics_test.yaml
  charts/ingress-nginx/tests/controller-service_test.yaml
  charts/ingress-nginx/tests/default-backend-service_test.yaml
Labels: cncf-cla: yes, lgtm, size/L, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted, area/helm

#10761 CI: Replace `chart-testing` image by `e2e-test-runner`.
  hack/verify-chart-lint.sh
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/failing-test, priority/important-soon, approved, triage/accepted

#10659 Helm fix: make status update permission configurable
  charts/ingress-nginx/templates/controller-role.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/backlog, approved, triage/accepted, area/helm

#10762 update images from golang upgrade (#10750)
  .github/workflows/ci.yaml
  images/nginx/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, needs-triage, needs-priority

#10781 update nginx build
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10721 Chart: Improve #10673.
  charts/ingress-nginx/templates/default-backend-extra-configmaps.yaml
  charts/ingress-nginx/tests/controller-service_test.yaml
  charts/ingress-nginx/tests/default-backend-extra-configmaps_test.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, priority/important-soon, approved, kind/cleanup, triage/accepted, area/helm

#10782 Helm: Remove `ingress-nginx-4.8.4`.
  index.yaml
Labels: cncf-cla: yes, lgtm, area/docs, size/S, needs-kind, needs-triage, needs-priority

#10767 Fix minor typos in bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10780 Correct typo from 'gingko' to 'ginkgo'
  ginkgo_upgrade.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10787 release plugin on controller release
  .github/workflows/plugin.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10788 Golang update
  .github/workflows/golangci-lint.yml
  .github/workflows/plugin.yaml
  go.mod
  go.sum
  go.work
  go.work.sum
  images/cfssl/rootfs/Dockerfile
  images/custom-error-pages/Makefile
  images/custom-error-pages/rootfs/Dockerfile
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/httpbun/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  images/nginx/TAG
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
  images/opentelemetry/Makefile
  images/opentelemetry/rootfs/Dockerfile
  images/opentelemetry/rootfs/go.mod
  images/test-runner/Makefile
  internal/ingress/annotations/annotations_test.go
  internal/ingress/annotations/parser/validators.go
  magefiles/go.mod
  magefiles/go.sum
  magefiles/steps/helm.go
  magefiles/utils/releasenote.go
  test/e2e/annotations/auth.go
  test/e2e/annotations/grpc.go
  test/e2e/framework/httpexpect/response.go
  test/e2e/settings/disable_sync_events.go
  test/e2e/settings/enable_real_ip.go
Labels: cncf-cla: yes, size/L, approved, needs-kind, needs-triage, needs-priority

#10789 Chart: Revert verion `4.8.4`.
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, area/helm, needs-priority

#10790 start 1.9.5 build
  TAG
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#10317 fix(labels): use complete labels variable on default-backend deployment
  charts/ingress-nginx/templates/default-backend-deployment.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#9677 Add controller.metrics.serviceMonitor.annotations in Helm chart
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, priority/backlog, needs-ok-to-test, approved, needs-triage, area/helm

#10795 release 1.9.5 docs
  README.md
  changelog/controller-1.9.5.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.9.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/e2e-tests.md
  go.work.sum
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, approved, needs-kind, needs-triage, area/helm, needs-priority

#10796 Chart: Add Gacko to maintainers.
  charts/ingress-nginx/Chart.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, kind/documentation, approved, triage/accepted, area/helm

#10803 Add common label to Dockerfiles
  images/kube-webhook-certgen/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/test-runner/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10800 change MODSECURITY_VERSION_LIB to 3.0.11
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10737 Fix up grammar in how-it-works.md
  docs/how-it-works.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10810 Bump download and upload artifact actions
  .github/workflows/ci.yaml
  .github/workflows/scorecards.yml
Labels: cncf-cla: yes, size/S, approved, needs-kind, needs-triage, needs-priority

#10816 Fix upload artifact action
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority
