Repository kubernetes/ingress-nginx, pull requests merged in 2023-02, with the labels that each got.

#9566 build release 1.6.1 image
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9570 add lint on chart before release
  .github/workflows/helm.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#9573 add path validation to implementation specific as well
  pkg/util/ingress/ingress.go
  pkg/util/ingress/ingress_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#9574 build 1.6.2
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, do-not-merge/invalid-commit-message, needs-triage, needs-priority

#9576 remove 4.4.3 Helm chart
  index.yaml
Labels: cncf-cla: yes, area/docs, size/S, needs-kind, needs-triage, needs-priority

#9581 Replace deprecated command with environment file
  .github/workflows/vulnerability-scans.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9542 Allow to pass a target test
  test/test-lua.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9568 add ah and helm chart linting to release
  magefiles/helm.go
  magefiles/release.go
Labels: cncf-cla: yes, size/M, approved, needs-kind, needs-triage, needs-priority

#9582 mage: using helm.sh/helm/v3
  magefiles/go.mod
  magefiles/go.sum
  magefiles/helm.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, needs-priority

#9607 Revert Implement pathType validation (#9511)
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-configmap.yaml
  charts/ingress-nginx/values.yaml
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/store/store.go
  internal/k8s/main.go
  magefiles/helm.go
  pkg/util/ingress/ingress.go
  pkg/util/ingress/ingress_test.go
  test/e2e/admission/admission.go
  test/e2e/annotations/affinity.go
  test/e2e/annotations/auth.go
  test/e2e/annotations/rewrite.go
  test/e2e/security/invalid_paths.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#9613 trigger the build 1.6.3
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9614 Release docs for Controller v1.6.3 and Helm v4.5.0
  README.md
  changelog/Changelog-1.6.3.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.5.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, approved, needs-kind, needs-triage, area/helm, needs-priority

#9617 Fix incorrect annotation name in upstream hashing configuration
  docs/user-guide/nginx-configuration/annotations.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, needs-triage, needs-priority

#9626 remove tests and regex path checks
  go.mod
  go.sum
  internal/ingress/controller/store/store.go
  pkg/util/ingress/ingress.go
  pkg/util/ingress/ingress_test.go
  test/e2e/security/invalid_paths.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, needs-priority

#9627 start 1.6.4 build
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9628 Release Notes Controller 1.6.4 Helm 4.5.1
  README.md
  changelog/Changelog-1.6.4.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.5.1.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#9629 Release new Helm Chart
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.5.2.md
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, area/helm, needs-priority

#9633 Fix rewrite example
  docs/examples/rewrite/README.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#9588 Optimize the judgment mode to remove redundant transformations
  internal/ingress/inspector/inspector.go
  internal/nginx/maxmind.go
  pkg/apis/ingress/types_equals.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9587 Adjust the import package order and use http library variables
  internal/ingress/controller/checker_test.go
  internal/ingress/controller/nginx_test.go
  internal/ingress/status/status.go
  test/e2e/framework/healthz.go
  test/e2e/framework/metrics.go
  test/e2e/status/update.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#9589 Replace all deprecated sets.String with sets.Set
  internal/ingress/controller/controller.go
  internal/ingress/controller/store/objectref.go
  internal/ingress/controller/template/template.go
  internal/ingress/metric/collectors/socket.go
  internal/ingress/metric/collectors/socket_test.go
  internal/ingress/metric/dummy.go
  internal/ingress/metric/main.go
  pkg/util/ingress/ingress.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9551 Optimize the document for readability in user guide
  docs/how-it-works.md
  docs/user-guide/k8s-122-migration.md
  docs/user-guide/miscellaneous.md
  docs/user-guide/monitoring.md
  docs/user-guide/multiple-ingress.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, needs-triage, needs-priority

#9571 code clean for fsnotify
  pkg/util/file/file_watcher.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/cleanup, ok-to-test, needs-triage, needs-priority

#9522 Rework Ginkgo usage
  Makefile
  internal/ingress/controller/store/store.go
  internal/k8s/main.go
  test/e2e-image/e2e.sh
  test/e2e-image/namespace-overlays/topology/values.yaml
  test/e2e/admission/admission.go
  test/e2e/annotations/fastcgi.go
  test/e2e/endpointslices/topology.go
  test/e2e/framework/exec.go
  test/e2e/framework/framework.go
  test/e2e/framework/influxdb.go
  test/e2e/framework/k8s.go
  test/e2e/leaks/lua_ssl.go
  test/e2e/run-chart-test.sh
  test/e2e/run-e2e-suite.sh
  test/e2e/run-kind-e2e.sh
  test/e2e/settings/configmap_change.go
  test/e2e/settings/namespace_selector.go
  test/e2e/settings/ocsp/ocsp.go
  test/e2e/tcpudp/tcp.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9550 controller: Don't panic when ready condition in a endpointslice is missing
  internal/ingress/controller/endpointslices.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#9647 changed v1.6.3 to v1.6.4 on deploy docs
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/important-soon, approved, needs-kind, triage/accepted

#9651 migrate mitchellh/hashstructure to v2
  go.mod
  go.sum
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/configmap_test.go
Labels: cncf-cla: yes, lgtm, size/S, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority
