Repository kubernetes/ingress-nginx, pull requests merged in 2023-10, with the labels that each got.

#10466 images: upgrade to Alpine 3.18.4
  images/cfssl/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/opentelemetry/rootfs/Dockerfile
  rootfs/Dockerfile-chroot
  test/e2e-image/Dockerfile
Labels: cncf-cla: yes, lgtm, size/S, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10467 fixes brotli build issues
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10473 docs(tls): add warning for not supporting TLSv1, TLSv1.1
  docs/user-guide/tls.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10469 Release v1.9.1
  README.md
  TAG
  changelog/Changelog-1.9.1.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.8.1.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#10477 Remove curl from nginx base image
  images/nginx/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10476 update error and otel to have all the arch we support
  images/custom-error-pages/Makefile
  images/opentelemetry/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10479 Revert "Remove curl from nginx base image (#10477)"
  images/nginx/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10494 add upstream patch for CVE-2023-44487
  images/nginx/rootfs/patches/nginx-1.21.4-http2.patch
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10492 added warning for configuration-snippets usage in docs
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, kind/documentation, approved, triage/accepted, needs-priority

#10503 Bump curl and Go version
  .github/workflows/ci.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/plugin.yaml
  build/run-in-docker.sh
  go.mod
  go.sum
  go.work
  go.work.sum
  images/custom-error-pages/rootfs/Dockerfile
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/httpbun/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  images/nginx/TAG
  images/opentelemetry/rootfs/go.mod
  images/test-runner/Makefile
  internal/ingress/annotations/annotations.go
  magefiles/go.mod
  magefiles/go.sum
  test/e2e/run-chart-test.sh
  test/e2e/run-kind-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XL, approved, needs-kind, tide/merge-method-squash, needs-triage, needs-priority

#10506 update nginx base, httpbun, e2e, helm webhook cert gen
  NGINX_BASE
  build/run-in-docker.sh
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  test/e2e-image/Makefile
  test/e2e/HTTPBUN_IMAGE
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, area/helm, needs-priority

#10509 Cherry pick image bump and re-add AJP as dynamic module
  NGINX_BASE
  build/run-in-docker.sh
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  rootfs/Dockerfile
  rootfs/Dockerfile-chroot
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e-image/Makefile
  test/e2e/HTTPBUN_IMAGE
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, area/helm, needs-priority

#10510 Release v1.8.3 final
  TAG
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#10511 Release v1.9.2
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10514 Bump x/net
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, needs-kind, needs-triage, needs-priority

#10515 Bump x/net
  TAG
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, needs-priority

#10517 Bump x/net
  TAG
  go.mod
  go.sum
  go.work.sum
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#10520 release 1.9.3
  README.md
  TAG
  changelog/Changelog-1.9.3.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.8.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#10519 controller 1.8.4 and helm 4.7.2 release
  .github/workflows/helm.yaml
  README.md
  changelog/Changelog-1.8.4.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.7.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, approved, needs-kind, needs-triage, area/helm, needs-priority

#10516 update docs to explicitly state TLS termination location
  docs/examples/grpc/README.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10255 DOCS Remove support for running Both
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/controller-hpa.yaml
  charts/ingress-nginx/templates/controller-keda.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10522 Update mkdocs version
  .github/actions/mkdocs/Dockerfile
  .github/actions/mkdocs/action.sh
  Makefile
  docs/requirements.txt
  mkdocs.yml
Labels: cncf-cla: yes, area/docs, size/S, approved, needs-kind, needs-triage, needs-priority

#10528 Fix fcgi configmap value parsing
  go.work.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  internal/ingress/annotations/fastcgi/main.go
  internal/ingress/annotations/fastcgi/main_test.go
  magefiles/go.mod
  magefiles/go.sum
Labels: cncf-cla: yes, lgtm, size/L, kind/bug, priority/important-soon, approved, triage/accepted

#10535 Documenting flag `enable-auth-access-log`
  docs/user-guide/nginx-configuration/configmap.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10544 Cherry pick fcgi fix and release v1.9.4
  TAG
  go.mod
  go.sum
  go.work
  go.work.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  internal/ingress/annotations/fastcgi/main.go
  internal/ingress/annotations/fastcgi/main_test.go
  magefiles/go.mod
  magefiles/go.sum
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, needs-priority

#10552 docs: fix list item format on troubleshooting.md
  docs/troubleshooting.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, kind/documentation, approved, ok-to-test, needs-triage, needs-priority

#10554 docs: fix broken link of "synchronization loop pattern"
  docs/how-it-works.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10558 changed readme as per issue 10556
  README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10539 feat: add namespace overrides
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/NOTES.txt
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/admission-webhooks/cert-manager.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/networkpolicy.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/templates/clusterrolebinding.yaml
  charts/ingress-nginx/templates/controller-configmap-addheaders.yaml
  charts/ingress-nginx/templates/controller-configmap-proxyheaders.yaml
  charts/ingress-nginx/templates/controller-configmap-tcp.yaml
  charts/ingress-nginx/templates/controller-configmap-udp.yaml
  charts/ingress-nginx/templates/controller-configmap.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/controller-hpa.yaml
  charts/ingress-nginx/templates/controller-networkpolicy.yaml
  charts/ingress-nginx/templates/controller-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/controller-role.yaml
  charts/ingress-nginx/templates/controller-rolebinding.yaml
  charts/ingress-nginx/templates/controller-secret.yaml
  charts/ingress-nginx/templates/controller-service-internal.yaml
  charts/ingress-nginx/templates/controller-service-metrics.yaml
  charts/ingress-nginx/templates/controller-service-webhook.yaml
  charts/ingress-nginx/templates/controller-service.yaml
  charts/ingress-nginx/templates/controller-serviceaccount.yaml
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
  charts/ingress-nginx/templates/default-backend-hpa.yaml
  charts/ingress-nginx/templates/default-backend-networkpolicy.yaml
  charts/ingress-nginx/templates/default-backend-poddisruptionbudget.yaml
  charts/ingress-nginx/templates/default-backend-role.yaml
  charts/ingress-nginx/templates/default-backend-rolebinding.yaml
  charts/ingress-nginx/templates/default-backend-service.yaml
  charts/ingress-nginx/templates/default-backend-serviceaccount.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#10576 Update TAG
  TAG
Labels: cncf-cla: yes, approved, needs-kind, needs-triage, needs-priority

#10564 Increase HSTS max-age to default to one year
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  test/data/cleanConf.expected.conf
  test/data/cleanConf.src.conf
  test/data/config.json
Labels: cncf-cla: yes, lgtm, area/docs, size/S, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10523 Admission Webhook: Truncate name.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/admission-webhooks/cert-manager.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/networkpolicy.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/psp.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
  charts/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority
