Repository kubernetes/ingress-nginx, pull requests merged in 2023-08, with the labels that each got.

#10257 promote distroless otel init image
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, triage/accepted, area/helm, needs-priority

#10272 test kind updates
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#9219 Handle request_id variable correctly in auth requests
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/authreq/main.go
  internal/ingress/annotations/authreq/main_test.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/auth.go
Labels: cncf-cla: yes, lgtm, area/docs, size/L, approved, needs-kind, tide/merge-method-squash, ok-to-test, needs-triage, needs-priority

#10256 Updated index.md - Fix typos
  docs/examples/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10249 helm: Use .Release.Namespace as default for ServiceMonitor namespace
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, area/helm, needs-priority

#10237 ci(helm): fix Helm Chart release action 422 error
  .github/workflows/helm.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10220 docs: fix tcp/udp services example explanation
  docs/user-guide/exposing-tcp-udp-services.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10282 Bump k8s.io/component-base from 0.26.4 to 0.27.4 (Replace Topology Aware Hints with Topology Aware Routing)
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  docs/user-guide/cli-arguments.md
  go.mod
  go.sum
  internal/ingress/controller/controller.go
  pkg/flags/flags.go
  test/e2e/framework/deployment.go
Labels: cncf-cla: yes, lgtm, area/docs, size/L, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#10296 Remove curl dependencies in e2e tests #9716
  test/e2e/annotations/serviceupstream.go
  test/e2e/endpointslices/topology.go
  test/e2e/servicebackend/service_externalname.go
  test/e2e/settings/tls.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10310 Add /etc/mime.types to custom-error-pages image
  images/custom-error-pages/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10316 Disable Modsecurity from internal processing which affects large ingresses
  rootfs/etc/nginx/template/nginx.tmpl
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10348 Use gzip instead of pigz in CI
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, lgtm, size/S, kind/failing-test, priority/important-soon, approved, ok-to-test, triage/accepted

#10350 Fix “dev-env” Makefile target to work with kubectl 1.28+
  build/dev-env.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/important-soon, approved, kind/cleanup, ok-to-test, needs-triage

#10335 Making auth access logs optional
  internal/ingress/controller/config/config.go
  rootfs/etc/nginx/template/nginx.tmpl
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, approved, ok-to-test, triage/accepted, needs-priority

#10357 Add firewall configuration to quick start documentation
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, kind/documentation, approved, ok-to-test, triage/accepted, needs-priority
