Repository kubernetes/ingress-nginx, pull requests merged in 2023-09, with the labels that each got.

#10330 fix: path with sepecial characters warning #10281 #10308
  docs/examples/rewrite/README.md
  docs/user-guide/ingress-path-matching.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10352 Upgrade OpenTelemetry to v1.11.0 and gRPC to v1.57.0
  images/opentelemetry/rootfs/CMakeLists.txt
  images/opentelemetry/rootfs/Dockerfile
  images/opentelemetry/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, needs-priority

#10254 DOCS consistent indentation for serviceaccount.annotations
  charts/ingress-nginx/templates/controller-serviceaccount.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, priority/important-soon, approved, kind/cleanup, triage/accepted, area/helm

#10187 Add golangci github action and replace the deprecated golint
  .github/workflows/ci.yaml
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  hack/verify-golint.sh
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10378 Bump Go version to 1.21.1 on testrunner
  images/test-runner/Makefile
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#10382 Fix http default backend test
  .github/workflows/ci.yaml
  test/e2e/defaultbackend/default_backend.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, needs-triage, needs-priority

#10379 Release v1.8.2 and Update Go to v1.21.1
  .github/workflows/ci.yaml
  .github/workflows/plugin.yaml
  TAG
  build/run-in-docker.sh
  go.mod
  go.sum
  images/custom-error-pages/rootfs/Dockerfile
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/httpbun/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/go.mod
  images/opentelemetry/rootfs/go.mod
  internal/ingress/controller/config/config.go
  magefiles/go.mod
  magefiles/go.sum
  test/e2e-image/Makefile
  test/e2e/defaultbackend/default_backend.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, needs-priority

#10306 fix: remove curl on base container #9716
  images/nginx/rootfs/Dockerfile
  images/test-runner/rootfs/Dockerfile
  rootfs/Dockerfile-chroot
  test/e2e-image/Dockerfile
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10389 release notes 1.8.2
  README.md
  TAG
  changelog/Changelog-1.8.2.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.7.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, approved, needs-kind, needs-triage, area/helm, needs-priority

#10259 Deployment/DaemonSet: Template `topologySpreadConstraints`.
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#10385 Remove gofmt in the CI pipeline
  .github/workflows/ci.yaml
Labels: cncf-cla: yes, lgtm, size/S, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10387 Fix deferInLoop error
  internal/nginx/maxmind.go
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10240 Deployment/DaemonSet: Fix templating & value.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10393 Disable user snippets per default
  .gitignore
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  cmd/plugin/util/util.go
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/annotations/fastcgi/main.go
  internal/ingress/annotations/modsecurity/main_test.go
  internal/ingress/annotations/proxy/main.go
  internal/ingress/annotations/sslcipher/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/metric/collectors/main.go
  internal/net/ssl/ssl.go
  magefiles/helm.go
  magefiles/mage.go
  magefiles/release.go
  magefiles/tags.go
  test/e2e/admission/admission.go
  test/e2e/annotations/auth.go
  test/e2e/annotations/fastcgi.go
  test/e2e/annotations/fromtowwwredirect.go
  test/e2e/annotations/grpc.go
  test/e2e/annotations/modsecurity/modsecurity.go
  test/e2e/annotations/serversnippet.go
  test/e2e/annotations/snippet.go
  test/e2e/annotations/streamsnippet.go
  test/e2e/framework/deployment.go
  test/e2e/ingress/multiple_rules.go
  test/e2e/ingress/pathtype_exact.go
  test/e2e/ingress/pathtype_mixed.go
  test/e2e/settings/badannotationvalues.go
  test/e2e/settings/geoip2.go
  test/e2e/settings/proxy_host.go
  test/e2e/settings/server_snippet.go
  test/e2e/settings/validations/validations.go
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#10396 Fix e2e test suite doc
  docs/e2e-tests.md
  hack/generate-e2e-suite-doc.sh
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10372 Update external-articles.md - advanced setup with GKE/Cloud Armor/IAP
  docs/user-guide/external-articles.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10300 helm: add resources to opentelemetry init container
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10409 DaemonSet: Implement OpenTelemetry resources.
  charts/ingress-nginx/templates/controller-daemonset.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#10422 Release v1.9.0-beta.0
  changelog/Changelog-1.9.0-beta.0.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.8.0-beta.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, approved, needs-kind, needs-triage, area/helm, needs-priority

#10383 fix path to faq.md in examples/rewrite/README.md
  docs/examples/rewrite/README.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, kind/documentation, approved, triage/accepted, needs-priority

#10287 Helm - Fix Chart.yaml - add license annotations, add type keyword, remove gotpl
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, tide/merge-method-squash, ok-to-test, needs-triage, area/helm, needs-priority

#10434 Fix release notes on helm
  magefiles/steps/helm.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#10433 Release v1.9.0
  changelog/Changelog-1.9.0.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/Changelog-4.8.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: cncf-cla: yes, lgtm, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#10323 upgrade owasp modsecurity core rule set to v3.3.5
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10238 Chart: Rework network policies.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/admission-webhooks/job-patch/networkpolicy.yaml
  charts/ingress-nginx/templates/controller-networkpolicy.yaml
  charts/ingress-nginx/templates/controller-webhooks-networkpolicy.yaml
  charts/ingress-nginx/templates/default-backend-networkpolicy.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, needs-ok-to-test, approved, needs-kind, needs-triage, area/helm, needs-priority

#10447 Update README.md for release 1.9.0
  README.md
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, needs-priority

#10456 Link configuration snippet to allow-snippet-annotations
  docs/user-guide/nginx-configuration/annotations.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10458 Fix link from #10456
  docs/user-guide/nginx-configuration/annotations.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#10460 Accept backend protocol on any case
  go.work.sum
  internal/ingress/controller/template/template.go
  test/e2e/annotations/backendprotocol.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, needs-priority

#10463 Start v1.9.1 release
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority
