Repository kubernetes/ingress-nginx, pull requests merged in 2024-07, with the labels that each got.

#11504 Docs: Improve default certificate usage.
  docs/user-guide/tls.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#11493 Docs: Specify `ingressClass` for multi-controller setup.
  docs/user-guide/multiple-ingress.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#11513 Docs: Add information about HTTP/3 support.
  images/nginx-1.25/README.md
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#11173 fix: Ensure changes in MatchCN annotation are detected
  internal/ingress/annotations/authtls/main.go
  internal/ingress/annotations/authtls/main_test.go
  test/e2e/annotations/authtls.go
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#11485 add ssl patches to nginx-1.25 image for coroutines to work in lua client hello and cert ssl blocks
  images/nginx-1.25/rootfs/patches/00_drop-alias-root.patch
  images/nginx-1.25/rootfs/patches/01_nginx-1.25.3-win32_max_err_str.patch
  images/nginx-1.25/rootfs/patches/02_nginx-1.25.3-stream_balancer_export.patch
  images/nginx-1.25/rootfs/patches/03_nginx-1.25.3-stream_proxy_get_next_upstream_tries.patch
  images/nginx-1.25/rootfs/patches/04_nginx-1.25.3-stream_proxy_timeout_fields.patch
  images/nginx-1.25/rootfs/patches/05_nginx-1.25.3-stream_ssl_preread_no_skip.patch
  images/nginx-1.25/rootfs/patches/06_nginx-1.25.3-resolver_conf_parsing.patch
  images/nginx-1.25/rootfs/patches/07_nginx-1.25.3-daemon_destroy_pool.patch
  images/nginx-1.25/rootfs/patches/08_nginx-1.25.3-init_cycle_pool_release.patch
  images/nginx-1.25/rootfs/patches/09_nginx-1.25.3-balancer_status_code.patch
  images/nginx-1.25/rootfs/patches/10_nginx-1.25.3-delayed_posted_events.patch
  images/nginx-1.25/rootfs/patches/11_nginx-1.25.3-privileged_agent_process.patch
  images/nginx-1.25/rootfs/patches/12_nginx-1.25.3-privileged_agent_process_connections.patch
  images/nginx-1.25/rootfs/patches/13_nginx-1.25.3-privileged_agent_process_thread_pool.patch
  images/nginx-1.25/rootfs/patches/14_nginx-1.25.3-single_process_graceful_exit.patch
  images/nginx-1.25/rootfs/patches/15_nginx-1.25.3-intercept_error_log.patch
  images/nginx-1.25/rootfs/patches/16_nginx-1.25.3-upstream_pipelining.patch
  images/nginx-1.25/rootfs/patches/17_nginx-1.25.3-no_error_pages.patch
  images/nginx-1.25/rootfs/patches/18_nginx-1.25.3-no_Werror.patch
  images/nginx-1.25/rootfs/patches/19_nginx-1.25.3-log_escape_non_ascii.patch
  images/nginx-1.25/rootfs/patches/20_nginx-1.25.3-proxy_host_port_vars.patch
  images/nginx-1.25/rootfs/patches/21_nginx-1.25.3-cache_manager_exit.patch
  images/nginx-1.25/rootfs/patches/22_nginx-1.25.3-larger_max_error_str.patch
  images/nginx-1.25/rootfs/patches/23_nginx-1.25.3-pcre_conf_opt.patch
  images/nginx-1.25/rootfs/patches/24_nginx-1.25.3-always_enable_cc_feature_tests.patch
  images/nginx-1.25/rootfs/patches/25_nginx-1.25.3-ssl_cert_cb_yield.patch
  images/nginx-1.25/rootfs/patches/26_nginx-1.25.3-ssl_sess_cb_yield.patch
  images/nginx-1.25/rootfs/patches/27_nginx-1.25.3-ssl_client_hello_cb_yield.patch
  images/nginx-1.25/rootfs/patches/28_nginx-1.25.3-upstream_timeout_fields.patch
  images/nginx-1.25/rootfs/patches/29_nginx-1.25.3-safe_resolver_ipv6_option.patch
  images/nginx-1.25/rootfs/patches/30_nginx-1.25.3-socket_cloexec.patch
  images/nginx-1.25/rootfs/patches/31_nginx-1.25.3-reuseport_close_unused_fds.patch
Labels: cncf-cla: yes, lgtm, size/XXL, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#11533 trigger build for NGINX-1.25 v0.0.8
  images/nginx-1.25/TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#11540 bump NGINX_BASE to v0.0.8
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#11545 tag new test runner image with new nginx base 0.0.8
  images/test-runner/TAG
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#11547 update test runner to latest build
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#11526 add k8s 1.30 to ci build
  .github/workflows/ci.yaml
  .github/workflows/images.yaml
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#11559 bumping TAG for 1.11 release
  TAG
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#11560 bumping 1.10.2 version
  TAG
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#11567 Mage: Stop mutating release notes.
  magefiles/steps/helm.go
  magefiles/steps/release.go
Labels: cncf-cla: yes, lgtm, size/M, priority/important-soon, approved, kind/cleanup, triage/accepted

#11578 Images: Bump `kube-webhook-certgen`.
  images/kube-webhook-certgen/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/important-soon, approved, kind/cleanup, triage/accepted

#11565 Release 1.10.2
  README.md
  changelog/controller-1.10.2.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
  go.work.sum
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, do-not-merge/hold, priority/important-soon, approved, kind/cleanup, triage/accepted, area/helm

#11585 Release Notes 1.11.0 and chart 4.11.0
  README.md
  changelog/controller-1.11.0.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.11.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/e2e-tests.md
  go.work.sum
Labels: cncf-cla: yes, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority

#11587 Repository: Add changelogs from `release-v1.10`.
  changelog/controller-1.10.2.md
  charts/ingress-nginx/changelog/helm-chart-4.10.2.md
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, kind/documentation, approved, triage/accepted, area/helm

#11586 README: Fix support matrix.
  README.md
Labels: cncf-cla: yes, lgtm, size/M, priority/important-soon, kind/documentation, approved, triage/accepted

#11589 Release: Apply changes from `main`.
  README.md
  changelog/controller-1.10.2.md
  changelog/controller-1.11.0.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.2.md
  charts/ingress-nginx/changelog/helm-chart-4.11.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/e2e-tests.md
  go.work.sum
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/important-soon, approved, kind/cleanup, triage/accepted, area/helm

#11593 README: Fix support matrix.
  README.md
Labels: cncf-cla: yes, size/M, approved, needs-kind, needs-triage, needs-priority

#11599 Images: Bump `NGINX_BASE` to v0.0.9.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/critical-urgent, approved, triage/accepted

#11600 Images: Bump `test-runner`.
  images/test-runner/TAG
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/critical-urgent, approved, triage/accepted

#11598 Fix indent in YAML for example pod
  docs/user-guide/fcgi-services.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, kind/bug, priority/backlog, needs-ok-to-test, approved, triage/accepted

#11606 un skip ocsp test
  go.work.sum
  images/test-runner/rootfs/Dockerfile
  test/e2e-image/Dockerfile
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, size/S, kind/bug, priority/critical-urgent, approved, tide/merge-method-squash, triage/accepted

#11617 remove modsecurity coreruleset test files from nginx image
  images/nginx-1.25/rootfs/build.sh
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, needs-ok-to-test, priority/important-soon, approved, triage/accepted

#11622 Bump github.com/prometheus/common from 0.54.0 to 0.55.0
  go.mod
  go.sum
  go.work.sum
  internal/ingress/metric/collectors/process.go
Labels: cncf-cla: yes, lgtm, size/XXL, priority/backlog, approved, kind/cleanup, triage/accepted

#11624 bump testing runner
  images/test-runner/TAG
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#11630 Images: Trigger NGINX build.
  images/nginx-1.25/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/important-soon, approved, kind/cleanup, triage/accepted

#11635 Images: Bump `NGINX_BASE` to v0.0.10.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-soon, approved, triage/accepted

#11636 Images: Trigger `test-runner` build.
  images/test-runner/TAG
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-soon, approved, triage/accepted

#11641 Images: Re-run `test-runner` build.
  images/test-runner/TAG
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-soon, approved, triage/accepted

#11645 Tests: Bump `test-runner` to v20240717-1fe74b5f.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-soon, approved, triage/accepted

#11649 Images: Trigger `controller` v1.11.1 build.
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-soon, approved, triage/accepted

#11648 Images: Trigger `controller` v1.10.3 build.
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/important-soon, approved, triage/accepted

#11650 Release controller v1.11.1 & chart v4.11.1.
  README.md
  changelog/controller-1.11.1.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.11.1.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
Labels: cncf-cla: yes, lgtm, size/L, priority/important-soon, approved, kind/cleanup, triage/accepted, area/helm

#11651 Release controller v1.10.3 & chart v4.10.3.
  README.md
  changelog/controller-1.10.3.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.3.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/L, priority/important-soon, approved, kind/cleanup, triage/accepted, area/helm

#11652 Docs: Update version in `deploy/index.md`.
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/backlog, kind/documentation, approved, triage/accepted

#11654 Release controller v1.11.1/v1.10.3 & chart v4.11.1/v4.10.3.
  README.md
  changelog/controller-1.10.3.md
  changelog/controller-1.11.1.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.3.md
  charts/ingress-nginx/changelog/helm-chart-4.11.1.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, area/docs, size/XL, priority/backlog, kind/documentation, approved, triage/accepted, area/helm

#11653 Bootstrap initial crossplane work
  .golangci.yml
  go.mod
  go.sum
  go.work.sum
  internal/ingress/controller/template/crossplane/config.go
  internal/ingress/controller/template/crossplane/crossplane.go
  internal/ingress/controller/template/crossplane/crossplane_internal_test.go
  internal/ingress/controller/template/crossplane/crossplane_internal_utils_test.go
  internal/ingress/controller/template/crossplane/crossplane_test.go
  internal/ingress/controller/template/crossplane/events.go
  internal/ingress/controller/template/crossplane/http.go
  internal/ingress/controller/template/crossplane/utils.go
Labels: cncf-cla: yes, size/XL, do-not-merge/hold, approved, needs-kind, needs-triage, needs-priority

#11659 Docs: Format NGINX configuration table.
  docs/user-guide/nginx-configuration/configmap.md
Labels: cncf-cla: yes, lgtm, area/docs, size/L, priority/backlog, kind/documentation, approved, triage/accepted

#11660 Docs: Format NGINX configuration table.
  docs/user-guide/nginx-configuration/configmap.md
Labels: cncf-cla: yes, area/docs, size/L, priority/backlog, kind/documentation, approved, triage/accepted

#11663 added real-client-ip faq
  docs/faq.md
  docs/user-guide/miscellaneous.md
  docs/user-guide/retaining-client-ipaddress.md
Labels: cncf-cla: yes, lgtm, area/docs, size/L, priority/backlog, kind/documentation, approved, triage/accepted

#11670 Add crossplane test and more directives
  internal/ingress/controller/template/crossplane/config.go
  internal/ingress/controller/template/crossplane/crossplane.go
  internal/ingress/controller/template/crossplane/crossplane_internal_test.go
  internal/ingress/controller/template/crossplane/crossplane_internal_utils_test.go
  internal/ingress/controller/template/crossplane/crossplane_test.go
  internal/ingress/controller/template/crossplane/events.go
  internal/ingress/controller/template/crossplane/http.go
  internal/ingress/controller/template/crossplane/testdata/README.md
  internal/ingress/controller/template/crossplane/testdata/nginx.tmpl
  internal/ingress/controller/template/crossplane/utils.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, needs-kind, needs-triage, needs-priority

#11671 crossplane: Add proxy pass header
  internal/ingress/controller/template/crossplane/http.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#11678 crossplane: Add brotli and proxy_hide_header
  internal/ingress/controller/template/crossplane/config.go
  internal/ingress/controller/template/crossplane/crossplane_test.go
  internal/ingress/controller/template/crossplane/http.go
  internal/ingress/controller/template/crossplane/testdata/nginx.tmpl
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#11688 Fix move nested if statement
  internal/ingress/controller/template/crossplane/http.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#11686 Add tests for tags with custom values
  internal/ingress/controller/template/crossplane/crossplane_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, triage/accepted, needs-priority

#11687 crossplane: Add test to 'proxy_hide_header' directive
  internal/ingress/controller/template/crossplane/crossplane_test.go
Labels: cncf-cla: yes, size/XS, needs-kind, ok-to-test, needs-triage, needs-priority

#11690 Add brotli module parser
  internal/ingress/controller/template/crossplane/config.go
  internal/ingress/controller/template/crossplane/crossplane_test.go
  internal/ingress/controller/template/crossplane/extramodules/README.md
  internal/ingress/controller/template/crossplane/extramodules/analyze.go
  internal/ingress/controller/template/crossplane/extramodules/brotli.go
Labels: cncf-cla: yes, size/L, approved, needs-kind, needs-triage, needs-priority

#11681 Add buildBlock helper and move upstream
  internal/ingress/controller/template/crossplane/crossplane_test.go
  internal/ingress/controller/template/crossplane/http.go
  internal/ingress/controller/template/crossplane/testdata/nginx.tmpl
  internal/ingress/controller/template/crossplane/utils.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, needs-triage, needs-priority

#11682 Docs: Clarify `from-to-www` redirect direction.
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/redirect/redirect.go
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#11679 Chart: Explicitly set `runAsGroup`.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/tests/controller-daemonset_test.yaml
  charts/ingress-nginx/tests/controller-deployment_test.yaml
  charts/ingress-nginx/tests/default-backend-deployment_test.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, approved, triage/accepted, area/helm

#11702 Tests: Bump `e2e-test-runner` to v20240729-04899b27.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#11699 Add CustomHTTPErrors directive
  internal/ingress/controller/template/crossplane/http.go
  internal/ingress/controller/template/crossplane/testdata/nginx.tmpl
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority
