Repository kubernetes/ingress-nginx, pull requests merged in 2024-10, with the labels that each got.

#12056 Chart: Add `controller.metrics.service.enabled`.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-service-metrics.yaml
  charts/ingress-nginx/tests/controller-service-metrics_test.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/S, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted, area/helm

#12066 Images: Bump `NGINX_BASE` to v1.0.0.
  NGINX_BASE
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12076 Images: Trigger NGINX build.
  images/nginx/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12080 Images: Bump `NGINX_BASE` to v0.1.0.
  NGINX_BASE
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12079 Images: Bump `NGINX_BASE` to v0.1.0.
  NGINX_BASE
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12089 Bump sigs.k8s.io/mdtoc from 1.1.0 to 1.4.0
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12088 Bump sigs.k8s.io/mdtoc from 1.1.0 to 1.4.0
  go.mod
  go.sum
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12093 Go: Bump to v1.22.8.
  GOLANG_VERSION
  go.mod
  go.work
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
  images/opentelemetry/rootfs/Dockerfile
  images/opentelemetry/rootfs/go.mod
  magefiles/go.mod
Labels: cncf-cla: yes, size/S, priority/backlog, do-not-merge/hold, approved, kind/cleanup, triage/accepted

#12094 Go: Bump to v1.22.8.
  GOLANG_VERSION
  go.mod
  go.work
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
  images/opentelemetry/rootfs/Dockerfile
  images/opentelemetry/rootfs/go.mod
  magefiles/go.mod
Labels: cncf-cla: yes, size/S, priority/backlog, do-not-merge/hold, approved, kind/cleanup, triage/accepted

#12069 Go: Bump to v1.22.8.
  GOLANG_VERSION
  go.mod
  go.work
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
  magefiles/go.mod
Labels: cncf-cla: yes, size/S, priority/backlog, do-not-merge/hold, approved, kind/cleanup, triage/accepted

#12091 Docs: Add a multi-tenant warning.
  README.md
  docs/deploy/hardening-guide.md
  docs/faq.md
Labels: cncf-cla: yes, area/docs, size/S, do-not-merge/hold, priority/important-soon, kind/documentation, approved, triage/accepted

#12100 Images: Trigger `test-runner` build.
  images/test-runner/TAG
Labels: cncf-cla: yes, priority/backlog, approved, kind/cleanup, triage/accepted

#12103 Tests: Bump `e2e-test-runner` to v20241004-114a6abb.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12110 Images: Trigger other builds.
  cloudbuild.yaml
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/custom-error-pages/cloudbuild.yaml
  images/fastcgi-helloserver/TAG
  images/fastcgi-helloserver/cloudbuild.yaml
  images/httpbun/TAG
  images/httpbun/cloudbuild.yaml
  images/kube-webhook-certgen/TAG
  images/kube-webhook-certgen/cloudbuild.yaml
  images/test-runner/cloudbuild.yaml
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12113 Cloud Build: Bump `gcb-docker-gcloud` to v20240718-5ef92b5c36.
  cloudbuild.yaml
  images/cfssl/cloudbuild.yaml
  images/custom-error-pages/cloudbuild.yaml
  images/e2e-test-echo/cloudbuild.yaml
  images/fastcgi-helloserver/cloudbuild.yaml
  images/httpbun/cloudbuild.yaml
  images/kube-webhook-certgen/cloudbuild.yaml
  images/nginx/cloudbuild.yaml
  images/test-runner/cloudbuild.yaml
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12117 Cloud Build: Bump `gcb-docker-gcloud` to v20240718-5ef92b5c36.
  cloudbuild.yaml
  images/cfssl/cloudbuild.yaml
  images/custom-error-pages/cloudbuild.yaml
  images/e2e-test-echo/cloudbuild.yaml
  images/fastcgi-helloserver/cloudbuild.yaml
  images/httpbun/cloudbuild.yaml
  images/kube-webhook-certgen/cloudbuild.yaml
  images/nginx/cloudbuild.yaml
  images/opentelemetry/cloudbuild.yaml
  images/test-runner/cloudbuild.yaml
Labels: cncf-cla: yes, priority/backlog, approved, kind/cleanup, triage/accepted

#12116 Cloud Build: Bump `gcb-docker-gcloud` to v20240718-5ef92b5c36.
  cloudbuild.yaml
  images/cfssl/cloudbuild.yaml
  images/custom-error-pages/cloudbuild.yaml
  images/e2e-test-echo/cloudbuild.yaml
  images/fastcgi-helloserver/cloudbuild.yaml
  images/httpbun/cloudbuild.yaml
  images/kube-webhook-certgen/cloudbuild.yaml
  images/nginx/cloudbuild.yaml
  images/opentelemetry/cloudbuild.yaml
  images/test-runner/cloudbuild.yaml
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12118 Tests & Docs: Bump images.
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12119 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#12123 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#12122 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#12125 Images: Build `s390x` controller.
  Makefile
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12131 Images: Drop `s390x`.
  .github/workflows/images.yaml
  Makefile
  hack/init-buildx.sh
  images/Makefile
  images/nginx/Makefile
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12132 Images: Trigger `e2e-test-echo` build.
  images/e2e-test-echo/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12143 Tests & Docs: Bump `e2e-test-echo` to v1.0.1.
  docs/examples/canary/README.md
  docs/examples/customization/external-auth-headers/echo-service.yaml
  test/e2e/framework/deployment.go
Labels: cncf-cla: yes, area/docs, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12095 Metrics: Disable by default.
  charts/ingress-nginx/templates/_params.tpl
  charts/ingress-nginx/tests/controller-daemonset_test.yaml
  charts/ingress-nginx/tests/controller-deployment_test.yaml
  docs/user-guide/cli-arguments.md
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, area/docs, size/M, kind/feature, priority/backlog, approved, triage/accepted, area/helm

#12149 Bump the actions group with 3 updates
  .github/workflows/chart.yaml
  .github/workflows/ci.yaml
  .github/workflows/depreview.yaml
  .github/workflows/docs.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/images.yaml
  .github/workflows/perftest.yaml
  .github/workflows/plugin.yaml
  .github/workflows/scorecards.yml
  .github/workflows/vulnerability-scans.yaml
  .github/workflows/zz-tmpl-images.yaml
  .github/workflows/zz-tmpl-k8s-e2e.yaml
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#12150 Bump the actions group with 3 updates
  .github/workflows/chart.yaml
  .github/workflows/ci.yaml
  .github/workflows/depreview.yaml
  .github/workflows/docs.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/images.yaml
  .github/workflows/perftest.yaml
  .github/workflows/plugin.yaml
  .github/workflows/scorecards.yml
  .github/workflows/vulnerability-scans.yaml
  .github/workflows/zz-tmpl-images.yaml
  .github/workflows/zz-tmpl-k8s-e2e.yaml
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#12133 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12134 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12154 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, priority/backlog, approved, kind/cleanup, triage/accepted

#12155 Release controller v1.10.5 & chart v4.10.5.
  README.md
  changelog/controller-1.10.5.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.5.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, kind/feature, priority/backlog, approved, triage/accepted, area/helm

#12156 Release controller v1.11.3 & chart v4.11.3.
  README.md
  changelog/controller-1.11.3.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.11.3.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, kind/feature, priority/backlog, approved, triage/accepted, area/helm

#12159 Docs: Goodbye, v1.10.
  README.md
Labels: cncf-cla: yes, priority/backlog, kind/documentation, triage/accepted

#12166 Release controller v1.12.0-beta.0/v1.11.3/v1.10.5 & chart v4.12.0-beta.0/v4.11.3/v4.10.5.
  README.md
  changelog/controller-1.10.5.md
  changelog/controller-1.11.3.md
  changelog/controller-1.12.0-beta.0.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.5.md
  charts/ingress-nginx/changelog/helm-chart-4.11.3.md
  charts/ingress-nginx/changelog/helm-chart-4.12.0-beta.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, kind/feature, priority/important-soon, approved, triage/accepted, area/helm

#12165 Release controller v1.12.0-beta.0 & chart v4.12.0-beta.0.
  README.md
  changelog/controller-1.12.0-beta.0.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.12.0-beta.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, area/docs, size/XL, kind/feature, do-not-merge/hold, priority/important-soon, approved, triage/accepted, area/helm

#12172 Docs: Clarify external & service port in TCP/UDP services explanation.
  docs/user-guide/exposing-tcp-udp-services.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#12174 Docs: Add Pod Security Admission.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/README.md.gotmpl
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, kind/documentation, approved, ok-to-test, triage/accepted, area/helm

#12198 Docs: Add Pod Security Admission.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/README.md.gotmpl
Labels: cncf-cla: yes, priority/backlog, kind/documentation, approved, triage/accepted, area/helm

#12197 Docs: Add Pod Security Admission.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/README.md.gotmpl
Labels: cncf-cla: yes, size/M, priority/backlog, kind/documentation, approved, triage/accepted, area/helm

#12201 Chart: Suggest `matchLabelKeys` in Topology Spread Constraints.
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted, area/helm

#12204 Chart: Suggest `matchLabelKeys` in Topology Spread Constraints.
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, size/XS, priority/backlog, kind/documentation, approved, triage/accepted, area/helm

#11569 [fix] fix nginx temp configs cleanup
  internal/ingress/controller/nginx.go
  internal/ingress/controller/nginx_test.go
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#12240 Bump the actions group with 5 updates
  .github/workflows/chart.yaml
  .github/workflows/ci.yaml
  .github/workflows/depreview.yaml
  .github/workflows/docs.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/images.yaml
  .github/workflows/perftest.yaml
  .github/workflows/plugin.yaml
  .github/workflows/scorecards.yml
  .github/workflows/vulnerability-scans.yaml
  .github/workflows/zz-tmpl-images.yaml
  .github/workflows/zz-tmpl-k8s-e2e.yaml
Labels: cncf-cla: yes, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#12232 Deploy: Use LoadBalancer for KIND.
  hack/manifest-templates/provider/kind/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/feature, priority/backlog, approved, triage/accepted

#12257 CI: Fix chart testing.
  .github/workflows/ci.yaml
  charts/ingress-nginx/tests/admission-webhooks/job-patch/serviceaccount_test.yaml
  charts/ingress-nginx/tests/admission-webhooks/validating-webhook_test.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/backlog, needs-ok-to-test, do-not-merge/hold, approved, triage/accepted, area/helm

#12250 Lua: Extract external auth into file.
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  rootfs/etc/nginx/lua/nginx/ngx_conf_external_auth.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/auth.go
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, kind/bug, priority/backlog, priority/important-soon, approved, triage/accepted, area/lua

#12261 Chart: Add ServiceAccount tests.
  charts/ingress-nginx/tests/controller-serviceaccount_test.yaml
  charts/ingress-nginx/tests/default-backend-serviceaccount_test.yaml
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, needs-ok-to-test, approved, kind/cleanup, triage/accepted, area/helm

#12247 Chart: Set `automountServiceAccountToken` in workloads.
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/templates/default-backend-deployment.yaml
  charts/ingress-nginx/tests/admission-webhooks/job-patch/job-createSecret_test.yaml
  charts/ingress-nginx/tests/admission-webhooks/job-patch/job-patchWebhook_test.yaml
  charts/ingress-nginx/tests/controller-daemonset_test.yaml
  charts/ingress-nginx/tests/controller-deployment_test.yaml
  charts/ingress-nginx/tests/default-backend-deployment_test.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, needs-ok-to-test, approved, triage/accepted, area/helm

#12267 Chart: Rework ServiceMonitor.
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
Labels: cncf-cla: yes, size/M, approved, needs-kind, needs-triage, area/helm, needs-priority

#12251 Chart: Implement ServiceMonitor limits.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-servicemonitor.yaml
  charts/ingress-nginx/tests/controller-servicemonitor_test.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, needs-ok-to-test, approved, triage/accepted, area/helm

#12277 Docs: fix limit-rate-after references
  docs/user-guide/nginx-configuration/configmap.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, kind/documentation, approved, ok-to-test, triage/accepted, needs-priority
