Repository kubernetes/ingress-nginx, pull requests merged in 2024-02, with the labels that each got.

#10957 Chart: Remove useless `default` from `_params.tpl`.
  charts/ingress-nginx/templates/_params.tpl
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#10958 Chart: Sync from `main`.
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.9.0.md
  charts/ingress-nginx/changelog/helm-chart-4.9.1.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#10959 Chart: Set `--enable-metrics` depending on `controller.metrics.enabled`.
  charts/ingress-nginx/templates/_params.tpl
  charts/ingress-nginx/tests/controller-daemonset_test.yaml
  charts/ingress-nginx/tests/controller-deployment_test.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/backlog, approved, triage/accepted, area/helm

#10962 E2E Tests: Explicitly enable metrics.
  test/e2e/wait-for-nginx.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, kind/failing-test, approved, triage/accepted

#11007 Update ingress-path-matching.md
  docs/user-guide/ingress-path-matching.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, do-not-merge/hold, kind/documentation, approved, ok-to-test, triage/accepted, needs-priority

#11008 Update ingress-path-matching.md
  docs/user-guide/ingress-path-matching.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, kind/documentation, approved, ok-to-test, triage/accepted, needs-priority

#10991 chore(deps): upgrade headers-more module to 0.37
  images/nginx-1.25/rootfs/build.sh
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#11021 Bump grpc and reintroduce OTEL compilation
  .github/workflows/images.yaml
  images/nginx-1.25/Makefile
  images/nginx-1.25/TAG
  images/nginx-1.25/rootfs/Dockerfile
  images/nginx-1.25/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, needs-kind, needs-triage, needs-priority

#11024 Bump modsecurity on nginx 1.25
  images/nginx-1.25/TAG
  images/nginx-1.25/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9536 Fix print-e2e-suite
  hack/print-e2e-suite.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10164 Properly support a TLS-wrapped OCSP responder
  rootfs/etc/nginx/lua/certificate.lua
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority, area/lua

#9092 fix datasource, $exported_namespace variable in grafana nginx dashboard
  deploy/grafana/dashboards/nginx.json
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved, needs-kind, needs-triage, needs-priority

#9541 test(gzip): reach ingress
  test/e2e/settings/gzip.go
Labels: cncf-cla: yes, lgtm, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#11027 Stop reporting interrupted tests
  test/e2e/framework/framework.go
Labels: cncf-cla: yes, lgtm, size/XS, priority/important-soon, approved, kind/cleanup, triage/accepted

#8902 Do not delete PrometheusRule when using tools like Pulumi to manage the Helm chart
  charts/ingress-nginx/templates/controller-prometheusrules.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, lifecycle/active, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#9545 chore(docs): add missing backend-protocol annotation option
  docs/user-guide/nginx-configuration/annotations.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#11023 Bump go libraries
  cmd/nginx/logger.go
  go.mod
  go.sum
  go.work.sum
  hack/update-codegen.sh
  images/kube-webhook-certgen/TAG
  images/kube-webhook-certgen/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  internal/ingress/annotations/rewrite/main.go
  internal/ingress/metric/collectors/testutils.go
  magefiles/go.mod
  magefiles/go.sum
  test/e2e/settings/gzip.go
  test/e2e/settings/pod_security_policy.go
  test/e2e/settings/pod_security_policy_volumes.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, needs-kind, needs-triage, needs-priority

#11033 Fix kubewebhook image tag
  images/kube-webhook-certgen/TAG
Labels: cncf-cla: yes, needs-triage

#11034 Bump kubewebhook certgen
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, area/helm, needs-priority

#11037 bump nginx and Go, remove tag file and old CI jobs
  .github/workflows/ci.yaml
  .github/workflows/images.yaml
  GOLANG_VERSION
  NGINX_BASE
  TAG
Labels: cncf-cla: yes, size/M, approved, needs-kind, needs-triage, needs-priority

#11038 Start the release of v1.10.0
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#11039 Release version v1.10.0
  README.md
  changelog/controller-1.10.0.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, approved, needs-kind, needs-triage, area/helm, needs-priority
