Repository kubernetes/ingress-nginx, pull requests merged in 2024-12, with the labels that each got.

#12439 Plugin: Bump `goreleaser` to v2.
  .github/workflows/plugin.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12433 Config/Annotations: Add `proxy-busy-buffers-size`.
  docs/user-guide/nginx-configuration/annotations-risk.md
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/annotations/proxy/main.go
  internal/ingress/annotations/proxy/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/defaults/main.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/annotations/proxy.go
Labels: cncf-cla: yes, lgtm, area/docs, size/M, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted

#12482 Go: Bump to v1.23.4.
  GOLANG_VERSION
  go.mod
  go.work
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
  magefiles/go.mod
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12486 rikatz is stepping down
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#12515 rikatz is stepping down
  .github/ISSUE_TEMPLATE/cve_report.md
  charts/ingress-nginx/Chart.yaml
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, area/helm, needs-priority

#12481 Images: Bump Alpine to v3.21.
  Makefile
  docs/examples/customization/sysctl/patch.json
  images/cfssl/rootfs/Dockerfile
  images/custom-error-pages/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
  images/test-runner/rootfs/Dockerfile
  rootfs/Dockerfile
  rootfs/Dockerfile-chroot
  rootfs/chroot.sh
  test/e2e-image/Dockerfile
Labels: cncf-cla: yes, lgtm, area/docs, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#12549 Bump k8s.io/cli-runtime from 0.31.3 to 0.32.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12553 CI: Update KIND images.
  .github/workflows/ci.yaml
  .github/workflows/images.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12558 CI: Update KIND images.
  .github/workflows/ci.yaml
  .github/workflows/images.yaml
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12554 Images: Bump `gcb-docker-gcloud` to v20241217-ff46a068cd.
  cloudbuild.yaml
  images/cfssl/cloudbuild.yaml
  images/custom-error-pages/cloudbuild.yaml
  images/e2e-test-echo/cloudbuild.yaml
  images/fastcgi-helloserver/cloudbuild.yaml
  images/httpbun/cloudbuild.yaml
  images/kube-webhook-certgen/cloudbuild.yaml
  images/nginx/cloudbuild.yaml
  images/test-runner/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12519 Repository: Update owners.
  OWNERS_ALIASES
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/OWNERS
  images/kube-webhook-certgen/OWNERS
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#12574 Go: Clean `go.work.sum`.
  go.work.sum
Labels: cncf-cla: yes, lgtm, size/XXL, priority/backlog, approved, kind/cleanup, triage/accepted

#12573 Go: Clean `go.work.sum`.
  go.work.sum
Labels: cncf-cla: yes, lgtm, size/XXL, priority/backlog, approved, kind/cleanup, triage/accepted

#12572 Go: Clean `go.work.sum`.
  go.work.sum
Labels: cncf-cla: yes, lgtm, size/XXL, priority/backlog, approved, kind/cleanup, triage/accepted

#12575 Go: Clean `go.work.sum`.
  go.mod
  go.work.sum
Labels: cncf-cla: yes, lgtm, size/XXL, priority/backlog, approved, kind/cleanup, triage/accepted

#12577 Images: Trigger NGINX build.
  images/nginx/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12576 Images: Trigger NGINX build.
  images/nginx/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12580 Images: Bump `NGINX_BASE` to v1.1.0.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12583 Images: Bump `NGINX_BASE` to v0.2.0.
  NGINX_BASE
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12585 Images: Trigger `test-runner` build.
  images/test-runner/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12589 Tests: Bump `e2e-test-runner` to v20241224-68ed4e7b.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12593 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12594 Images: Trigger other builds (2/2).
  images/fastcgi-helloserver/TAG
  images/go-grpc-greeter-server/TAG
  images/httpbun/TAG
  images/kube-webhook-certgen/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12601 Tests & Docs: Bump images.
  docs/examples/canary/README.md
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/examples/customization/external-auth-headers/echo-service.yaml
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/deployment.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12602 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#12607 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#12608 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#12609 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12610 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12611 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12613 Release controller v1.10.6 & chart v4.10.6.
  README.md
  changelog/controller-1.10.6.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.6.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#12614 Release controller v1.11.4 & chart v4.11.4.
  README.md
  changelog/controller-1.11.4.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.11.4.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#12615 Release controller v1.12.0 & chart v4.12.0.
  README.md
  changelog/controller-1.12.0.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.12.0.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm
