Repository kubernetes/ingress-nginx, pull requests merged in 2024-08, with the labels that each got.

#11710 Chart: Remove `isControllerTagValid`.
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/tests/controller-daemonset_test.yaml
  charts/ingress-nginx/tests/controller-deployment_test.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/backlog, approved, triage/accepted, area/helm

#11712 Docs: Fix `from-to-www` redirect description.
  docs/user-guide/nginx-configuration/annotations.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#11713 Chart: Remove `isControllerTagValid`.
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/tests/controller-daemonset_test.yaml
  charts/ingress-nginx/tests/controller-deployment_test.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/backlog, approved, triage/accepted, area/helm

#11714 Chart: Remove `isControllerTagValid`.
  charts/ingress-nginx/templates/_helpers.tpl
  charts/ingress-nginx/templates/controller-daemonset.yaml
  charts/ingress-nginx/templates/controller-deployment.yaml
  charts/ingress-nginx/tests/controller-daemonset_test.yaml
  charts/ingress-nginx/tests/controller-deployment_test.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/backlog, approved, triage/accepted, area/helm

#11717 chore: make the auth verify regex more strict
  internal/ingress/annotations/authtls/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, triage/accepted, needs-priority

#11720 Perform some cleaning operations on line breaks.
  internal/ingress/controller/template/template.go
Labels: cncf-cla: yes, lgtm, size/S, kind/bug, priority/backlog, approved, triage/accepted

#11723 Docs: Fix typo in AWS LB Controller reference
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#11634 Go: Bump to v1.22.5.
  GOLANG_VERSION
  go.mod
  go.work
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/go.mod
  images/opentelemetry/rootfs/Dockerfile
  images/opentelemetry/rootfs/build.sh
  images/opentelemetry/rootfs/go.mod
  magefiles/go.mod
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/backlog, approved, triage/accepted

#11730 Docs: Update OpenSSL Roadmap link
  images/nginx-1.25/README.md
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#11735 Images: Trigger NGINX build.
  images/nginx-1.25/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/important-soon, approved, kind/cleanup, triage/accepted

#11741 Images: Bump `NGINX_BASE` to v0.0.11.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#11747 Go: Bump to v1.22.6.
  GOLANG_VERSION
  go.mod
  go.work
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
  images/opentelemetry/rootfs/Dockerfile
  images/opentelemetry/rootfs/go.mod
  magefiles/go.mod
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#11633 Cloud Build: Some chores.
  cloudbuild.yaml
  images/cfssl/cloudbuild.yaml
  images/custom-error-pages/README.md
  images/custom-error-pages/TAG
  images/custom-error-pages/cloudbuild.yaml
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
  images/ext-auth-example-authsvc/cloudbuild.yaml
  images/fastcgi-helloserver/TAG
  images/fastcgi-helloserver/cloudbuild.yaml
  images/go-grpc-greeter-server/TAG
  images/go-grpc-greeter-server/cloudbuild.yaml
  images/httpbun/TAG
  images/httpbun/cloudbuild.yaml
  images/kube-webhook-certgen/cloudbuild.yaml
  images/nginx-1.25/cloudbuild.yaml
  images/nginx/cloudbuild.yaml
  images/nginx/rc.yaml
  images/opentelemetry/README.md
  images/opentelemetry/cloudbuild.yaml
  images/test-runner/cloudbuild.yaml
Labels: cncf-cla: yes, size/L, priority/backlog, do-not-merge/hold, approved, kind/cleanup, triage/accepted

#11758 Cloud Build: Fix substitutions.
  cloudbuild.yaml
  images/cfssl/cloudbuild.yaml
  images/custom-error-pages/cloudbuild.yaml
  images/ext-auth-example-authsvc/cloudbuild.yaml
  images/fastcgi-helloserver/cloudbuild.yaml
  images/go-grpc-greeter-server/cloudbuild.yaml
  images/httpbun/cloudbuild.yaml
  images/kube-webhook-certgen/cloudbuild.yaml
  images/nginx-1.25/cloudbuild.yaml
  images/nginx/cloudbuild.yaml
  images/opentelemetry/cloudbuild.yaml
  images/test-runner/cloudbuild.yaml
Labels: cncf-cla: yes, size/M, kind/bug, priority/backlog, approved, triage/accepted

#11761 Cloud Build: Tweak timeouts.
  images/opentelemetry/cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#9816 Generate correct output on NumCPU() when using cgroups2
  pkg/util/runtime/cpu_linux.go
  test/e2e/cgroups/cgroups.go
  test/e2e/e2e.go
Labels: cncf-cla: yes, lgtm, size/L, kind/bug, needs-ok-to-test, do-not-merge/hold, approved, triage/accepted, needs-priority

#11774 Cloud Build: Add missing config, remove unused ones.
  images/e2e-test-echo/cloudbuild.yaml
  images/go-grpc-greeter-server/cloudbuild.yaml
Labels: cncf-cla: yes, size/S, kind/bug, priority/backlog, approved, triage/accepted

#11779 Images: Trigger NGINX build.
  images/nginx-1.25/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#11775 Generate correct output on NumCPU() when using cgroups2
  pkg/util/runtime/cpu_linux.go
  test/e2e/cgroups/cgroups.go
  test/e2e/e2e.go
Labels: cncf-cla: yes, size/L, kind/bug, priority/backlog, approved, triage/accepted

#11778 Generate correct output on NumCPU() when using cgroups2
  pkg/util/runtime/cpu_linux.go
  test/e2e/cgroups/cgroups.go
  test/e2e/e2e.go
Labels: cncf-cla: yes, size/L, kind/bug, priority/backlog, approved, triage/accepted

#11782 Images: Bump `NGINX_BASE` to v0.0.12.
  NGINX_BASE
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#11785 Images: Trigger `test-runner` build.
  images/test-runner/TAG
Labels: cncf-cla: yes, priority/backlog, approved, kind/cleanup, triage/accepted

#11788 Tests: Bump `e2e-test-runner` to v20240812-3f0129aa.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#11789 Controller: Fix panic in alternative backend merging.
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, needs-ok-to-test, priority/important-soon, approved, triage/accepted

#11796 Images: Trigger other builds.
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
  images/fastcgi-helloserver/TAG
  images/go-grpc-greeter-server/TAG
  images/httpbun/TAG
  images/kube-webhook-certgen/TAG
  images/nginx/TAG
  images/opentelemetry/TAG
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#11800 Images: Trigger failed builds.
  images/custom-error-pages/TAG
  images/fastcgi-helloserver/TAG
  images/httpbun/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#11803 Tests & Docs: Bump images.
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/user-guide/third-party-addons/opentelemetry.md
  images/test-runner/rootfs/Dockerfile
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#11804 Tests & Docs: Bump images.
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/user-guide/third-party-addons/opentelemetry.md
  images/test-runner/rootfs/Dockerfile
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, area/docs, size/S, approved, needs-kind, needs-triage, needs-priority

#11805 Tests & Docs: Bump images.
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/user-guide/third-party-addons/opentelemetry.md
  images/test-runner/rootfs/Dockerfile
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, area/docs, size/S, approved, needs-kind, needs-triage, needs-priority

#11808 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, size/XS, priority/important-soon, approved, kind/cleanup, triage/accepted

#11807 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, size/XS, priority/important-soon, approved, kind/cleanup, triage/accepted

#11809 Chart: Bump Kube Webhook CertGen & OpenTelemetry.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#11814 Release controller v1.11.2 & chart v4.11.2.
  README.md
  changelog/controller-1.11.2.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.11.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#11815 Release controller v1.10.4 & chart v4.10.4.
  README.md
  changelog/controller-1.10.4.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.4.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#11816 Release controller v1.11.2/v1.10.4 & chart v4.11.2/v4.10.4.
  README.md
  changelog/controller-1.10.4.md
  changelog/controller-1.11.2.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.10.4.md
  charts/ingress-nginx/changelog/helm-chart-4.11.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#11795 Metrics: Remove `ingress_upstream_latency_seconds`.
  docs/user-guide/monitoring.md
  internal/ingress/metric/collectors/socket.go
Labels: cncf-cla: yes, lgtm, area/docs, size/M, kind/bug, priority/backlog, approved, ok-to-test, triage/accepted

#11820 Auto-generate annotation docs
  .github/workflows/ci.yaml
  Makefile
  cmd/annotations/annotations.tmpl
  cmd/annotations/main.go
  docs/user-guide/nginx-configuration/annotations-risk.md
  hack/update-annotation-doc.sh
  hack/verify-annotation-docs.sh
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/parser/main.go
  mkdocs.yml
Labels: cncf-cla: yes, lgtm, area/docs, size/L, approved, needs-kind, needs-triage, needs-priority

#11835 Auto-generate annotation docs
  .github/workflows/ci.yaml
  Makefile
  cmd/annotations/annotations.tmpl
  cmd/annotations/main.go
  docs/user-guide/nginx-configuration/annotations-risk.md
  hack/update-annotation-doc.sh
  hack/verify-annotation-docs.sh
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/parser/main.go
  mkdocs.yml
Labels: cncf-cla: yes, area/docs, size/L, priority/backlog, approved, kind/cleanup, triage/accepted

#11821 Remove 3rd party lua plugin support
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/controller/config/config.go
  internal/ingress/controller/template/configmap.go
  rootfs/etc/nginx/lua/plugins.lua
  rootfs/etc/nginx/lua/plugins/README.md
  rootfs/etc/nginx/lua/plugins/hello_world/main.lua
  rootfs/etc/nginx/lua/plugins/hello_world/test/main_test.lua
  rootfs/etc/nginx/lua/test/plugins_test.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/data/cleanConf.expected.conf
  test/data/cleanConf.src.conf
  test/e2e/settings/plugins.go
  test/test-lua.sh
Labels: cncf-cla: yes, lgtm, area/docs, size/L, priority/important-longterm, approved, needs-kind, needs-triage, area/lua

#11841 Bump k8s.io/component-base from 0.30.3 to 0.31.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, priority/backlog, do-not-merge/hold, approved, kind/cleanup, do-not-merge/invalid-commit-message, triage/accepted

#11846 Bump dario.cat/mergo from 1.0.0 to 1.0.1 in the all group
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, do-not-merge/invalid-commit-message, triage/accepted

#9565 docs: Add deployment for AWS NLB Proxy.
  deploy/static/provider/aws/nlb-proxy-with-tls-termination/deploy.yaml
  deploy/static/provider/aws/nlb-proxy-with-tls-termination/kustomization.yaml
Labels: cncf-cla: yes, lgtm, size/XL, needs-ok-to-test, do-not-merge/hold, approved, needs-kind, needs-triage, needs-priority

#11819 Enable security features by default
  .github/workflows/ci.yaml
  .github/workflows/zz-tmpl-k8s-e2e.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  docs/user-guide/cli-arguments.md
  internal/ingress/controller/config/config.go
  pkg/flags/flags.go
  test/e2e/admission/admission.go
  test/e2e/annotations/auth.go
  test/e2e/annotations/fromtowwwredirect.go
  test/e2e/annotations/grpc.go
  test/e2e/annotations/modsecurity/modsecurity.go
  test/e2e/annotations/serversnippet.go
  test/e2e/annotations/snippet.go
  test/e2e/annotations/streamsnippet.go
  test/e2e/framework/exec.go
  test/e2e/framework/framework.go
  test/e2e/ingress/multiple_rules.go
  test/e2e/ingress/pathtype_exact.go
  test/e2e/ingress/pathtype_mixed.go
  test/e2e/run-e2e-suite.sh
  test/e2e/run-kind-e2e.sh
  test/e2e/settings/badannotationvalues.go
  test/e2e/settings/geoip2.go
  test/e2e/settings/proxy_host.go
  test/e2e/settings/server_snippet.go
  test/e2e/settings/validations/validations.go
  test/e2e/wait-for-nginx.sh
Labels: cncf-cla: yes, lgtm, area/docs, size/L, kind/bug, priority/critical-urgent, approved, triage/accepted, area/helm

#11853 Replace deprecated queue method
  internal/task/queue.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#9971 Add native histogram support for histogram metrics
  cmd/dataplane/main.go
  cmd/nginx/main.go
  docs/user-guide/cli-arguments.md
  go.work.sum
  internal/ingress/controller/controller.go
  internal/ingress/metric/collectors/socket.go
  internal/ingress/metric/collectors/socket_test.go
  internal/ingress/metric/main.go
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, area/docs, size/L, approved, needs-kind, ok-to-test, needs-triage, needs-priority

#10651 Add custom code handling for temporal redirect
  docs/user-guide/nginx-configuration/annotations-risk.md
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/redirect/redirect.go
  internal/ingress/annotations/redirect/redirect_test.go
Labels: cncf-cla: yes, lgtm, area/docs, size/M, approved, needs-kind, needs-triage, needs-priority

#11857 Revert "docs: Add deployment for AWS NLB Proxy."
  deploy/static/provider/aws/nlb-proxy-with-tls-termination/deploy.yaml
  deploy/static/provider/aws/nlb-proxy-with-tls-termination/kustomization.yaml
Labels: cncf-cla: yes, approved, needs-kind, needs-triage, needs-priority

#11851 Remove global-rate-limit feature
  charts/ingress-nginx/tests/controller-configmap_test.yaml
  docs/e2e-tests.md
  docs/user-guide/nginx-configuration/annotations-risk.md
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  images/nginx-1.25/rootfs/build.sh
  images/nginx/rootfs/build.sh
  internal/ingress/annotations/annotations.go
  internal/ingress/annotations/globalratelimit/main.go
  internal/ingress/annotations/globalratelimit/main_test.go
  internal/ingress/controller/config/config.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/template/configmap.go
  internal/ingress/controller/template/template.go
  internal/ingress/controller/template/template_test.go
  pkg/apis/ingress/types.go
  pkg/apis/ingress/types_equals.go
  rootfs/etc/nginx/lua/global_throttle.lua
  rootfs/etc/nginx/lua/lua_ingress.lua
  rootfs/etc/nginx/lua/test/global_throttle_test.lua
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/admission/admission.go
  test/e2e/annotations/globalratelimit.go
  test/e2e/settings/globalratelimit.go
  test/test-lua.sh
Labels: cncf-cla: yes, lgtm, area/docs, size/XXL, approved, kind/deprecation, needs-triage, area/helm, needs-priority, area/lua

#11861 Update maxmind post link about geolite2 license changes
  Changelog.md
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
  docs/user-guide/cli-arguments.md
  docs/user-guide/nginx-configuration/configmap.md
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, approved, needs-kind, ok-to-test, needs-triage, area/helm, needs-priority

#11876 Go: Sync `go.work.sum`.
  go.work.sum
Labels: cncf-cla: yes, size/M, approved, needs-kind, needs-triage, needs-priority

#11875 Go: Sync `go.work.sum`.
  go.work.sum
Labels: cncf-cla: yes, size/M, approved, needs-kind, needs-triage, needs-priority

#11818 Metrics: Add `--metrics-per-undefined-host` argument.
  cmd/dataplane/main.go
  cmd/nginx/main.go
  docs/user-guide/cli-arguments.md
  docs/user-guide/monitoring.md
  internal/ingress/controller/controller.go
  internal/ingress/metric/collectors/socket.go
  internal/ingress/metric/collectors/socket_test.go
  internal/ingress/metric/main.go
  pkg/flags/flags.go
  pkg/flags/flags_test.go
  test/e2e/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, area/docs, size/L, kind/feature, needs-rebase, priority/backlog, approved, ok-to-test, triage/accepted

#11878 Dashboard: Remove `ingress_upstream_latency_seconds`.
  deploy/grafana/dashboards/request-handling-performance.json
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#11872 Lua: Remove plugins from `.luacheckrc` & E2E docs.
  .luacheckrc
  docs/e2e-tests.md
Labels: cncf-cla: yes, area/docs, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#11874 Security: Follow-up on recent changes.
  .github/workflows/images.yaml
  charts/ingress-nginx/templates/_params.tpl
  charts/ingress-nginx/templates/controller-configmap.yaml
  docs/user-guide/nginx-configuration/configmap.md
  internal/ingress/resolver/mock.go
  pkg/flags/flags.go
  test/e2e/settings/proxy_host.go
  test/e2e/wait-for-nginx.sh
Labels: cncf-cla: yes, lgtm, area/docs, size/M, priority/important-soon, approved, kind/cleanup, triage/accepted, area/helm

#11877 Chart: Use generic values for `ConfigMap` test.
  charts/ingress-nginx/tests/controller-configmap_test.yaml
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#11879 Chart: Use generic values for `ConfigMap` test.
  charts/ingress-nginx/tests/controller-configmap_test.yaml
Labels: cncf-cla: yes, size/S, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#11862 CI: Grant checks write permissions to E2E Test Report.
  .github/workflows/junit-reports.yaml
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, needs-ok-to-test, priority/important-soon, approved, triage/accepted

#11882 Annotations: Allow commas in URLs.
  internal/ingress/annotations/parser/validators.go
  internal/ingress/annotations/parser/validators_test.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/backlog, approved, ok-to-test, triage/accepted

#11883 Chart: Add tests for `PrometheusRule` & `ServiceMonitor`.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-prometheusrule.yaml
  charts/ingress-nginx/tests/controller-prometheusrule_test.yaml
  charts/ingress-nginx/tests/controller-servicemonitor_test.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, size/M, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#11849 Chart: Add `controller.metrics.prometheusRule.annotations`.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/controller-prometheusrule.yaml
  charts/ingress-nginx/tests/controller-prometheusrule_test.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/S, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted, area/helm

#11916 Images: Trigger `test-runner` build.
  images/test-runner/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#11919 Tests: Bump `e2e-test-runner` to v20240829-2c421762.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#11153 Allow any protocol for cors origins
  docs/user-guide/nginx-configuration/annotations.md
  internal/ingress/annotations/cors/main.go
  internal/ingress/annotations/cors/main_test.go
  test/e2e/annotations/cors.go
Labels: cncf-cla: yes, lgtm, area/docs, size/M, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted
