Repository kubernetes/ingress-nginx, pull requests merged in 2025-08, with the labels that each got.

#13680 Chart: Push to OCI registry.
  charts/Makefile
  charts/ingress-nginx/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13700 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13701 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13702 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13715 Images: Bump NGINX to v2.2.1.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13716 Images: Bump NGINX to v2.2.1.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13718 Go: Bump to v1.24.6.
  GOLANG_VERSION
  go.mod
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13719 Go: Bump to v1.24.6.
  GOLANG_VERSION
  go.mod
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13721 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13729 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13731 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, do-not-merge/hold, approved, kind/cleanup, triage/accepted

#13735 Images: Trigger other builds (2/2).
  images/fastcgi-helloserver/TAG
  images/go-grpc-greeter-server/TAG
  images/httpbun/TAG
  images/kube-webhook-certgen/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13733 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13737 Docs: Fix default config values and links.
  docs/kubectl-plugin.md
  docs/user-guide/nginx-configuration/annotations.md
  docs/user-guide/nginx-configuration/configmap.md
  docs/user-guide/third-party-addons/opentelemetry.md
  internal/ingress/controller/config/config.go
Labels: cncf-cla: yes, lgtm, area/docs, size/M, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#13742 Tests: Add `ssl-session-*` config values tests.
  test/e2e/settings/ssl_session_cache.go
  test/e2e/settings/ssl_session_tickets.go
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, needs-ok-to-test, approved, kind/cleanup, triage/accepted

#13751 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, triage/accepted

#13760 Tests & Docs: Bump images.
  docs/examples/canary/README.md
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/examples/customization/external-auth-headers/echo-service.yaml
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/deployment.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13763 Tests & Docs: Bump images.
  docs/examples/canary/README.md
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/examples/customization/external-auth-headers/echo-service.yaml
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/deployment.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13771 Release controller v1.12.5 & chart v4.12.5.
  README.md
  changelog/controller-1.12.5.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.12.5.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13774 CI: Update Kubernetes to v1.33.4.
  .github/workflows/ci.yaml
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13775 Go: Update dependencies.
  go.mod
  go.sum
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13766 Chores: Migrate deprecated `wait.Poll*` to context-aware equivalents.
  internal/ingress/status/status.go
  test/e2e/framework/k8s.go
  test/e2e/status/update.go
  test/e2e/tcpudp/tcp.go
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, ok-to-test, triage/accepted

#13769 Tests: Enhance SSL Proxy.
  pkg/flags/flags_test.go
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, ok-to-test, triage/accepted

#13808 Tests: Bump Ginkgo to v2.25.0.
  build/run-in-docker.sh
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  images/test-runner/Makefile
  test/e2e/run-chart-test.sh
  test/e2e/run-kind-e2e.sh
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13812 Docs: Replace no-break spaces (U+A0).
  NEW_CONTRIBUTOR.md
  README.md
Labels: cncf-cla: yes, size/M, priority/backlog, kind/documentation, approved, triage/accepted

#13816 Tests: Bump Ginkgo to v2.25.1.
  build/run-in-docker.sh
  go.mod
  go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  images/test-runner/Makefile
  test/e2e/run-chart-test.sh
  test/e2e/run-kind-e2e.sh
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13817 Tests: Bump Ginkgo to v2.25.1.
  build/run-in-docker.sh
  go.mod
  go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  images/test-runner/Makefile
  test/e2e/run-chart-test.sh
  test/e2e/run-kind-e2e.sh
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13752 Annotations/AuthTLS: Allow named redirects.
  internal/ingress/annotations/authtls/main.go
  internal/ingress/annotations/authtls/main_test.go
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, kind/bug, priority/backlog, approved, ok-to-test, triage/accepted

#13827 Go: Update dependencies.
  go.mod
  go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13811 Chart: Add volumes for webhook patch job.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
  charts/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  charts/ingress-nginx/tests/admission-webhooks/job-patch/job-createSecret_test.yaml
  charts/ingress-nginx/tests/admission-webhooks/job-patch/job-patchWebhook_test.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/L, kind/feature, priority/backlog, approved, ok-to-test, triage/accepted, area/helm

#13834 Images: Trigger NGINX build.
  images/nginx/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, do-not-merge/hold, approved, kind/cleanup, triage/accepted

#13835 Images: Bump NGINX to v2.2.2.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13837 Images: Bump NGINX to v1.3.2.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13838 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13841 Tests: Bump Test Runner to v2.2.2.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13842 Tests: Bump Test Runner to v2.2.2.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13845 Images: Trigger other builds (2/2).
  images/fastcgi-helloserver/TAG
  images/go-grpc-greeter-server/TAG
  images/httpbun/TAG
  images/kube-webhook-certgen/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13848 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13830 Metrics: Fix `nginx_ingress_controller_config_last_reload_successful`.
  internal/ingress/controller/controller.go
  internal/ingress/controller/nginx.go
Labels: cncf-cla: yes, lgtm, size/S, kind/bug, priority/backlog, approved, kind/cleanup, ok-to-test, triage/accepted

#13865 Release controller v1.13.2 & chart v4.13.2.
  README.md
  changelog/controller-1.13.2.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.13.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13866 Release controller v1.12.6 & chart v4.12.6.
  README.md
  changelog/controller-1.12.6.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.12.6.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm
