Repository kubernetes/ingress-nginx, pull requests merged in 2025-03, with the labels that each got.

#12914 NGINX: Update ModSecurity.
  images/nginx/rootfs/build.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, needs-ok-to-test, approved, kind/cleanup, triage/accepted

#12906 Chart: Add `controller.admissionWebhooks.certManager.*.revisionHistoryLimit`.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/templates/admission-webhooks/cert-manager.yaml
  charts/ingress-nginx/tests/admission-webhooks/cert-manager_test.yaml
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, priority/backlog, needs-ok-to-test, do-not-merge/hold, approved, triage/accepted, area/helm

#12928 Test: Remove gRPC Fortune Teller.
  images/README.md
  test/e2e/annotations/grpc.go
  test/e2e/framework/grpc_fortune_teller.go
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, triage/accepted

#12907 CI: Update KIND images.
  .github/workflows/ci.yaml
  .github/workflows/images.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#12932 CI: Update KIND images.
  .github/workflows/ci.yaml
  .github/workflows/images.yaml
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#12935 Go: Bump to v1.24.1.
  .github/workflows/golangci-lint.yml
  GOLANG_VERSION
  go.mod
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
  internal/ingress/annotations/mirror/main_test.go
  internal/ingress/metric/collectors/nginx_status_test.go
  magefiles/go.mod
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#10989 fix DNS issues with unresolvable backends with ExternalName
  rootfs/etc/nginx/lua/balancer.lua
Labels: cncf-cla: yes, lgtm, size/S, approved, needs-kind, ok-to-test, needs-triage, needs-priority, area/lua

#12947 Docs: Update link to `values.yaml`.
  docs/examples/customization/jwt/README.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#12962 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  magefiles/go.mod
  magefiles/go.sum
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, triage/accepted

#12963 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  magefiles/go.mod
  magefiles/go.sum
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, triage/accepted

#12976 Docs: Use `enable-global-auth` annotation instead of non-existing ConfigMap option.
  docs/user-guide/nginx-configuration/annotations.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#13005 Custom Error Pages: Accept first of many MIME types.
  images/custom-error-pages/rootfs/main.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/backlog, needs-ok-to-test, approved, triage/accepted

#13008 Images: Rework. (1/3)
  Makefile
  cloudbuild.yaml
  hack/init-buildx.sh
  images/Makefile
  images/nginx/Makefile
  images/nginx/cloudbuild.yaml
  images/nginx/rootfs/Dockerfile
  images/nginx/rootfs/build.sh
  images/test-runner/Makefile
  images/test-runner/cloudbuild.yaml
  images/test-runner/rootfs/Dockerfile
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, triage/accepted

#13013 Images: Rework. (2/3)
  images/cfssl/cloudbuild.yaml
  images/custom-error-pages/cloudbuild.yaml
  images/e2e-test-echo/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13010 Images: Rework. (3/3)
  images/fastcgi-helloserver/cloudbuild.yaml
  images/httpbun/cloudbuild.yaml
  images/kube-webhook-certgen/cloudbuild.yaml
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13021 CI: Update Kubernetes to v1.32.3.
  .github/workflows/ci.yaml
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13020 Bump github.com/onsi/ginkgo/v2 from 2.23.0 to 2.23.3
  build/run-in-docker.sh
  go.mod
  go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  images/test-runner/Makefile
  test/e2e/run-chart-test.sh
  test/e2e/run-kind-e2e.sh
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13022 CI: Update KIND to v1.32.3.
  .github/workflows/ci.yaml
  .github/workflows/images.yaml
  build/dev-env.sh
  test/e2e/run-chart-test.sh
  test/e2e/run-kind-e2e.sh
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13030 CI: Update KIND to v1.32.3.
  build/dev-env.sh
  test/e2e/run-chart-test.sh
  test/e2e/run-kind-e2e.sh
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13035 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  magefiles/go.mod
  magefiles/go.sum
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, triage/accepted

#13036 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  magefiles/go.mod
  magefiles/go.sum
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, triage/accepted

#13037 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
  magefiles/go.mod
  magefiles/go.sum
Labels: cncf-cla: yes, lgtm, size/L, priority/backlog, approved, kind/cleanup, triage/accepted

#13040 Images: Trigger NGINX build.
  images/nginx/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13039 Images: Trigger NGINX build.
  images/nginx/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13041 Images: Bump `NGINX_BASE` to v0.3.1.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13042 Images: Bump `NGINX_BASE` to v2.0.1.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13043 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, lgtm, priority/backlog, approved, kind/cleanup, triage/accepted

#13045 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, priority/backlog, approved, kind/cleanup, triage/accepted

#13046 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, priority/backlog, approved, kind/cleanup, triage/accepted

#13047 Tests: Bump Test Runner to v2.0.1.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13050 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, needs-kind, needs-triage

#13051 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#13056 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, needs-priority

#13057 Images: Trigger other builds (2/2).
  images/fastcgi-helloserver/TAG
  images/go-grpc-greeter-server/TAG
  images/httpbun/TAG
  images/kube-webhook-certgen/TAG
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-kind, needs-triage, needs-priority

#13062 Tests & Docs: Bump images.
  docs/examples/canary/README.md
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/examples/customization/external-auth-headers/echo-service.yaml
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/deployment.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, area/docs, size/S, priority/backlog, do-not-merge/hold, approved, kind/cleanup, triage/accepted

#13063 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13067 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, size/XS, approved, needs-kind, needs-triage, area/helm, needs-priority

#13069 Controller: Several security fixes.
  internal/ingress/annotations/auth/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/admission/admission.go
  test/e2e/annotations/mirror.go
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/important-soon, approved, triage/accepted

#13070 Controller: Several security fixes.
  internal/ingress/annotations/auth/main.go
  internal/ingress/controller/controller.go
  internal/ingress/controller/controller_test.go
  internal/ingress/controller/template/template.go
  rootfs/etc/nginx/template/nginx.tmpl
  test/e2e/admission/admission.go
  test/e2e/annotations/mirror.go
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/important-soon, approved, triage/accepted

#13071 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, approved, needs-kind, needs-triage, needs-priority

#13072 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, approved, needs-kind, needs-triage, needs-priority

#13074 Release controller v1.11.5 & chart v4.11.5.
  README.md
  changelog/controller-1.11.5.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.11.5.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13075 Release controller v1.12.1/v1.11.5 & chart v4.12.1/v4.11.5.
  README.md
  changelog/controller-1.11.5.md
  changelog/controller-1.12.1.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.11.5.md
  charts/ingress-nginx/changelog/helm-chart-4.12.1.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
  docs/e2e-tests.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, do-not-merge/hold, approved, kind/cleanup, triage/accepted, area/helm

#13080 Go: Fix Mage.
  go.mod
  go.sum
  magefiles/go.mod
  magefiles/go.sum
Labels: cncf-cla: yes, lgtm, size/L, kind/bug, priority/backlog, approved, triage/accepted

#13077 Go: Fix Mage.
  go.mod
  go.sum
  magefiles/go.mod
  magefiles/go.sum
Labels: cncf-cla: yes, lgtm, size/L, kind/bug, priority/backlog, approved, triage/accepted

#13106 Docs: Fix OpenTelemetry listing.
  docs/user-guide/third-party-addons/opentelemetry.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#13102 Plugin: Improve error handling.
  cmd/plugin/kubectl/kubectl.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/backlog, needs-ok-to-test, approved, triage/accepted

#13114 Images: Extract modules.
  go.mod
  go.sum
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, kind/bug, priority/backlog, approved, triage/accepted

#13117 Images: Fix FromAsCasing.
  images/custom-error-pages/rootfs/Dockerfile
  images/ext-auth-example-authsvc/rootfs/Dockerfile
  images/fastcgi-helloserver/rootfs/Dockerfile
  images/go-grpc-greeter-server/rootfs/Dockerfile
  images/kube-webhook-certgen/rootfs/Dockerfile
  rootfs/Dockerfile-chroot
Labels: cncf-cla: yes, lgtm, size/S, kind/bug, priority/backlog, approved, triage/accepted

#13120 CI: Do not fail fast.
  .github/workflows/ci.yaml
  .github/workflows/images.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted
