Repository kubernetes/ingress-nginx, pull requests merged in 2025-04, with the labels that each got.

#13110 Annotations: Allow ciphers with underscores.
  internal/ingress/annotations/sslcipher/main.go
  internal/ingress/annotations/sslcipher/main_test.go
Labels: cncf-cla: yes, lgtm, size/XS, kind/bug, priority/backlog, needs-ok-to-test, approved, triage/accepted

#13146 Go: Bump to v1.24.2.
  GOLANG_VERSION
  go.mod
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13147 Go: Update dependencies.
  go.mod
  go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13149 Go: Update dependencies.
  go.mod
  go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13150 Go: Bump to v1.24.2.
  GOLANG_VERSION
  go.mod
  images/custom-error-pages/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/fastcgi-helloserver/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.mod
Labels: cncf-cla: yes, lgtm, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13190 Docs: Fix link in installation instructions.
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#13209 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13211 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13212 Bump github.com/onsi/ginkgo/v2 from 2.23.3 to 2.23.4
  build/run-in-docker.sh
  images/test-runner/Makefile
  test/e2e/run-chart-test.sh
  test/e2e/run-kind-e2e.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13218 Images: Trigger NGINX build.
  images/nginx/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13219 Images: Trigger NGINX build.
  images/nginx/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13220 Images: Trigger NGINX build.
  images/nginx/TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13221 Images: Bump `NGINX_BASE` to v2.0.2.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13222 Images: Bump `NGINX_BASE` to v1.2.2.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13223 Images: Bump `NGINX_BASE` to v0.3.2.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13225 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13228 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, priority/backlog, approved, kind/cleanup, triage/accepted

#13232 Tests: Bump Test Runner to v2.0.2.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13233 Tests: Bump Test Runner to v1.3.2.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13234 Tests: Bump Test Runner to v1.3.2.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13171 Docs: Enable metrics in manifest-based deployments.
  docs/user-guide/monitoring.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#13239 Docs: Improve formatting in `monitoring.md`.
  docs/user-guide/monitoring.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, approved, kind/cleanup, triage/accepted

#13247 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
Labels: cncf-cla: yes, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13246 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
Labels: cncf-cla: yes, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13245 Go: Update dependencies.
  go.mod
  go.sum
  images/custom-error-pages/rootfs/go.mod
  images/custom-error-pages/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
Labels: cncf-cla: yes, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13242 Docs: How to modify NLB TCP timeout.
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XS, priority/backlog, needs-ok-to-test, kind/documentation, approved, triage/accepted

#13254 CI: Update Kubernetes to v1.32.4.
  .github/workflows/ci.yaml
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13255 CI: Update Kubernetes to v1.32.4.
  .github/workflows/ci.yaml
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13256 CI: Update Kubernetes to v1.32.4.
  .github/workflows/ci.yaml
  images/test-runner/Makefile
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13259 Go: Update dependencies.
  go.mod
  go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13257 Go: Update dependencies.
  go.mod
  go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13260 Go: Update dependencies.
  go.mod
  go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13266 Images: Bump NGINX to v1.2.3.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13265 Images: Bump NGINX to v2.0.3.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13267 Images: Bump NGINX to v0.3.3.
  NGINX_BASE
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13268 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13269 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13270 Images: Trigger Test Runner build.
  images/test-runner/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13282 Go: Update dependencies.
  go.mod
  go.sum
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13284 Go: Update dependencies.
  go.mod
  go.sum
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13283 Go: Update dependencies.
  go.mod
  go.sum
  images/ext-auth-example-authsvc/rootfs/go.mod
  images/ext-auth-example-authsvc/rootfs/go.sum
  images/go-grpc-greeter-server/rootfs/go.mod
  images/go-grpc-greeter-server/rootfs/go.sum
  images/kube-webhook-certgen/rootfs/go.mod
  images/kube-webhook-certgen/rootfs/go.sum
Labels: cncf-cla: yes, lgtm, size/M, priority/backlog, approved, kind/cleanup, triage/accepted

#13286 Tests: Bump Test Runner to v2.0.3.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13287 Tests: Bump Test Runner to v1.3.3.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13288 Tests: Bump Test Runner to v1.3.3.
  build/run-in-docker.sh
  test/e2e-image/Makefile
  test/e2e/run-chart-test.sh
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13289 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13290 Images: Trigger other builds (1/2).
  images/cfssl/TAG
  images/custom-error-pages/TAG
  images/e2e-test-echo/TAG
  images/ext-auth-example-authsvc/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13292 Images: Trigger other builds (2/2).
  images/fastcgi-helloserver/TAG
  images/go-grpc-greeter-server/TAG
  images/httpbun/TAG
  images/kube-webhook-certgen/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13293 Images: Trigger other builds (2/2).
  images/fastcgi-helloserver/TAG
  images/go-grpc-greeter-server/TAG
  images/httpbun/TAG
  images/kube-webhook-certgen/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13294 Images: Trigger other builds (2/2).
  images/fastcgi-helloserver/TAG
  images/go-grpc-greeter-server/TAG
  images/httpbun/TAG
  images/kube-webhook-certgen/TAG
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13307 Tests & Docs: Bump images.
  docs/examples/canary/README.md
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/examples/customization/external-auth-headers/echo-service.yaml
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/deployment.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13309 Tests & Docs: Bump images.
  docs/examples/canary/README.md
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/examples/customization/external-auth-headers/echo-service.yaml
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/deployment.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13308 Tests & Docs: Bump images.
  docs/examples/canary/README.md
  docs/examples/customization/custom-errors/custom-default-backend.helm.values.yaml
  docs/examples/customization/custom-errors/custom-default-backend.yaml
  docs/examples/customization/external-auth-headers/echo-service.yaml
  test/e2e/HTTPBUN_IMAGE
  test/e2e/framework/deployment.go
  test/e2e/framework/fastcgi_helloserver.go
  test/e2e/settings/ocsp/ocsp.go
Labels: cncf-cla: yes, lgtm, area/docs, size/S, priority/backlog, approved, kind/cleanup, triage/accepted

#13310 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13311 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13312 Chart: Bump Kube Webhook CertGen.
  charts/ingress-nginx/README.md
  charts/ingress-nginx/values.yaml
Labels: cncf-cla: yes, lgtm, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13313 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13314 Images: Trigger controller build.
  TAG
Labels: cncf-cla: yes, size/XS, priority/backlog, approved, kind/cleanup, triage/accepted

#13316 Release controller v1.12.2 & chart v4.12.2.
  README.md
  changelog/controller-1.12.2.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.12.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13317 Release controller v1.11.6 & chart v4.11.6.
  README.md
  changelog/controller-1.11.6.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.11.6.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm

#13318 Release controller v1.12.2/v1.11.6 & chart v4.12.2/v4.11.6.
  README.md
  changelog/controller-1.11.6.md
  changelog/controller-1.12.2.md
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/README.md
  charts/ingress-nginx/changelog/helm-chart-4.11.6.md
  charts/ingress-nginx/changelog/helm-chart-4.12.2.md
  charts/ingress-nginx/values.yaml
  deploy/static/provider/aws/deploy.yaml
  deploy/static/provider/aws/nlb-with-tls-termination/deploy.yaml
  deploy/static/provider/baremetal/deploy.yaml
  deploy/static/provider/cloud/deploy.yaml
  deploy/static/provider/do/deploy.yaml
  deploy/static/provider/exoscale/deploy.yaml
  deploy/static/provider/kind/deploy.yaml
  deploy/static/provider/oracle/deploy.yaml
  deploy/static/provider/scw/deploy.yaml
  docs/deploy/index.md
Labels: cncf-cla: yes, lgtm, area/docs, size/XL, priority/backlog, approved, kind/cleanup, triage/accepted, area/helm
